<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Company_Name</name>
   <tag></tag>
   <elementGuidId>ba39fc89-3eed-4b08-b436-48c5840bc033</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @name = 'billingCompanyname' and @id = 'billingCompanyname']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2bc35604-b922-41a8-affb-d25dc3f8544d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billingCompanyname</value>
      <webElementGuid>254dd2fb-d264-4ff2-8539-7186cca703b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billingCompanyname</value>
      <webElementGuid>7d4df8cf-2e69-41a3-87bd-d074041bf9e0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
