<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PaymentDate</name>
   <tag></tag>
   <elementGuidId>1c638c4d-3931-4353-b141-db3d3fbd14af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='paymentDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#paymentDate</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;paymentDate&quot;)[count(. | //*[@class = 'form-control' and @id = 'paymentDate' and @name = 'paymentDate']) = count(//*[@class = 'form-control' and @id = 'paymentDate' and @name = 'paymentDate'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#paymentDate</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>340f2a36-e54d-4ec1-8c3a-13c730ad1126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>92415b3d-936e-4507-8dae-f06484983bfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9a5c4d79-44ba-423e-b4f9-36fe1dfbf51f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>paymentDate</value>
      <webElementGuid>17730d8b-01a3-4efb-8f7e-8701d442a922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>paymentDate</value>
      <webElementGuid>25551a34-aa0e-4c0c-9cf0-616b78cbca36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>02/10/2026</value>
      <webElementGuid>0b5a50d2-039d-4bab-b661-a986ee4a3334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2eb9ac66-d662-4bef-8441-4c89673e6c25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paymentDate&quot;)</value>
      <webElementGuid>06bfed88-e66b-41e1-ad3d-9fed95772c56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='paymentDate']</value>
      <webElementGuid>9e15a829-8513-4099-b99d-d0c285875c37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='velocityForm']/div/div[8]/div[3]/input</value>
      <webElementGuid>af1b548d-a634-4241-9b03-4271dfe85983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[3]/input</value>
      <webElementGuid>a1ef300f-8835-427a-9953-7f08fa7880b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'paymentDate' and @name = 'paymentDate']</value>
      <webElementGuid>31d22679-ef9c-430a-afb0-a29b9acdba82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
