<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CardHolderName</name>
   <tag></tag>
   <elementGuidId>c7f03007-77e1-4734-8e28-32e906c2c169</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='emvCardHolderName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#emvCardHolderName</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;emvCardHolderName&quot;)[count(. | //*[@name = 'emvCardHolderName' and @id = 'emvCardHolderName' and @class = 'form-control']) = count(//*[@name = 'emvCardHolderName' and @id = 'emvCardHolderName' and @class = 'form-control'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#emvCardHolderName</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bfd4eecf-3892-4ab6-9ba8-01a2f22df0d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>53a4d2f7-e295-4912-9896-b7dce9a6d108</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>emvCardHolderName</value>
      <webElementGuid>dfa7163e-0eb3-4286-ac80-39c09a106304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>d129a669-ec4e-481b-941a-f8120ea27505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>emvCardHolderName</value>
      <webElementGuid>bb2ffd73-2245-4af6-9586-06966bbccc8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>04a33fea-55f5-4bdf-bfe9-8a1d2237db65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;emvCardHolderName&quot;)</value>
      <webElementGuid>5cb185af-7f85-44cf-a555-6c813687d109</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='emvCardHolderName']</value>
      <webElementGuid>daf0a376-cedc-4b9b-824b-79d34b64708d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cc-emv-fields']/div/div[3]/input</value>
      <webElementGuid>2d3348c7-2388-4c93-876e-48b901ea3ae0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[3]/input</value>
      <webElementGuid>ca368c1e-2811-4ce4-9aae-f86e37655fc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'emvCardHolderName' and @id = 'emvCardHolderName']</value>
      <webElementGuid>efa59bcf-7897-434c-a8e3-6a77cc686ed5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
