<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_AddressLine1</name>
   <tag></tag>
   <elementGuidId>a2035fdb-3791-440a-b431-ccec8b56be92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addressLine1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#addressLine1</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;addressLine1&quot;)[count(. | //*[@name = 'billingAddress1' and @id = 'addressLine1' and @class = 'form-control']) = count(//*[@name = 'billingAddress1' and @id = 'addressLine1' and @class = 'form-control'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#addressLine1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d90fd22b-3cd3-47a0-8741-cfd7d0379b5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>89d3e6ee-6b4b-4ada-8de7-275fc3a8edf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billingAddress1</value>
      <webElementGuid>ecd6c3ef-1bf2-404f-b674-e6f3590f5b92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>aa1fbff8-1782-4bb0-bec1-616cf2b95e1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addressLine1</value>
      <webElementGuid>08a16b17-4599-4fb3-93c4-4b641deedfdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d606a24f-53bd-4a37-8d9e-0edc52d1bbb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addressLine1&quot;)</value>
      <webElementGuid>078d1b50-aa94-41ad-84bd-51a9e1f8d5a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addressLine1']</value>
      <webElementGuid>9df63eb3-99a1-41b9-8177-dc78a716d5b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='velocityForm']/div/div[8]/div[5]/input</value>
      <webElementGuid>8014d39c-5c74-4ea9-aece-f34ad6ca2724</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[5]/input</value>
      <webElementGuid>435e85b5-a318-42dc-a2c6-1113950acfdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'billingAddress1' and @id = 'addressLine1']</value>
      <webElementGuid>4b7e540e-3f78-4777-a4ba-777e388caf8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
