<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_EMVCloudTerminal</name>
   <tag></tag>
   <elementGuidId>31c6a0d3-7149-4ea6-865c-7363591abfc6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='label-method-EMVCloud']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#label-method-EMVCloud</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;label-method-EMVCloud&quot;)[count(. | //*[@id = 'label-method-EMVCloud' and @class = 'btn btn-tab active' and (text() = 'EMV Cloud Terminal' or . = 'EMV Cloud Terminal')]) = count(//*[@id = 'label-method-EMVCloud' and @class = 'btn btn-tab active' and (text() = 'EMV Cloud Terminal' or . = 'EMV Cloud Terminal')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#label-method-EMVCloud</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>39350094-d982-4f8d-a2c6-2bcd9c20f8c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>label-method-EMVCloud</value>
      <webElementGuid>0e3bcfce-229c-40c0-9764-00a48d71db4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-tab active</value>
      <webElementGuid>26853294-a793-4c4c-b2d6-aa8e816c661b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>velocityForm_paymentMethodEMVCloud</value>
      <webElementGuid>1bb335e8-e67c-4377-9ec5-6a6a847a9554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EMV Cloud Terminal</value>
      <webElementGuid>6d020ce9-08a2-4259-b714-5eb3c4bca1e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;label-method-EMVCloud&quot;)</value>
      <webElementGuid>49ef07ed-4d1f-472f-9f2b-f0d28ee38e3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='label-method-EMVCloud']</value>
      <webElementGuid>6a4faae2-8bec-420b-bdff-650e374d4fb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='velocityForm']/div/div[3]/label[5]</value>
      <webElementGuid>f573c4d5-9d6e-4c6a-b90a-c1c4c5bab8b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business Check'])[1]/following::label[1]</value>
      <webElementGuid>32171ba9-8351-4366-8dbe-eb0795ad13c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personal Check'])[1]/following::label[2]</value>
      <webElementGuid>48de5760-c779-476b-92ff-051e0d3cb637</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit Card'])[2]/preceding::label[1]</value>
      <webElementGuid>92458a76-cd24-4cf6-bc91-3b97bbf65bb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personal Checking /Savings'])[1]/preceding::label[2]</value>
      <webElementGuid>2a81f620-58b8-450f-b525-98ac1230719c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[5]</value>
      <webElementGuid>337df9fa-378b-4d3b-812a-70508f804295</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'label-method-EMVCloud' and (text() = 'EMV Cloud Terminal' or . = 'EMV Cloud Terminal')]</value>
      <webElementGuid>f3e3e26d-5ee8-4879-9d1d-ace1a0e6f8eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
