<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Terminal</name>
   <tag></tag>
   <elementGuidId>bc52d648-9254-48f7-a11b-00b4f1297ba5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;terminals&quot;)[count(. | //*[@class = 'form-select form-control' and @id = 'terminals']) = count(//*[@class = 'form-select form-control' and @id = 'terminals'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#terminals</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='terminals']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Select a terminal  *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>12ef9fa3-d835-48d8-bb5b-fb1af9fe70ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select form-control</value>
      <webElementGuid>bd1b52e9-998f-4f23-9bea-1b6db75224ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>terminals</value>
      <webElementGuid>0650afa3-2545-40b4-bc9c-9a991d70052d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>terminals</value>
      <webElementGuid>d810527b-9e5f-487b-8b8b-a751abd9b3f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d8294c4c-e003-4f2b-826c-87e995be19c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>201b3c8f-be08-4b4c-b854-de936d399f6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>populateTerminalFields()</value>
      <webElementGuid>7fa1fadf-8919-4822-8381-086457f9d040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select One016 - NOT CONNECTED003 - NOT CONNECTED012 - NOT CONNECTED009 - NOT CONNECTEDDallas3K3 - NOT CONNECTED015 - NOT CONNECTED002 - NOT CONNECTED008 - NOT CONNECTEDDallas3K6 - NOT CONNECTED011 - NOT CONNECTED010 - NOT CONNECTEDDallas3K4 - NOT CONNECTEDDallas3K1 - NOT CONNECTED014 - NOT CONNECTED007 - NOT CONNECTED001 - NOT CONNECTEDDallas3K205212025 PCL Cloud - NOT CONNECTED005 - NOT CONNECTED006 - NOT CONNECTEDDallas3K5 - NOT CONNECTED ✅004 - NOT CONNECTED007 - NOT CONNECTED017 - NOT CONNECTED013 - NOT CONNECTED</value>
      <webElementGuid>4b33f1cc-78b4-4c23-996d-3203c2474ce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;terminals&quot;)</value>
      <webElementGuid>f33eddc5-78a1-496f-a3bb-e922abda8869</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='terminals']</value>
      <webElementGuid>bb9231c9-ae6c-456c-86b9-01fa04441378</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cc-emv-fields']/div/div[2]/select</value>
      <webElementGuid>f7e5af3e-cea0-47db-b860-41264912f1a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::select[1]</value>
      <webElementGuid>f36475ff-fae1-47db-a750-c1bfccb77c24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select a terminal'])[1]/preceding::select[1]</value>
      <webElementGuid>d9b800b3-97dd-4946-a17d-0b5269b5ec56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The selected EMV terminal is not connected to the network. Please choose a different terminal.'])[1]/preceding::select[1]</value>
      <webElementGuid>3d50ca94-db7b-437e-9529-6b155f4addc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>a1246f89-4e09-4e5e-814d-3465d3f66a74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'terminals' and @id = 'terminals' and (text() = 'Select One016 - NOT CONNECTED003 - NOT CONNECTED012 - NOT CONNECTED009 - NOT CONNECTEDDallas3K3 - NOT CONNECTED015 - NOT CONNECTED002 - NOT CONNECTED008 - NOT CONNECTEDDallas3K6 - NOT CONNECTED011 - NOT CONNECTED010 - NOT CONNECTEDDallas3K4 - NOT CONNECTEDDallas3K1 - NOT CONNECTED014 - NOT CONNECTED007 - NOT CONNECTED001 - NOT CONNECTEDDallas3K205212025 PCL Cloud - NOT CONNECTED005 - NOT CONNECTED006 - NOT CONNECTEDDallas3K5 - NOT CONNECTED ✅004 - NOT CONNECTED007 - NOT CONNECTED017 - NOT CONNECTED013 - NOT CONNECTED' or . = 'Select One016 - NOT CONNECTED003 - NOT CONNECTED012 - NOT CONNECTED009 - NOT CONNECTEDDallas3K3 - NOT CONNECTED015 - NOT CONNECTED002 - NOT CONNECTED008 - NOT CONNECTEDDallas3K6 - NOT CONNECTED011 - NOT CONNECTED010 - NOT CONNECTEDDallas3K4 - NOT CONNECTEDDallas3K1 - NOT CONNECTED014 - NOT CONNECTED007 - NOT CONNECTED001 - NOT CONNECTEDDallas3K205212025 PCL Cloud - NOT CONNECTED005 - NOT CONNECTED006 - NOT CONNECTEDDallas3K5 - NOT CONNECTED ✅004 - NOT CONNECTED007 - NOT CONNECTED017 - NOT CONNECTED013 - NOT CONNECTED')]</value>
      <webElementGuid>c2039d76-a4ff-457e-855e-62eef88e72b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
