<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Exit</name>
   <tag></tag>
   <elementGuidId>cbe04fee-2ee1-4d4b-a5a2-eeef3e019da8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-md-1.col-sm-3.col-xs-12.bootstrap-btn-group > input.btn.btn-default.btn-block</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Exit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d46457e7-fb2b-4027-80a5-c345251c2d13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f25adf02-ea5e-4c6c-b5c8-77d7f3687f26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default btn-block</value>
      <webElementGuid>b9269fc3-db77-41d9-93d9-0a2f0a990872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Exit</value>
      <webElementGuid>5801ef40-c6d6-446e-a324-02ce9e29eb1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>location.href='https://www.dallascounty.org/departments/tax/?remittance_id=dfdf43543fgdghgh&amp;security_id=804bd70a4002b88b87727cedfdc6db7b&amp;application_id=836';</value>
      <webElementGuid>07e8676b-f1a4-4bdf-b6c2-9a09dbe1818e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container&quot;]/div[@class=&quot;panel panel-default&quot;]/div[@class=&quot;panel-body&quot;]/form[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-1 col-sm-3 col-xs-12 bootstrap-btn-group&quot;]/input[@class=&quot;btn btn-default btn-block&quot;]</value>
      <webElementGuid>60d178ba-b1fe-4d66-ad55-de4a2e9ad0cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Exit']</value>
      <webElementGuid>65a99606-fb4e-4ec9-9929-b8be00da8ea7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>8ea86d4b-3796-48f6-bfbb-637a44eebc8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>68138061-6b4d-4856-aa24-34114efc8bb7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
