<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_RejectFee</name>
   <tag></tag>
   <elementGuidId>4051004c-5e30-47a5-979f-70c98b1cc5d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-md-3.col-sm-4.col-xs-12.bootstrap-btn-group > input[name=&quot;convFeeNotifyAction&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='convFeeNotifyAction'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3ef96ce5-1b21-4b4e-88fe-c41cacdaaca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>954c92cf-0d61-43e7-9f94-04e25f0b7d98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default btn-block</value>
      <webElementGuid>f1b34139-e9b6-4ed0-9d82-856a1f16d5c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>convFeeNotifyAction</value>
      <webElementGuid>423bb871-9fc8-4b85-84d1-ae36c51553af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Reject Fee and Exit</value>
      <webElementGuid>e2ff8de5-e72d-4a0b-a973-1da6c9537b70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>setCancelPayment();</value>
      <webElementGuid>90059979-bc10-4225-bb2d-cf4688ef3b74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container&quot;]/div[@class=&quot;panel panel-default&quot;]/div[@class=&quot;panel-body&quot;]/form[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-3 col-sm-4 col-xs-12 bootstrap-btn-group&quot;]/input[@class=&quot;btn btn-default btn-block&quot;]</value>
      <webElementGuid>420913e1-310d-4c7c-9ff3-fca862c285f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='convFeeNotifyAction'])[2]</value>
      <webElementGuid>0b3e03b3-4892-4187-880b-093e376fad98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>818e58ab-3bf0-47d2-9c8b-efc916c12abf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'convFeeNotifyAction']</value>
      <webElementGuid>68253910-acec-4cb9-9c14-73377d1decce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
