<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TotalAmount</name>
   <tag></tag>
   <elementGuidId>68f76d67-44f5-4b4b-be10-2126b2348356</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;receiptForm&quot;]/div/div[5]/div[2]/div/div[4]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;receiptForm&quot;]/div/div[5]/div[2]/div/div[4]/div[2]</value>
      <webElementGuid>64b3223f-83fd-476b-b97d-f09443c4fc2e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
