<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TransactionType</name>
   <tag></tag>
   <elementGuidId>d2730d46-7244-4858-a58f-99daa93c0f83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;receiptForm&quot;]/div/div[5]/div[1]/div/div[3]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;receiptForm&quot;]/div/div[5]/div[1]/div/div[3]/div[2]</value>
      <webElementGuid>1f822b5b-bd03-4310-883e-bfca372952d8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
