<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>UserDefinedField1Confirm</name>
   <tag></tag>
   <elementGuidId>62d97df4-94ea-4556-8f4b-9adec88d9696</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;receiptForm&quot;]/div/div[5]/div[2]/div/div[5]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;receiptForm&quot;]/div/div[5]/div[2]/div/div[5]/div[2]</value>
      <webElementGuid>fbffea07-4946-4b20-aaaa-71c687fdd2d6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
