<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_RoutingNumber</name>
   <tag></tag>
   <elementGuidId>17dfce92-beef-4087-91a8-bb5f7e4abc21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#routingNumberBC</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='routingNumberBC']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#routingNumberBC</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>72be3c7d-e0d4-4c3c-a6c4-5478c7c4d8a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>48e2d080-e124-4326-b198-d7d19930736e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>routingNumberBC</value>
      <webElementGuid>eb5b3002-4401-4634-9844-43ee3824c12c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>acafd854-b2fd-4e7e-b412-da47f8f21954</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>routingNumberBC</value>
      <webElementGuid>3532a2c5-0995-4df2-a24f-1e33f02b7972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0c3c8119-87d0-4069-a6da-b1264b9744ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>validateRTN(this, 'routingName_bc','billing-routingNumber-input-err-bc','billing-routingNumber-input-err-from-formbean-bc')</value>
      <webElementGuid>741ab739-07c3-4881-8a7c-0cf256e5a360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>76ea71c7-c783-4c10-a6ad-b300e7a278fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>\d{9}</value>
      <webElementGuid>f62d91e3-f315-48b9-8c16-8b71123b0f9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;routingNumberBC&quot;)</value>
      <webElementGuid>be167d89-19e1-4253-b9c6-3ad7b68d6a15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='routingNumberBC']</value>
      <webElementGuid>4beceab5-94b2-4670-8345-8106608b58ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='business-check-fields']/div/div/input</value>
      <webElementGuid>ace76a53-d742-4cf1-ad10-0593fbffb404</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/input</value>
      <webElementGuid>e1c8be8a-df80-4afd-a543-e8c00ddd891c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'routingNumberBC' and @id = 'routingNumberBC']</value>
      <webElementGuid>48fd01f2-4d40-48fd-9720-7c9ed5338d01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
