<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Country</name>
   <tag></tag>
   <elementGuidId>3c683a60-c988-4f8b-88cf-3141e95d81d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#billing-country-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='billing-country-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#billing-country-input</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4e77dd7d-ced4-41a6-836d-92abd3852fc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>07bb6efb-e9e7-46f8-8772-e4ebe822c32d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billingCountry</value>
      <webElementGuid>27b939ba-601d-4569-a789-6c26c25ab9bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billing-country-input</value>
      <webElementGuid>1e5fd6a9-f415-4bc2-9b13-c37166799809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>6775c5f3-6e39-433c-9ae1-113f169166c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
		            		United States
		            	</value>
      <webElementGuid>dfbc3dd3-6a5b-4e9f-9c04-f4343e548cb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billing-country-input&quot;)</value>
      <webElementGuid>92609f62-0218-44b7-a3b9-67426838f77b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='billing-country-input']</value>
      <webElementGuid>3c5708bd-ebf3-43d5-afbe-93651309226b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='velocityForm']/div/div[8]/div[4]/select</value>
      <webElementGuid>afc3cbdf-f90e-4681-a395-df98287d8173</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[19]/following::select[1]</value>
      <webElementGuid>0d6b0e3d-2db0-4b13-b1f9-1424e868275e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[20]/preceding::select[1]</value>
      <webElementGuid>9ea99089-039b-49ee-87b1-1d5d7e0b892d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[4]/select</value>
      <webElementGuid>c898bdbf-b333-47ee-9846-647da64f8c15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'billingCountry' and @id = 'billing-country-input' and (text() = '
		            		United States
		            	' or . = '
		            		United States
		            	')]</value>
      <webElementGuid>72bc6c71-18b1-4f32-a1a0-6d802bf32b43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
