<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_JointFiling_userType_New</name>
   <tag></tag>
   <elementGuidId>d84f3ae0-57da-4041-9b9b-6cd830227576</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='joint']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#joint</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'userType' and @type = 'radio' and @id = 'joint']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>81ac2533-4371-441f-a074-86dbea5f84f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>7157ffae-e490-4c51-8ccb-2f4d60ff2539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>joint</value>
      <webElementGuid>81d012a2-08b8-482c-ab0f-d5a536824d0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>userType</value>
      <webElementGuid>2fd32813-043b-4e7b-a9e1-d35719691a2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>84970925-9b1d-4d92-91a2-8bc87ecab84b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>joint</value>
      <webElementGuid>4315ddf1-c2a8-48d1-abad-97c41d42f443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;joint&quot;)</value>
      <webElementGuid>c561d8b1-722e-4895-a0c2-b6bd6ea6bc6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='joint']</value>
      <webElementGuid>6c84d3dc-fe4e-435e-8205-c0ff976b6ac1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='taxForm']/div[7]/div[2]/div[2]/div[2]/input</value>
      <webElementGuid>fcb71e9d-fe44-4e19-a5e9-654dbac76c90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>93817d1f-de09-4beb-a973-1b51e5959383</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'userType' and @type = 'radio' and @id = 'joint']</value>
      <webElementGuid>2a1361ab-ade6-4bc2-bdfa-84711f3a0514</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
