<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pay by Credit or Debit Card</name>
   <tag></tag>
   <elementGuidId>7e687af1-bdf6-4e58-a496-b5c71d9b5874</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CC</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CC']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8113e92d-7d94-4576-85a1-dfc8f895b8c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>39be2b84-f293-40f2-a317-e867fd98ed28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CC</value>
      <webElementGuid>12a9a6b4-d8ca-42fb-99e9-c87b8c3b5a52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9f9bb133-40a2-4813-a3dd-c5d07e1eed71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>paymentMethodSelect</value>
      <webElementGuid>4284b144-b99f-46ae-a798-b2db51a6b3bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9f73a995-e812-46bb-9774-0f24c762dcd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CC&quot;)</value>
      <webElementGuid>bfa061bd-aafc-4122-b1b1-384cb9045e81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CC']</value>
      <webElementGuid>5cd1c967-0198-48cc-a8e2-9ecaa39b045b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/form/input</value>
      <webElementGuid>57708df7-46ef-4713-b9cf-f97ff022797d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'CC' and @name = 'paymentMethodSelect']</value>
      <webElementGuid>5f8fb2e0-0158-4713-a385-ede3a8419783</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
