<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pay by Personal Check</name>
   <tag></tag>
   <elementGuidId>ce43454b-3add-4fc1-922b-47051d6c50d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PC</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PC']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>156ad32b-c48c-4438-a42f-fa5b4ea80bca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>72a47740-51b7-4136-a677-1e3082125e8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PC</value>
      <webElementGuid>4d916468-75a5-4cf6-a369-dd563d1e39f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>P</value>
      <webElementGuid>081ca2a9-04c5-4435-9001-52f0074d5079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>paymentMethodSelect</value>
      <webElementGuid>c0602825-167f-4091-b6b1-9278fe28a10b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>d4d0a605-ff96-47ad-8f0a-8b54adbc0987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PC&quot;)</value>
      <webElementGuid>10716c0b-5d27-473f-9a0e-b92f71e0c974</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PC']</value>
      <webElementGuid>80ec7d96-1dc8-495f-b3e5-7da3db92c1e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/label/form/input</value>
      <webElementGuid>f01bd833-213a-4f7f-bc33-346934dd855a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'PC' and @name = 'paymentMethodSelect']</value>
      <webElementGuid>f31bbe93-599c-4677-ae62-3271abf7d8f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
