<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_cvv_Demo</name>
   <tag></tag>
   <elementGuidId>f58d4ade-541b-4b86-be25-7fd7097ed005</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cvv']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cvv</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'password_paymentMethodForm.cvv' and @id = 'password_cvv']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password_paymentMethodForm.cvv</value>
      <webElementGuid>807ead20-a5e8-4a42-b34a-34bf68cf2655</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>password_cvv</value>
      <webElementGuid>ef06d679-b2a9-4679-b104-8778afe24cb5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cvv']</value>
      <webElementGuid>aec1ae14-d849-40ed-b19f-4fe0a95503d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area_creditCard']/table/tbody/tr[4]/td[2]/input</value>
      <webElementGuid>e4bdca9d-f259-4420-adf7-73aa8603f9ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/input</value>
      <webElementGuid>2495c59d-7297-44ae-b602-01fc4dd63007</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'paymentMethodForm.cvv' and @id = 'cvv' and @alt = 'CVV']</value>
      <webElementGuid>dfecf6ec-ebd2-4e61-95e7-087eab424432</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
