import internal.GlobalVariable as GlobalVariable
import com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords as WebUI

WebUI.openBrowser('https://www.google.com/')
String baseUrl = "https://www.google.com/"
int pageLoadTimeoutSeconds = 30
def to = { String locator -> CustomKeywords.'customClasses.LegacyLocatorUtils.testObjectFromLegacyLocator'(locator) }

def bbpURL = GlobalVariable.BBPURL
if (bbpURL?.startsWith('http://') || bbpURL?.startsWith('https://')) {
	WebUI.navigateToUrl(bbpURL)
} else {
	WebUI.navigateToUrl(baseUrl + bbpURL)
}


WebUI.setText(to("id=field1"), "111150")
WebUI.setText(to("id=field2"), "111151")
WebUI.click(to("name=Test"))
WebUI.delay(2)
WebUI.click(to("name=paysubmit"))
WebUI.waitForPageLoad(pageLoadTimeoutSeconds)
WebUI.click(to("xpath=(//input[@name='paymentMethod'])[2]"))
WebUI.click(to("css=input[type=\"submit\"]"))
WebUI.waitForPageLoad(pageLoadTimeoutSeconds)
//softAssertion.assertEquals("Required fields are highlighted with an asterisk.", selenium.getText("css=span.required"))
//softAssertion.assertEquals("Please enter the following billing information about your payment:", selenium.getText("css=span.vrelay-header"))

WebUI.verifyTextPresent(("Required fields are highlighted with an asterisk."), true)
WebUI.verifyTextPresent(("Please enter the following billing information about your payment:"), true)


WebUI.setText(to("name=amount"), ("13.00").toString())
WebUI.setText(to("name=userDefined2"), ("UDF2 Data2").toString())
WebUI.setText(to("name=userDefined3"), ("UDF3 Data2").toString())
WebUI.selectOptionByLabel(to("name=variableField4DropdownGroupItemID"), "Purple", false)
WebUI.selectOptionByLabel(to("name=variableField5DropdownGroupItemID"), "Orange", false)
WebUI.setText(to("name=userDefined6"), ("UDF6 Data2").toString())
WebUI.setText(to("name=userDefined7"), ("UDF7 Data2").toString())
WebUI.setText(to("name=userDefined8"), ("UDF8 Data2").toString())
WebUI.setText(to("name=billingFirstname"), "Molly")
WebUI.setText(to("name=billingLastname"), "Hunter")
WebUI.setText(to("id=routingNumber"), "256072691")
WebUI.setText(to("id=accountNumber"), "11111111")
WebUI.setText(to("id=confirmAccountNumber"), "11111111")
WebUI.click(to("name=accountType"))
WebUI.setText(to("name=billingAddress"), ("2311 york road").toString())
WebUI.setText(to("name=billingAddress2"), ("Suite 600").toString())
WebUI.setText(to("id=billing-zip-input"), "21054")
WebUI.setText(to("name=emailAddress"), ("iahmed@govolution.com").toString())
WebUI.click(to("id=checkedAcceptCondition"))
WebUI.click(to("name=achSubmit"))
WebUI.waitForPageLoad(pageLoadTimeoutSeconds)

WebUI.verifyTextPresent(("Please verify the following information:"), true)
WebUI.verifyTextPresent(("Is this information correct"), true)


//selenium.selectWindow("null")
//softAssertion.assertEquals("$13.00", selenium.getText("//tr[5]/td[3]"))
//softAssertion.assertEquals("UDF2 Data2", selenium.getText("//tr[7]/td[3]"))
//softAssertion.assertEquals("UDF3 Data2", selenium.getText("//tr[8]/td[3]"))
//softAssertion.assertEquals("Purple", selenium.getText("//tr[9]/td[3]"))
//softAssertion.assertEquals("Orange", selenium.getText("//tr[10]/td[3]"))
//softAssertion.assertEquals("UDF6 Data2", selenium.getText("//tr[11]/td[3]"))
//softAssertion.assertEquals("UDF7 Data2", selenium.getText("//tr[12]/td[3]"))
//softAssertion.assertEquals("UDF8 Data2", selenium.getText("//tr[13]/td[3]"))
//softAssertion.assertEquals("Molly", selenium.getText("//tr[16]/td[3]"))
//softAssertion.assertEquals("Hunter", selenium.getText("//tr[17]/td[3]"))
//softAssertion.assertEquals(Pattern.matches('selenium.getText("//tr[19]/td[3]")', '^exact:[\\s\\S]*[\\s\\S]*[\\s\\S]*[\\s\\S]*1111$'), true)
//softAssertion.assertEquals("Personal Checking", selenium.getText("//tr[20]/td[3]"))
//softAssertion.assertEquals("2311 york road", selenium.getText("//tr[21]/td[3]"))
//softAssertion.assertEquals("Suite 600", selenium.getText("//tr[22]/td[3]"))
//softAssertion.assertEquals("United States", selenium.getText("//tr[23]/td[3]"))
//softAssertion.assertEquals("GAMBRILLS", selenium.getText("//tr[24]/td[3]"))
//softAssertion.assertEquals("Maryland", selenium.getText("//tr[25]/td[3]"))
//softAssertion.assertEquals("21054", selenium.getText("//tr[26]/td[3]"))
//softAssertion.assertEquals("iahmed@govolution.com", selenium.getText("//tr[28]/td[3]"))

WebUI.verifyTextPresent(("13.00"), true)
WebUI.verifyTextPresent(("UDF2 Data2"), true)
WebUI.verifyTextPresent(("UDF3 Data2"), true)
WebUI.verifyTextPresent(("Purple"), true)
WebUI.verifyTextPresent(("Orange"), true)
WebUI.verifyTextPresent(("UDF6 Data2"), true)
WebUI.verifyTextPresent(("UDF7 Data2"), true)
WebUI.verifyTextPresent(("UDF8 Data2"), true)
WebUI.verifyTextPresent(("Molly"), true)
WebUI.verifyTextPresent(("Hunter"), true)
WebUI.verifyTextPresent(("1111"), true)
WebUI.verifyTextPresent(("Personal Checking"), true)
WebUI.verifyTextPresent(("2311 york road"), true)
WebUI.verifyTextPresent(("Suite 600"), true)
WebUI.verifyTextPresent(("United States"), true)
WebUI.verifyTextPresent(("GAMBRILLS"), true)
WebUI.verifyTextPresent(("Maryland"), true)
WebUI.verifyTextPresent(("21054"), true)
WebUI.verifyTextPresent(("iahmed@govolution.com"), true)


WebUI.click(to("xpath=(//input[@name='confirmNotifyAction'])[2]"))
WebUI.waitForPageLoad(pageLoadTimeoutSeconds)
WebUI.setText(to("name=amount"), ("20.00").toString())
WebUI.setText(to("name=userDefined2"), ("UDF2 Data2 Modified").toString())
WebUI.setText(to("name=userDefined3"), ("UDF3 Data2 Modified").toString())
WebUI.selectOptionByLabel(to("name=variableField4DropdownGroupItemID"), "Orange", false)
WebUI.selectOptionByLabel(to("name=variableField5DropdownGroupItemID"), "Purple", false)
WebUI.setText(to("name=userDefined6"), ("UDF6 Data2 Modified").toString())
WebUI.setText(to("name=userDefined7"), ("UDF7 Data2 Modified").toString())
WebUI.setText(to("name=userDefined8"), ("UDF8 Data2 Modified").toString())
WebUI.setText(to("name=billingFirstname"), "Jelly")
WebUI.setText(to("name=billingLastname"), "Jackson")
WebUI.setText(to("id=routingNumber"), "055002707")
WebUI.setText(to("id=accountNumber"), "22222222")
WebUI.setText(to("id=confirmAccountNumber"), "22222222")
WebUI.click(to("name=accountType"))
WebUI.setText(to("name=billingAddress"), ("15 Main Street").toString())
WebUI.setText(to("name=billingAddress2"), ("Building 2").toString())
WebUI.setText(to("id=billing-zip-input"), "22201")
WebUI.setText(to("name=emailAddress"), ("imtiazster@gmail.com").toString())
WebUI.click(to("name=achSubmit"))
WebUI.waitForPageLoad(pageLoadTimeoutSeconds)

WebUI.verifyTextPresent(("Please verify the following information:"), true)
WebUI.verifyTextPresent(("Is this information correct"), true)


//softAssertion.assertEquals("$20.00", selenium.getText("//tr[5]/td[3]"))
//softAssertion.assertEquals("UDF2 Data2 Modified", selenium.getText("//tr[7]/td[3]"))
//softAssertion.assertEquals("UDF3 Data2 Modified", selenium.getText("//tr[8]/td[3]"))
//softAssertion.assertEquals("Orange", selenium.getText("//tr[9]/td[3]"))
//softAssertion.assertEquals("Purple", selenium.getText("//tr[10]/td[3]"))
//softAssertion.assertEquals("UDF6 Data2 Modified", selenium.getText("//tr[11]/td[3]"))
//softAssertion.assertEquals("UDF7 Data2 Modified", selenium.getText("//tr[12]/td[3]"))
//softAssertion.assertEquals("UDF8 Data2 Modified", selenium.getText("//tr[13]/td[3]"))
//softAssertion.assertEquals("Jelly", selenium.getText("//tr[16]/td[3]"))
//softAssertion.assertEquals("Jackson", selenium.getText("//tr[17]/td[3]"))
//softAssertion.assertEquals(Pattern.matches('selenium.getText("//tr[18]/td[3]")', "2707.*"), true)
//softAssertion.assertEquals(Pattern.matches('selenium.getText("//tr[19]/td[3]")', '^exact:[\\s\\S]*[\\s\\S]*[\\s\\S]*[\\s\\S]*2222$'), true)
//softAssertion.assertEquals("Personal Checking", selenium.getText("//tr[20]/td[3]"))
//softAssertion.assertEquals("15 Main Street", selenium.getText("//tr[21]/td[3]"))
//softAssertion.assertEquals("Building 2", selenium.getText("//tr[22]/td[3]"))
//softAssertion.assertEquals("United States", selenium.getText("//tr[23]/td[3]"))
//softAssertion.assertEquals("ARLINGTON", selenium.getText("//tr[24]/td[3]"))
//softAssertion.assertEquals("Virginia", selenium.getText("//tr[25]/td[3]"))
//softAssertion.assertEquals("22201", selenium.getText("//tr[26]/td[3]"))
//softAssertion.assertEquals("imtiazster@gmail.com", selenium.getText("//tr[28]/td[3]"))

WebUI.verifyTextPresent(("20.00"), true)
WebUI.verifyTextPresent(("UDF2 Data2 Modified"), true)
WebUI.verifyTextPresent(("UDF3 Data2 Modified"), true)
WebUI.verifyTextPresent(("Orange"), true)
WebUI.verifyTextPresent(("Purple"), true)
WebUI.verifyTextPresent(("UDF6 Data2 Modified"), true)
WebUI.verifyTextPresent(("UDF7 Data2 Modified"), true)
WebUI.verifyTextPresent(("UDF8 Data2 Modified"), true)
WebUI.verifyTextPresent(("Jelly"), true)
WebUI.verifyTextPresent(("Jackson"), true)
WebUI.verifyTextPresent(("2707"), true)
WebUI.verifyTextPresent(("2222"), true)
WebUI.verifyTextPresent(("Personal Checking"), true)
WebUI.verifyTextPresent(("15 Main Street"), true)
WebUI.verifyTextPresent(("Building 2"), true)
WebUI.verifyTextPresent(("United States"), true)
WebUI.verifyTextPresent(("ARLINGTON"), true)
WebUI.verifyTextPresent(("Virginia"), true)
WebUI.verifyTextPresent(("22201"), true)
WebUI.verifyTextPresent(("imtiazster@gmail.com"), true)



WebUI.click(to("name=confirmNotifyAction"))
WebUI.waitForPageLoad(pageLoadTimeoutSeconds)
WebUI.delay(15)
//softAssertion.assertEquals("$20.00", selenium.getText("//tr[14]/td[2]"))
//softAssertion.assertEquals(Pattern.matches('selenium.getText("//tr[16]/td[2]")', "2222.*"), true)
//softAssertion.assertEquals(Pattern.matches('selenium.getText("//tr[16]/td[2]")', "2707.*"), true)
//softAssertion.assertEquals(Pattern.matches('selenium.getText("//tr[16]/td[2]")', "JELLY JACKSON.*"), true)
//softAssertion.assertEquals(Pattern.matches('selenium.getText("//tr[17]/td[2]")', "15 Main Street.*"), true)
//softAssertion.assertEquals(Pattern.matches('selenium.getText("//tr[17]/td[2]")', "Building 2.*"), true)
//softAssertion.assertEquals(Pattern.matches('selenium.getText("//tr[17]/td[2]")', "United States.*"), true)
//softAssertion.assertEquals(Pattern.matches('selenium.getText("//tr[17]/td[2]")', "ARLINGTON.*"), true)
//softAssertion.assertEquals(Pattern.matches('selenium.getText("//tr[17]/td[2]")', "Virginia.*"), true)
//softAssertion.assertEquals(Pattern.matches('selenium.getText("//tr[17]/td[2]")', "22201.*"), true)


WebUI.verifyTextPresent(("20.00"), true)
WebUI.verifyTextPresent(("2222"), true)
WebUI.verifyTextPresent(("2707"), true)
WebUI.verifyTextPresent(("JELLY JACKSON"), true)
WebUI.verifyTextPresent(("15 Main Street"), true)
WebUI.verifyTextPresent(("Building 2"), true)
WebUI.verifyTextPresent(("United States"), true)
WebUI.verifyTextPresent(("ARLINGTON"), true)
WebUI.verifyTextPresent(("Virginia"), true)
WebUI.verifyTextPresent(("22201"), true)

