<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pay by Credit</name>
   <tag></tag>
   <elementGuidId>fe1f525b-65b5-4dff-ac77-5aaca46bfc0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'radio' and @id = 'CC' and @name = 'paymentMethodSelect']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CC']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CC</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7c025330-7d53-4ff0-a553-009127f8f91a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>737ad1b4-b9d7-4d43-bb86-fb302525d4cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CC</value>
      <webElementGuid>87d3cdad-9d81-4bf6-a0f1-57047979db36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5affd080-fb15-4119-a8f3-d0e400a525f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>paymentMethodSelect</value>
      <webElementGuid>a0d54dbd-c084-4f8e-996a-7528d7100627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b2153f19-c858-4d43-98c3-7eb6efb75394</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CC&quot;)</value>
      <webElementGuid>9eb816b6-4421-488a-a8b8-1a9be5d9c4ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CC']</value>
      <webElementGuid>507aeaad-9804-43ff-8908-ee2b7e190549</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/form/input</value>
      <webElementGuid>ae914653-6520-4ce5-bea1-b74fb89d0fe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'CC' and @name = 'paymentMethodSelect']</value>
      <webElementGuid>ac0bfff9-9c66-459c-a626-33eedd1e9a28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
