<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_x_mb_btn_ok</name>
   <tag></tag>
   <elementGuidId>d2919ecd-7fb1-47fa-82de-3aa005305cbf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mb_btn_ok</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mb_btn_ok']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1d13c6af-c8e5-454b-b111-51ba939d9fa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mb_btn_ok</value>
      <webElementGuid>08f3e73f-feb4-42c9-9302-8e0b9a0deaee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c12bb44e-a2ac-42be-942e-57a04cbdd1aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>a7efe30c-71d2-409f-a0d1-475fdfd3409f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mb_btn_ok&quot;)</value>
      <webElementGuid>6aec95a3-0cf1-4e40-afbd-cae38b56fbc2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mb_btn_ok']</value>
      <webElementGuid>26c90ee0-a084-4d3b-bbf8-80fca104a902</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mb_btnbox']/input</value>
      <webElementGuid>c267f48b-9280-4e4d-9009-8a8441dff82b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/input</value>
      <webElementGuid>59af1c7a-5612-46ed-937c-4fc6179655b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'mb_btn_ok' and @type = 'button']</value>
      <webElementGuid>6c70a3aa-c2b0-4135-ad71-6439a76346c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
