<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_remittance_id_remittance_id</name>
   <tag></tag>
   <elementGuidId>db940ba9-59cb-46e5-a9a1-0ea3257fbf6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @name = 'remittance_id']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='remittance_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;remittance_id&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>af671ace-7b7c-43ba-8032-2ddcd7be900e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formTxtInput2</value>
      <webElementGuid>4def7b89-9ea4-42cc-8807-9958228d06c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>25d2e1b5-09d7-4dcf-9170-e67659221be4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>remittance_id</value>
      <webElementGuid>1944e021-00c4-4b04-97fe-942836c21685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/table[1]/tbody[1]/tr[2]/td[1]/table[1]/tbody[1]/tr[4]/td[1]/form[1]/table[1]/tbody[1]/tr[4]/td[2]/font[@class=&quot;size3&quot;]/input[@class=&quot;formTxtInput2&quot;]</value>
      <webElementGuid>9fb019ff-d69d-4825-a96f-8817cfbb8a5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='remittance_id']</value>
      <webElementGuid>3f0551c5-0fd6-4479-aaf3-f9c0c67707f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/font/input</value>
      <webElementGuid>8b8c0e8d-d432-428d-a1b3-a4d47362cb7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'remittance_id']</value>
      <webElementGuid>a9840538-b326-4e37-92e9-c0c3f63da6ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
