<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_message_version_message_version</name>
   <tag></tag>
   <elementGuidId>35c09d11-9509-462c-b68a-0118cc0ec523</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @name = 'message_version']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='message_version']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;message_version&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1bcc9618-36cf-4655-b579-ea9b2bb85111</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c64dd64b-f518-479d-9e0b-aa013d89f78a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>message_version</value>
      <webElementGuid>b9f024a4-9cff-43e0-bbbf-4d7121b3e763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2.2</value>
      <webElementGuid>1a2c6666-381b-4032-a852-cb48847909fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/table[1]/tbody[1]/tr[2]/td[1]/table[1]/tbody[1]/tr[4]/td[1]/form[1]/table[1]/tbody[1]/tr[3]/td[2]/font[@class=&quot;size3&quot;]/input[1]</value>
      <webElementGuid>352831ea-b06a-4e3b-9961-09eea7ce53f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='message_version']</value>
      <webElementGuid>c10afe24-f420-47d7-b993-1c1719494e01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/font/input</value>
      <webElementGuid>1cc500c8-1232-45a9-a229-992ebf4c643a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'message_version']</value>
      <webElementGuid>15d8527f-bbff-4374-ac84-3989f9514b7d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
