<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ConfirmCancelPlan</name>
   <tag></tag>
   <elementGuidId>292516ef-63d1-48c2-a4f5-1052eeed5d8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;cancelPaymentPlanHistoryBtn&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='cancelPaymentPlanHistoryBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>407cbbc0-ff85-41a7-926b-c569ce6a8d89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6a16dc4d-9419-4afe-aab2-eaa7db97fa64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cancelPaymentPlanHistoryBtn</value>
      <webElementGuid>6ff94a73-b81b-41d5-9fac-9cb5c7073c4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-block</value>
      <webElementGuid>f6a48ad2-3b8f-4564-a7b9-73428e48c644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Cancel Plan</value>
      <webElementGuid>9b1c86f1-2788-48dc-a590-d5e5912a249e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>cancelPaymentPlanHistory();</value>
      <webElementGuid>865d6f4c-c5c3-4db2-ba7e-0cbfe417a52b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;backButtonDiv&quot;)/div[@class=&quot;col-md-3  col-sm-3  col-xs-12 bootstrap-btn-group&quot;]/input[@class=&quot;btn btn-primary btn-block&quot;]</value>
      <webElementGuid>c471b768-ffed-4c3f-ab62-aab40b38494d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='cancelPaymentPlanHistoryBtn']</value>
      <webElementGuid>814c9262-a759-4086-8fa7-d74f1bfad865</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='backButtonDiv']/div[2]/input</value>
      <webElementGuid>c3df5edd-9c6a-4013-9be1-d7a4642954a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>c586277d-9943-4508-ae4d-f4d1ea6fcf11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'cancelPaymentPlanHistoryBtn']</value>
      <webElementGuid>1370160f-d5ff-4d86-9300-c9abec57e1be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
