<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_MV</name>
   <tag></tag>
   <elementGuidId>d152e4bc-277d-4b46-aa7f-ad0ca5dfb5eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='message_version']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;message_version&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'message_version']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>baf7f675-ff33-45d3-817a-dfe7534662c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>message_version</value>
      <webElementGuid>4da8abd7-3093-46df-8245-9bf64246508b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>changeMessageVersion(this.value)</value>
      <webElementGuid>057353ce-dd4d-413d-b38b-163a8391e0d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2.1
            2.2
            2.3
            2.5
            2.7
            3.0</value>
      <webElementGuid>8b6f1937-68d1-4a0d-b59a-975f7a9af5c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/table[1]/tbody[1]/tr[2]/td[1]/table[1]/tbody[1]/tr[2]/td[1]/table[1]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[4]/td[2]/select[1]</value>
      <webElementGuid>52eaea6e-0f50-44a5-a1f0-c9a83c96845f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='message_version']</value>
      <webElementGuid>b262b39e-957b-4d59-92d8-3ae76bd917ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Message Version'])[1]/following::select[1]</value>
      <webElementGuid>e94ca384-3ee6-4df6-b46e-3aa151d22f07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Input Editor'])[2]/following::select[1]</value>
      <webElementGuid>83a29637-f4bb-4a8a-bc91-117cec3a591b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amount'])[1]/preceding::select[1]</value>
      <webElementGuid>f8add4ff-f523-4f74-b5ee-b0a9bb62518f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Account Number'])[1]/preceding::select[1]</value>
      <webElementGuid>bad8c93d-348e-429b-bd0f-2990e0b4d191</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>94bc315c-5246-48fe-bff5-76f8f81fd647</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'message_version' and (text() = '2.1
            2.2
            2.3
            2.5
            2.7
            3.0' or . = '2.1
            2.2
            2.3
            2.5
            2.7
            3.0')]</value>
      <webElementGuid>91ae7137-05dc-44a6-88f1-50cd5e529b37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
