<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_UDFQuarter</name>
   <tag></tag>
   <elementGuidId>c8b33e63-636b-4b94-961f-a4f96186aa40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'variableField1DropdownGroupItemID']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='variableField1DropdownGroupItemID']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;variableField1DropdownGroupItemID&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8e911d46-afe2-4669-8464-1d6fbe37ff7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>variableField1DropdownGroupItemID</value>
      <webElementGuid>9e4f9613-dc58-4302-af79-0a2fe585a228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>611874e1-f3e1-40a9-8e21-634cf776434b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value> Quarter</value>
      <webElementGuid>84b8203e-acfb-45d1-9937-20dff4e2ab03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select One--RedYellowGreenOrangeBlack</value>
      <webElementGuid>c2a438e7-d064-4da4-b45d-34c3a5847ee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;udfcontent&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;form-group&quot;]/select[@class=&quot;form-control&quot;]</value>
      <webElementGuid>98cb8191-4258-44db-8506-2bdc3ca4b350</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='variableField1DropdownGroupItemID']</value>
      <webElementGuid>2f240e05-a1ae-48d5-931f-638a98005f1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='udfcontent']/div/div/div/select</value>
      <webElementGuid>c545b417-5c93-4678-8758-01a0a6413682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[9]/following::select[1]</value>
      <webElementGuid>367c3709-7131-4f24-b4c7-85369fc0ecd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Certificate of Authority #'])[1]/preceding::select[1]</value>
      <webElementGuid>c728ea5f-d162-4add-a727-f322d31eea6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gross Income'])[1]/preceding::select[1]</value>
      <webElementGuid>6120cd3a-a0ca-40f9-8cb5-e3ee522db850</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/select</value>
      <webElementGuid>f32ceb8a-331d-4819-96eb-873c5b09f770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'variableField1DropdownGroupItemID' and @alt = ' Quarter' and (text() = '--Select One--RedYellowGreenOrangeBlack' or . = '--Select One--RedYellowGreenOrangeBlack')]</value>
      <webElementGuid>792713c3-1d76-4d02-87d8-43eeafcc2d2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
