<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__guestBillSubmitBtn</name>
   <tag></tag>
   <elementGuidId>e2830b20-e56b-4dd8-b88c-d28db648ebba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='guestBillSubmitBtn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#guestBillSubmitBtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9aed6715-05ca-4fd7-a9b5-14354eb3b07d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>guestBillSubmitBtn</value>
      <webElementGuid>4d4a281e-e045-4c1b-bcad-f0080ab17f2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>guestBillSubmitBtn</value>
      <webElementGuid>872b29b4-c6f9-4a1a-8b2f-81a183a1af55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1c7fd797-7861-4d6f-b23a-5e18156c49b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>guestPaySubmit()</value>
      <webElementGuid>2b66da58-e0f8-4da7-b209-e2755f3b6221</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Pay as a Guest</value>
      <webElementGuid>24d64406-7021-4de0-b21b-24a32e86c4ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;guestBillSubmitBtn&quot;)</value>
      <webElementGuid>6523d474-12f8-4740-9c86-e3991d3d1f49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='guestBillSubmitBtn']</value>
      <webElementGuid>3e58d224-636b-44f7-8865-ecbfaf38103d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='guestBillSubmitBtnDiv']/input[4]</value>
      <webElementGuid>97982751-6473-4ab8-b200-a3ce41f00d7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input[4]</value>
      <webElementGuid>bc16870b-e970-4842-951a-f93f2ea12c48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'guestBillSubmitBtn' and @name = 'guestBillSubmitBtn' and @type = 'button']</value>
      <webElementGuid>3bba7105-793a-4d0a-ae46-be28162eb4f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
