<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__billLookupForm.lookupValue2</name>
   <tag></tag>
   <elementGuidId>76dc318b-8283-486e-a5c6-d896d77951f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lookupValue2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lookupValue2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>468300c5-e155-4d21-8fce-a29b1014b964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>65946e9a-4e04-4c95-9016-a8c4302a1dc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billLookupForm.lookupValue2</value>
      <webElementGuid>d927f41f-fd90-4325-aea0-6c427d21dae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>39022060-9771-46ed-8cc5-f721a7ecf00d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>1ed1bb11-bd28-49d4-90f0-99d1c2b23d42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lookupValue2</value>
      <webElementGuid>e22471f4-4e6e-4ce3-9370-ae050a54cc1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>485lookup2</value>
      <webElementGuid>e8a9a8d6-54c6-4ed2-80d1-13f2aa74a03c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lookupValue2&quot;)</value>
      <webElementGuid>af9c0a42-4dd5-42ed-9674-5880e08a7544</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lookupValue2']</value>
      <webElementGuid>3d27cd64-044a-45f9-b381-ee84e6cca461</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='lookupTr2']/td[2]/input</value>
      <webElementGuid>efcdc746-0dec-4ea8-bf0a-26899e1c771d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>84576270-db3e-485a-a92b-9f16f480ea1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'billLookupForm.lookupValue2' and @id = 'lookupValue2' and @alt = '485lookup2']</value>
      <webElementGuid>8e35ba17-d5ee-4b23-b65d-a1ffc2b9bba6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
