<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td</name>
   <tag></tag>
   <elementGuidId>bd35cf8b-90a4-4187-8c10-6a9d0b9968b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='lookupTr3']/td[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lookupTr3 > td:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>3f2c1896-9e8f-432e-84c6-4a7dfac99772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>0b0a0d32-3a57-432f-a591-43fc4b985383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lookupTr3&quot;)/td[2]</value>
      <webElementGuid>6e268d2c-da40-4089-9f8a-245a3d261b62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='lookupTr3']/td[2]</value>
      <webElementGuid>c30d16d4-e6aa-4be7-afd0-5cddfacc8f1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::td[1]</value>
      <webElementGuid>c8cfc7fa-0af0-4dd6-897b-eb5103ba6f80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::td[3]</value>
      <webElementGuid>1ad0265d-75b3-4840-8dca-f556ccc0e9db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Registration Benefits:'])[1]/preceding::td[3]</value>
      <webElementGuid>c417bb59-7c00-45ae-b0dc-f39b19fd9ff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-Store payment methods for future use'])[1]/preceding::td[3]</value>
      <webElementGuid>7b896564-b844-4c3e-ae67-171b47ea7b01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/table/tbody/tr[3]/td[2]</value>
      <webElementGuid>8290bbfe-634e-49e7-a3c0-e435f3982edf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
