<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Tax Information_tx_iframe_taxTypeExisitingSSNIFrame</name>
   <tag></tag>
   <elementGuidId>66dd37dc-ed79-46d8-bb73-dc5422bf49e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tx_iframe_taxTypeExisitingSSNIFrame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='tx_iframe_taxTypeExisitingSSNIFrame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>3de43b62-b71e-4699-816c-f46e0cd6e7c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://test-htp.tokenex.com/iframe/v3?AuthenticationKey=yAvqp0PyKFr6vaC40lSYvMLKfoJG9aYWM0u%2F5Cx5PdQ%3D&amp;Origin=https%3A%2F%2Fqa2.velocitypayment.com&amp;TokenExID=3817434419954472&amp;Timestamp=20230904160552&amp;Container=taxTypeExisitingSSNIFrame&amp;Mode=Data&amp;PCI=false&amp;TokenScheme=nTOKENfour1to1&amp;ExpiresInSeconds=1200</value>
      <webElementGuid>6557b556-4c10-4f00-a6d7-2b60af37d770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>16b1110e-2a75-4b0e-8f98-c14c848e70a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>9bcdbad9-2e9e-48e1-b3aa-bb02173f5b66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>b3f01240-5c72-46cc-adc2-16be21540d8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tx_iframe_taxTypeExisitingSSNIFrame</value>
      <webElementGuid>d6e62114-6449-407d-905e-876e4298522a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tx_iframe_taxTypeExisitingSSNIFrame</value>
      <webElementGuid>5979f535-cda2-4b68-a83a-640341fe33f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tx_iframe_taxTypeExisitingSSNIFrame&quot;)</value>
      <webElementGuid>f43d2a56-c9cb-4f78-b861-3e14f73baa0f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='tx_iframe_taxTypeExisitingSSNIFrame']</value>
      <webElementGuid>75827f5c-f1cb-4811-b433-172baa3b6787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='taxTypeExisitingSSNIFrame']/iframe</value>
      <webElementGuid>d0a7a8be-9302-44f4-bc01-5a0dafa165ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[3]/fieldset/div/iframe</value>
      <webElementGuid>782d895f-3921-4ffe-846d-f1fbd3774d0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://test-htp.tokenex.com/iframe/v3?AuthenticationKey=yAvqp0PyKFr6vaC40lSYvMLKfoJG9aYWM0u%2F5Cx5PdQ%3D&amp;Origin=https%3A%2F%2Fqa2.velocitypayment.com&amp;TokenExID=3817434419954472&amp;Timestamp=20230904160552&amp;Container=taxTypeExisitingSSNIFrame&amp;Mode=Data&amp;PCI=false&amp;TokenScheme=nTOKENfour1to1&amp;ExpiresInSeconds=1200' and @id = 'tx_iframe_taxTypeExisitingSSNIFrame' and @name = 'tx_iframe_taxTypeExisitingSSNIFrame']</value>
      <webElementGuid>7a2104e0-ef39-473f-a90d-b0890a497b88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
