<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Please enter a valid FEINSSN with 9 digits_tx_iframe_reEnterTaxTypeExistingPTEIFrame (1)</name>
   <tag></tag>
   <elementGuidId>ccdf5ddb-3f9f-43f3-acf2-07e95f866ef6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tx_iframe_reEnterTaxTypeExistingPTEIFrame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='tx_iframe_reEnterTaxTypeExistingPTEIFrame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>e35abd67-5153-423f-8e38-cbfbd9be5044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://test-htp.tokenex.com/iframe/v3?AuthenticationKey=FPdLU8JXv%2F17tFlTXqxiy758QH8efmvUihTGj8T3nIM%3D&amp;Origin=https%3A%2F%2Fqa2.velocitypayment.com&amp;TokenExID=3817434419954472&amp;Timestamp=20231031191524&amp;Container=reEnterTaxTypeExistingPTEIFrame&amp;Mode=Data&amp;PCI=false&amp;TokenScheme=nTOKENfour1to1&amp;ExpiresInSeconds=1200</value>
      <webElementGuid>790bdfbb-0f26-454a-87a6-97eaf523d5c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cf9b3b28-271a-43b8-ad05-39e919a69f73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>da3b9003-15e3-4afa-a13f-7228b20ca0aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>89331220-945d-4782-a0f1-9c5533a04eb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tx_iframe_reEnterTaxTypeExistingPTEIFrame</value>
      <webElementGuid>efdafb33-c559-49b8-b1b2-e6041f84f549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tx_iframe_reEnterTaxTypeExistingPTEIFrame</value>
      <webElementGuid>06ea3fb5-5666-49e0-91e4-e571895e7aa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tx_iframe_reEnterTaxTypeExistingPTEIFrame&quot;)</value>
      <webElementGuid>92e55312-6a45-4bec-af41-0d5c4a66d9be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='tx_iframe_reEnterTaxTypeExistingPTEIFrame']</value>
      <webElementGuid>d23f413d-d893-4dfd-a052-67206dfc1680</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='reEnterTaxTypeExistingPTEIFrame']/iframe</value>
      <webElementGuid>46407d1b-5006-4a46-bce9-5ae3b3a5fc21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/fieldset/div/iframe</value>
      <webElementGuid>b77c2120-3a68-43d3-b416-be99184cb15d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://test-htp.tokenex.com/iframe/v3?AuthenticationKey=FPdLU8JXv%2F17tFlTXqxiy758QH8efmvUihTGj8T3nIM%3D&amp;Origin=https%3A%2F%2Fqa2.velocitypayment.com&amp;TokenExID=3817434419954472&amp;Timestamp=20231031191524&amp;Container=reEnterTaxTypeExistingPTEIFrame&amp;Mode=Data&amp;PCI=false&amp;TokenScheme=nTOKENfour1to1&amp;ExpiresInSeconds=1200' and @id = 'tx_iframe_reEnterTaxTypeExistingPTEIFrame' and @name = 'tx_iframe_reEnterTaxTypeExistingPTEIFrame']</value>
      <webElementGuid>6a0c0c0f-014d-4f30-a76e-8ba482616dec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
