<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Tax Information_tx_iframe_taxTypePTEIFrame</name>
   <tag></tag>
   <elementGuidId>fe8806c5-4b47-4d0c-9789-e4bfbf2a3e1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tx_iframe_taxTypePTEIFrame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='tx_iframe_taxTypePTEIFrame']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'tx_iframe_taxTypePTEIFrame' and @name = 'tx_iframe_taxTypePTEIFrame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>22396f20-f7c7-495e-a29b-d40316191d42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://test-htp.tokenex.com/iframe/v3?AuthenticationKey=F+JvwA3GrzRSG+IXR%2FJs5+rMqjPeRs%2F42i2qwRoDkjY%3D&amp;Origin=https%3A%2F%2Fqa2.velocitypayment.com&amp;TokenExID=3817434419954472&amp;Timestamp=20231031013652&amp;Container=taxTypePTEIFrame&amp;Mode=Data&amp;PCI=false&amp;TokenScheme=nTOKENfour1to1&amp;ExpiresInSeconds=1200</value>
      <webElementGuid>2e4c949c-da79-4222-afac-cb547024467d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9dcebbc4-5a82-4149-a685-1dff772ca882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>69a237bb-0d29-4233-b743-2cedd46c9525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>b44ef7a7-dda8-46bb-9e24-8c991690fffd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tx_iframe_taxTypePTEIFrame</value>
      <webElementGuid>9650ef57-e784-4b56-8058-84dccdb9f296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tx_iframe_taxTypePTEIFrame</value>
      <webElementGuid>754f84de-0f64-4e74-8512-0f9b97f3f7b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tx_iframe_taxTypePTEIFrame&quot;)</value>
      <webElementGuid>4e96cc67-cedb-4d2d-b6e5-75aabc66ca15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='tx_iframe_taxTypePTEIFrame']</value>
      <webElementGuid>c0611ee2-e63f-44ee-b65f-cfce99c17c3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='taxTypePTEIFrame']/iframe</value>
      <webElementGuid>9eb37fc9-7bbe-42e1-9508-a7b482536f2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/fieldset/div/iframe</value>
      <webElementGuid>b27ad95e-2e69-4951-92b8-6771cfb9608b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://test-htp.tokenex.com/iframe/v3?AuthenticationKey=F+JvwA3GrzRSG+IXR%2FJs5+rMqjPeRs%2F42i2qwRoDkjY%3D&amp;Origin=https%3A%2F%2Fqa2.velocitypayment.com&amp;TokenExID=3817434419954472&amp;Timestamp=20231031013652&amp;Container=taxTypePTEIFrame&amp;Mode=Data&amp;PCI=false&amp;TokenScheme=nTOKENfour1to1&amp;ExpiresInSeconds=1200' and @id = 'tx_iframe_taxTypePTEIFrame' and @name = 'tx_iframe_taxTypePTEIFrame']</value>
      <webElementGuid>635a9612-367a-4c5b-b2eb-7142c28cd38f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
