<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Tax Information_tx_iframe_taxTypeExi_006482</name>
   <tag></tag>
   <elementGuidId>0789bb62-f280-4d5a-9b4d-37ea434335f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tx_iframe_taxTypeExisitingSSNIFrame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='tx_iframe_taxTypeExisitingSSNIFrame']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'tx_iframe_taxTypeExisitingSSNIFrame' and @name = 'tx_iframe_taxTypeExisitingSSNIFrame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://test-htp.tokenex.com/iframe/v3?AuthenticationKey=w9RX64HAzEf3chAOKTvrWrNbcQ3TUcIzNyaiDhW8jAM%3D&amp;Origin=https%3A%2F%2Fqa.velocitypayment.com&amp;TokenExID=3817434419954472&amp;Timestamp=20211026182143&amp;Container=taxTypeExisitingSSNIFrame&amp;Mode=Data&amp;PCI=false&amp;TokenScheme=ASCIITOKENFOUR&amp;ExpiresInSeconds=1200</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tx_iframe_taxTypeExisitingSSNIFrame</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tx_iframe_taxTypeExisitingSSNIFrame</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tx_iframe_taxTypeExisitingSSNIFrame&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='tx_iframe_taxTypeExisitingSSNIFrame']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='taxTypeExisitingSSNIFrame']/iframe</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[3]/fieldset/div/iframe</value>
   </webElementXpaths>
</WebElementEntity>
