<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TaxInfo_RetypeFeinSSN_New</name>
   <tag></tag>
   <elementGuidId>bc709818-7baf-424d-8f1e-11fb214f6ece</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#data</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='data']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'data' and @ref_element = 'Object Repository/RAD_Pages/TaxInfo_Page/iframe_Please enter a valid FEINSSN with 9 digits_tx_iframe_reEnterTaxTypeExistingPTEIFrame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>34c7242d-1ca0-46aa-9d04-e4515c4518f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>898bdc16-6965-4136-9920-a8a8d921dccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>data</value>
      <webElementGuid>79fc4f0f-fe77-4b1d-8084-d16884b0a660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Data</value>
      <webElementGuid>76d42a71-48d6-46b4-89b7-60e238d3abdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>4151f952-4d08-4388-a6b4-0f470d7312b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Re-Type FEIN/SSN *</value>
      <webElementGuid>1a70be0f-99a3-4e28-a9ff-1cab3a55498d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>error</value>
      <webElementGuid>fa22c2e5-b016-485c-9ae9-6151c1270502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;data&quot;)</value>
      <webElementGuid>4c8e41a6-cc3f-4d4d-9409-334ec1ca145d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/RAD_Pages/TaxInfo_Page/iframe_Please enter a valid FEINSSN with 9 digits_tx_iframe_reEnterTaxTypeExistingPTEIFrame</value>
      <webElementGuid>20fea8f3-d395-40e9-8baa-beb16edea2c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='data']</value>
      <webElementGuid>fde7ebe1-ecdb-4752-8823-acd1eff2b07d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[29]</value>
      <webElementGuid>05f1ec68-dc00-40d8-ad92-54ab74dccd9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'data' and @name = 'Data' and @type = 'password' and @placeholder = 'Re-Type FEIN/SSN *']</value>
      <webElementGuid>12521c42-1795-4f78-aa70-a75017b0c026</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
