<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(id(, , data, , ))_Data (1)</name>
   <tag></tag>
   <elementGuidId>28eb45fe-3085-4628-b2dd-813d00c529ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='data']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#data</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;data&quot;)[count(. | //*[@id = 'data' and @name = 'Data' and @type = 'password' and @placeholder = 'Re-Type FEIN Number *' and @ref_element = 'Object Repository/RAD_Pages/TaxInfo_Page/iframe_Enter valid FEIN with 9 digits_tx_if_a5ef47']) = count(//*[@id = 'data' and @name = 'Data' and @type = 'password' and @placeholder = 'Re-Type FEIN Number *' and @ref_element = 'Object Repository/RAD_Pages/TaxInfo_Page/iframe_Enter valid FEIN with 9 digits_tx_if_a5ef47'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>data</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Data</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Re-Type FEIN Number *</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;data&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/RAD_Pages/TaxInfo_Page/iframe_Enter valid FEIN with 9 digits_tx_if_a5ef47</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='data']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[20]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'data' and @name = 'Data' and @type = 'password' and @placeholder = 'Re-Type FEIN Number *']</value>
   </webElementXpaths>
</WebElementEntity>
