<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TaxInfo_RetypeFeinSsn_New_2</name>
   <tag></tag>
   <elementGuidId>3e86821e-975c-4e5b-b50f-c6421030b3f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#data</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='data']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>53ee12f0-9d6a-48a9-a3be-c7370a121218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7cc1d3fd-91a6-44b0-8f76-da50cce50145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>data</value>
      <webElementGuid>46d96930-b9a5-4f87-9c4e-3fde6afeeee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Data</value>
      <webElementGuid>dd94aa05-5e21-4556-bb8d-fe6b2ec86281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>dde2d2a3-8550-4a19-9733-f6b1d2791a36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Re-Type FEIN/SSN *</value>
      <webElementGuid>3662cc6d-d649-4ea4-a8f5-3f28240cff06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;data&quot;)</value>
      <webElementGuid>de057ce3-2413-4117-ac1f-14ffe3998a02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/RAD_Pages/TaxInfo_Page/iframe_Enter FEINSSN_tx_iframe_reEnterTaxTypePTEIFrame</value>
      <webElementGuid>a32fb56f-d69c-4b31-aca7-777135582f46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='data']</value>
      <webElementGuid>2d545f33-c083-4ecd-abfd-987250e9be6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[29]</value>
      <webElementGuid>bd4bcb66-a776-489a-b884-30f3b24cc3aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'data' and @name = 'Data' and @type = 'password' and @placeholder = 'Re-Type FEIN/SSN *']</value>
      <webElementGuid>f407cb6f-4b7e-4a73-82db-51a65cb93948</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
