<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TaxInfo_RefeinSsn_Existing</name>
   <tag></tag>
   <elementGuidId>c40fb77f-83c2-43cb-98fb-acffede1e9d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.row.taxInfoExisitingLiabilityCont > div.col-lg-6.refeinorSsn > div.form-floating.mb-3 > #refeinSsn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='refeinSsn'])[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'password' and @name = 'refeinSsn' and @id = 'refeinSsn' and @placeholder = 'Re-Type FEIN/SSN']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b8ad7840-9eba-4b49-9e31-bbd425678286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>7d9dabc3-ac06-4cc9-bc84-e75115cc3177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>refeinSsn</value>
      <webElementGuid>288c753f-5310-43bd-97ce-f75cdddeeab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mask</name>
      <type>Main</type>
      <value>999999999</value>
      <webElementGuid>40062216-a0d5-4fa5-af5f-ba1a46da26a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>86a7e277-2dde-4dcf-97ce-12de8799bd4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>refeinSsn</value>
      <webElementGuid>78b30474-c271-4703-95ed-7ae961e8c271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>3273cf1c-f115-4f7f-a347-75fa5a1b61b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Re-Type FEIN/SSN</value>
      <webElementGuid>b925a943-7f56-4f1e-8ebb-3c72eb0a7f80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b2c364dd-e5f5-4714-8345-2905be221e66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;taxForm&quot;)/div[@class=&quot;row taxInfoExisitingLiabilityCont&quot;]/div[@class=&quot;col-lg-6 refeinorSsn&quot;]/div[@class=&quot;form-floating mb-3&quot;]/input[@id=&quot;refeinSsn&quot;]</value>
      <webElementGuid>a2600152-d044-46e4-9325-1bb2915b76c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='refeinSsn'])[2]</value>
      <webElementGuid>b240fb8d-a19b-4710-af0f-9def423df061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='taxForm']/div[9]/div[10]/div/input</value>
      <webElementGuid>aae01eb7-48e2-4b53-9267-9ca3d3932ced</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[10]/div/input</value>
      <webElementGuid>b7d76440-f9c5-4969-a1b0-9da3a9dd1393</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'refeinSsn' and @id = 'refeinSsn' and @placeholder = 'Re-Type FEIN/SSN']</value>
      <webElementGuid>3b5eb464-097c-461e-8c28-54fb980fca3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
