<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_reTypeNoticeNumber_Only</name>
   <tag></tag>
   <elementGuidId>3a49c788-e4c1-4689-930b-7a26f44f077e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#reTypeNoticeNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='reTypeNoticeNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>96a8af72-b459-452a-8ac7-c2d51e3bcf75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4211374a-35a7-451a-8935-9089880f0f92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reTypeNoticeNumber</value>
      <webElementGuid>e031d34f-aa1e-46d9-aca8-a1be1b856bfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mask</name>
      <type>Main</type>
      <value>9999999999999</value>
      <webElementGuid>be331538-76b7-496f-9adb-5872b57a992e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>cb5c7d95-ec81-4334-af78-8ce9ed9f8f5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reTypeNoticeNumber</value>
      <webElementGuid>ebfce013-7506-4a62-ba85-997393547ede</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>ac207f5d-018a-423b-9600-287a4e68b6f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Re-Type Notice or Invoice Number</value>
      <webElementGuid>9a523669-e6bd-4c88-8301-f54c40290b96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ec4dc44c-7991-49a0-9df2-fcac9db50b65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reTypeNoticeNumber&quot;)</value>
      <webElementGuid>39c1952e-e541-4aed-a91e-fd597b8a3a6d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='reTypeNoticeNumber']</value>
      <webElementGuid>78630f5b-1162-4050-b958-fa211b96e44f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='taxForm']/div[7]/div[8]/div/input</value>
      <webElementGuid>f97ed9dc-4466-405f-a718-0aae55f051f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[8]/div/input</value>
      <webElementGuid>b1d76a07-81d0-4aa4-b6d9-e3508efbab44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'reTypeNoticeNumber' and @id = 'reTypeNoticeNumber' and @placeholder = 'Re-Type Notice or Invoice Number']</value>
      <webElementGuid>950522c3-3721-41e3-b37e-7c02fbf92b3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
