<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_billingZip</name>
   <tag></tag>
   <elementGuidId>090c0fd9-e76e-4f62-9329-0deaef1cfa18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#billing-zip-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='billing-zip-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2ee9500b-aa43-4262-a49f-5a914454c4ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billing-zip-input</value>
      <webElementGuid>d7505a81-14cb-4643-be48-fd6cb166de6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>changeListener4ZipCode(this)</value>
      <webElementGuid>455121c8-ce47-4d2c-a15a-8aba4d44b3b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>5be8bbaa-8f9d-4972-be32-73d1590d1656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a46214c3-f680-481a-a3c0-8eb84fcdb8ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billingZip</value>
      <webElementGuid>6390507c-5be2-4552-8ce6-445eef730a43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>ZIP Code</value>
      <webElementGuid>bc67cb54-89e6-43d3-bac2-cc9f760d0f78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>94e62e25-483c-4b9d-91b2-2fb0e069aafc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>0ec8d7fe-939a-4902-8a7e-746d3d47e132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>92564</value>
      <webElementGuid>d4b6e1ef-6691-4879-9198-595a68c87305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a40fa5cf-7d36-46a8-9a4e-5390b42c0a41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billing-zip-input&quot;)</value>
      <webElementGuid>48d6f954-74b9-4051-84a6-0b924a8b06e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='billing-zip-input']</value>
      <webElementGuid>e543d29a-e29a-4e13-9927-9c28e5e7063c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/div/input</value>
      <webElementGuid>295d10b5-fb83-4a3a-b752-10306aae9e75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'billing-zip-input' and @type = 'text' and @name = 'billingZip' and @alt = 'ZIP Code']</value>
      <webElementGuid>e68d22c8-98c6-488a-9271-6c89a5824fb9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
