<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_aindurkar</name>
   <tag></tag>
   <elementGuidId>03f7e2fd-7ca5-48c0-a057-38581288a033</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='loadUser']/tr[4]/td[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;[aindurkar]&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6d26b873-3c27-4fec-8e36-01e374b4fb90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/admin/testcustomer/bootstrap/vadministrator/users/view.do?uid=55271</value>
      <webElementGuid>8afb6484-3c89-477f-9667-a6eca452da01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>[aindurkar]</value>
      <webElementGuid>8be73112-1c1b-4628-af83-f964a6820653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loadUser&quot;)/tr[@class=&quot;even table_bg&quot;]/td[2]/a[1]</value>
      <webElementGuid>93c3e98a-0475-493c-a272-8f3da6bbc55e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='loadUser']/tr[4]/td[2]/a</value>
      <webElementGuid>00a61961-b1e9-4eea-93b9-84c85153a3a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'[aindurkar]')]</value>
      <webElementGuid>a042f189-7b6b-49fd-84e8-0bbeb07b79c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ashwity Indurkar'])[1]/following::a[1]</value>
      <webElementGuid>009713c7-6324-4330-8380-504e49459493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[Aashu]'])[1]/following::a[1]</value>
      <webElementGuid>623dd238-9291-41e7-b934-9197ebc296e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aurora W'])[1]/preceding::a[1]</value>
      <webElementGuid>e42ee4b0-4997-4fe0-b2be-855992356147</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[Runaway]'])[1]/preceding::a[1]</value>
      <webElementGuid>6b51a99d-d38e-41ce-800d-9e4330f3cf4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='[aindurkar]']/parent::*</value>
      <webElementGuid>f7d32b8e-8bf6-46b1-866f-dc2a379ed150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/admin/testcustomer/bootstrap/vadministrator/users/view.do?uid=55271')]</value>
      <webElementGuid>6202c2ec-f1f7-4586-872a-4b48bd34787c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/a</value>
      <webElementGuid>adb5aef5-0147-4dfd-8f14-90111e6d7fcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/admin/testcustomer/bootstrap/vadministrator/users/view.do?uid=55271' and (text() = '[aindurkar]' or . = '[aindurkar]')]</value>
      <webElementGuid>8150ccf3-3a7c-4f50-8a2a-d9add442e97f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
