<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Export_New</name>
   <tag></tag>
   <elementGuidId>20538928-bb7e-4694-8a02-6fb913f9d1d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.dd-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Users'])[2]/following::div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f9ff5c2e-979d-4d1a-b8a3-ada255832521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dd-button</value>
      <webElementGuid>848c9f01-e322-4782-97ff-2422718a182a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
								    Export
								  </value>
      <webElementGuid>4287c134-d620-4bf2-93fd-436e4af541f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;app sidebar-mini&quot;]/main[@class=&quot;app-content&quot;]/div[@class=&quot;app-title shadow&quot;]/ul[@class=&quot;app-breadcrumb breadcrumb&quot;]/li[2]/div[@class=&quot;mr-3 ml-3&quot;]/label[@class=&quot;dropdown&quot;]/div[@class=&quot;dd-button&quot;]</value>
      <webElementGuid>32eb49b2-26f6-4292-8880-6affec0e6145</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Users'])[2]/following::div[2]</value>
      <webElementGuid>4cef804b-c0c6-47bb-b6a2-e56b8a654739</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Report'])[1]/preceding::div[1]</value>
      <webElementGuid>59da8189-39db-4a78-aae5-747c72980ed7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Find User'])[1]/preceding::div[1]</value>
      <webElementGuid>eb322c71-dec6-43d5-a458-55d079ed2d6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Export']/parent::*</value>
      <webElementGuid>d0ab8d41-afb6-4af0-bf5f-b4b7d264f5c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div</value>
      <webElementGuid>4995fdff-4079-4d9a-a442-3b7cb7189cbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
								    Export
								  ' or . = '
								    Export
								  ')]</value>
      <webElementGuid>4047573c-37a0-46f1-98fc-0fa9825221cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
