<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PayByPersonalCheck</name>
   <tag></tag>
   <elementGuidId>d0d56dc0-7769-4676-896b-39a793b58f12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'paymentMethodSelect' and @type = 'radio' and @id = 'PC']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>paymentMethodSelect</value>
      <webElementGuid>c02437f6-cb67-4b7b-8bcf-6904b067ff38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>8d94afeb-e0c4-4127-93eb-386a03f229b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PC</value>
      <webElementGuid>084ec673-3941-4e12-9b1c-d10be288ca55</webElementGuid>
   </webElementProperties>
</WebElementEntity>
