<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ReceiptEmailAddress</name>
   <tag></tag>
   <elementGuidId>8e5d5c8b-84cc-486a-b9c6-41d29e035637</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input_emailaddress']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input_emailaddress</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#input_emailaddress</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>30d55d73-afef-49c2-9184-f810624bdd38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a1c2761a-3d9f-4769-bc5b-97ab545c6763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>paymentMethodForm.emailaddress</value>
      <webElementGuid>634be4be-115a-488d-a258-a7952a9b9574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>bdd000ba-eaf7-4b22-840a-f05d8b0e3022</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>e83357b6-6917-41d6-8330-9e8f2e51d77a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input_emailaddress</value>
      <webElementGuid>7b441caa-fc5c-41d4-bad9-f91731fd0bc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input_emailaddress&quot;)</value>
      <webElementGuid>cc21c69f-968b-48d0-8aa0-b02b7910268d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input_emailaddress']</value>
      <webElementGuid>e369ccf1-8126-44be-b748-74ca930be26a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='paymentMethodTypeFormDiv']/div[4]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>f1603b32-a324-47f5-9df2-261ad87dfc5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div[4]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>1b69dab5-4623-4339-9a6c-9bda418aa1eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'paymentMethodForm.emailaddress' and @id = 'input_emailaddress']</value>
      <webElementGuid>737d8693-41e4-49de-9bfe-827bbcf8577b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
