<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CardholderName</name>
   <tag></tag>
   <elementGuidId>8ef4a0f4-32e1-445a-93c1-cb2d342f7103</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @name = 'billingName' and @id = 'billingName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b39fd310-cfae-4f9f-85fc-c84a36d54a98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billingName</value>
      <webElementGuid>b2bd9435-7f01-4154-9d73-03169633fe43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billingName</value>
      <webElementGuid>1030503d-7f54-42d8-8f43-fb9b6b3d4e48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>e6f721c9-a659-4f2b-a9ac-53c2e836511e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
