<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CardSecurityCode</name>
   <tag></tag>
   <elementGuidId>4086356c-ce22-4f9c-aa7a-93fe5301c23a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'cardSecurityCode' and @class = 'form-control']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='password_cardSecurityCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#password_cardSecurityCode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#password_cardSecurityCode</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b79b8d7d-556e-477a-bd70-83de1a2ca343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3c2dad9a-225a-41a5-a8b3-28846e6cefea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>54627f82-575e-4d5d-87f0-6cdaf7d9165e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cardSecurityCode</value>
      <webElementGuid>713805db-9e05-46ca-b73a-255f3cd3824b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cardSecurityCode</value>
      <webElementGuid>41b2c7ea-759b-4f55-b007-f78d41a66554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4e8a7717-cfb6-4100-ae7b-4f35b92a5563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>c748a5a8-e3af-4906-91bf-3bc34fd050c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;password_cardSecurityCode&quot;)</value>
      <webElementGuid>4e7f323a-6b95-4ffc-9fae-b0f7f3390012</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='password_cardSecurityCode']</value>
      <webElementGuid>73d120d9-c041-4ca8-b9ee-282ebd842c2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='credit-card-fields']/div/div[4]/input[2]</value>
      <webElementGuid>1b13f7c9-adfd-4d66-921d-e6484783d6a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[4]/input[2]</value>
      <webElementGuid>ffcc66ba-cc34-4393-90cf-d9f4e4f37dfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'password_cardSecurityCode' and @name = 'password_cardSecurityCode']</value>
      <webElementGuid>1a9aabad-5d7a-4ccd-9b07-6668848d1d1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
