<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_The SSN and Re-typeSSN do not match_tx_iframe_tokenXDSSNIFrame</name>
   <tag></tag>
   <elementGuidId>49327f66-379d-4ae4-9655-d0bde9157f1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='tx_iframe_tokenXDSSNIFrame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tx_iframe_tokenXDSSNIFrame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>0e970e3a-643b-4bb1-9628-77dd9d085be9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://test-htp.tokenex.com/iframe/v3?AuthenticationKey=mlOvs07Ep5NqiwSMTfKSUHfC9kksBbYo3+CfGcDGnYg%3D&amp;Origin=https%3A%2F%2Fqa2.velocitypayment.com&amp;TokenExID=3817434419954472&amp;Timestamp=20240131002137&amp;Container=tokenXDSSNIFrame&amp;Mode=Data&amp;PCI=false&amp;TokenScheme=nTOKENfour1to1&amp;ExpiresInSeconds=1200</value>
      <webElementGuid>abbfd68d-2ddd-44fd-8e21-0707116f162f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e1f33829-2f75-4ddb-9ca0-486b4161d342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>2e466def-d7e8-466f-bd6f-8c8f4da451da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>5e1ee324-5c85-43c2-a649-9679be219b24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tx_iframe_tokenXDSSNIFrame</value>
      <webElementGuid>18bce316-1993-477f-b1b6-982c30c7fa84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tx_iframe_tokenXDSSNIFrame</value>
      <webElementGuid>5f4b4fb6-bd11-43e9-aad0-bc6fdd1a9e28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tx_iframe_tokenXDSSNIFrame&quot;)</value>
      <webElementGuid>880ebb0a-acb2-4af0-a22e-0c8416a5d2fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='tx_iframe_tokenXDSSNIFrame']</value>
      <webElementGuid>e6e45d84-dacd-4585-aeee-ec43d73e0bc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tokenXDSSNIFrame']/iframe</value>
      <webElementGuid>3f402367-b99c-4fe7-86ed-f384dd4400cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/fieldset/div/iframe</value>
      <webElementGuid>5b65ac1c-a21b-452b-9935-67d04e644ff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://test-htp.tokenex.com/iframe/v3?AuthenticationKey=mlOvs07Ep5NqiwSMTfKSUHfC9kksBbYo3+CfGcDGnYg%3D&amp;Origin=https%3A%2F%2Fqa2.velocitypayment.com&amp;TokenExID=3817434419954472&amp;Timestamp=20240131002137&amp;Container=tokenXDSSNIFrame&amp;Mode=Data&amp;PCI=false&amp;TokenScheme=nTOKENfour1to1&amp;ExpiresInSeconds=1200' and @id = 'tx_iframe_tokenXDSSNIFrame' and @name = 'tx_iframe_tokenXDSSNIFrame']</value>
      <webElementGuid>c6a69562-9968-4c24-899d-95cfe2e0054c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
