<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_BusinessRepfirstName</name>
   <tag></tag>
   <elementGuidId>282ffdfa-bc31-4ed8-b04c-9eeb8c0bf1b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#RepfirstName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='RepfirstName']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'RepfirstName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1460d327-5839-4398-999c-8b0c793f540a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1cb35699-3113-43f6-b482-84d8e9846cea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>firstName</value>
      <webElementGuid>ffb0bbe5-8182-4a68-8eb6-48fc47eef0e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2b46c814-7a22-47e8-ba8b-3ada8fdc9092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>repfirstName</value>
      <webElementGuid>66ecbf7f-244a-4f95-b87c-6dfae419edfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>19c36e9f-802c-49dd-a8b1-b61b455546f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value> Business Rep First Name</value>
      <webElementGuid>fae0903f-fd03-450d-8659-f7ff619e9504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RepfirstName&quot;)</value>
      <webElementGuid>79019c04-6c96-41b8-82af-30ec49a3ec88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='RepfirstName']</value>
      <webElementGuid>836ad3ad-fd7d-4bcf-a33a-b609cc8d317f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='taxForm']/div[3]/div[4]/div/input</value>
      <webElementGuid>e3bb3a17-e1a8-4e07-a1b3-7b3d01885874</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>a8d9dcbc-7b86-4363-8221-e9c80721d45c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'RepfirstName' and @id = 'RepfirstName' and @placeholder = ' Business Rep First Name']</value>
      <webElementGuid>0ada965b-1cf7-42f7-84e8-43c8bf085142</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
