<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_BusinessRepfirstName</name>
   <tag></tag>
   <elementGuidId>282ffdfa-bc31-4ed8-b04c-9eeb8c0bf1b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#RepfirstName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='RepfirstName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e4b0e2de-36a8-41c1-b0ac-8c67427b3f24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9c0bc80a-881f-427a-9268-da9c786f83ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>RepfirstName</value>
      <webElementGuid>758062bf-bb78-47ec-8491-d77598cffd40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>95bbc626-7672-4689-95ef-efaaf1545f34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RepfirstName</value>
      <webElementGuid>020bb7c7-94f9-4272-9c22-e1a069b5054f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>e061894e-b373-4cb2-b931-98e1da99c969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value> Business Rep First Name</value>
      <webElementGuid>efa2e81b-30ca-49cb-b1ff-1acae833c631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RepfirstName&quot;)</value>
      <webElementGuid>3ec968fd-b7ef-4dca-9975-ccc5ef91a674</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='RepfirstName']</value>
      <webElementGuid>afde975c-7409-4157-bb24-ac829ee23766</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='taxForm']/div[3]/div[4]/div/input</value>
      <webElementGuid>bd38d29d-3b22-4184-9097-0234f5a2189e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>ae729bcd-c797-4928-8eaa-c9be96c9827b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'RepfirstName' and @id = 'RepfirstName' and @placeholder = ' Business Rep First Name']</value>
      <webElementGuid>e936c3fd-d4b9-41e8-a0eb-9bb9b518aae8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
