<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_BusinessReplastName</name>
   <tag></tag>
   <elementGuidId>415ab09a-e165-4914-bcf5-1774ea2143af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ReplastName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ReplastName']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'replastName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ee864ce8-83dd-48ae-98f0-8cde0a659950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>287e2412-b20f-4118-ad2d-b7d6ec3b1263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lastName</value>
      <webElementGuid>df366b4e-cbbb-42f4-8843-c3f1aa26141d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>240dd48d-a8c6-4445-af06-d3f263db4057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>replastName</value>
      <webElementGuid>375534eb-6fe9-4069-9ac7-1dcbca660e72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>a7b921e1-e427-49de-a4eb-aeffcdc2e15a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Business Rep Last Name</value>
      <webElementGuid>5961f5b1-cc9b-4325-b0a9-9e8a9191dc1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ReplastName&quot;)</value>
      <webElementGuid>97d7d890-b37c-4f6f-8034-d8d8bce8af34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ReplastName']</value>
      <webElementGuid>20a62b49-1caf-46cb-b9dc-eb2537897390</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='taxForm']/div[3]/div[6]/div/input</value>
      <webElementGuid>dc13b10d-e5ac-4158-9f01-9c8ea4e5aa79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>cfeac9bb-b8b8-4a11-ab10-e492067da28a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'ReplastName' and @id = 'ReplastName' and @placeholder = 'Business Rep Last Name']</value>
      <webElementGuid>caa39bd0-e17f-4b6d-bdf1-1e8d85552cb1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
