<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_BusinessRepmiddleName</name>
   <tag></tag>
   <elementGuidId>a0d71a30-5953-4636-9c22-523f52984f6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#RepmiddleName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='RepmiddleName']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'repmiddleName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fa33b14e-4edf-49a3-bcc6-eacc49b8ee5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>04a5fe34-fe2c-48d6-95fe-f35c854650c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>middleName</value>
      <webElementGuid>3cb81daa-b3e8-4ea8-9334-a0879aeace33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9878362c-93b0-46b3-9ab6-e083e5c9c609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>repmiddleName</value>
      <webElementGuid>dfbe0534-c364-4b63-8c30-86e1631142bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>d50a6eb1-75cc-4afa-a041-52d0f6410804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Business Rep Middle Name</value>
      <webElementGuid>93738be2-7175-4f31-bd56-4c7051adbb95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RepmiddleName&quot;)</value>
      <webElementGuid>6bb2af25-4740-4b0b-8a12-6f866d340103</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='RepmiddleName']</value>
      <webElementGuid>f42e162c-ef47-40ab-a4a1-3b244c7e741b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='taxForm']/div[3]/div[5]/div/input</value>
      <webElementGuid>a5b1579c-b258-4c2f-a636-887ef099c301</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>9458653e-91c1-45a2-874b-e6911b6dfe81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'RepmiddleName' and @id = 'RepmiddleName' and @placeholder = 'Business Rep Middle Name']</value>
      <webElementGuid>b928ec45-1d1a-41d8-b1af-bd9d65d608b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
