<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_TheSocial Security Number and Re-enter SSN do not match_tx_iframe_taxTypeExisitingFEINIFrame</name>
   <tag></tag>
   <elementGuidId>1a78b931-9ab0-439f-a98b-de9b75c80b93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tx_iframe_taxTypeExisitingFEINIFrame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='tx_iframe_taxTypeExisitingFEINIFrame']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'tx_iframe_taxTypeExisitingFEINIFrame' and @name = 'tx_iframe_taxTypeExisitingFEINIFrame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>974a2ab4-134e-4dce-aa84-a84743f45c63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://test-htp.tokenex.com/iframe/v3?AuthenticationKey=DjbcS1xc4TOcSG721tqfIv7ROXYjMQqRIT1ZLXZ24NQ%3D&amp;Origin=https%3A%2F%2Fqa2.velocitypayment.com&amp;TokenExID=3817434419954472&amp;Timestamp=20230903184346&amp;Container=taxTypeExisitingFEINIFrame&amp;Mode=Data&amp;PCI=false&amp;TokenScheme=nTOKENfour1to1&amp;ExpiresInSeconds=1200</value>
      <webElementGuid>d9e4e1de-d339-42b4-bd99-f1ed6e565bf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ff99012d-dbf5-4fcd-bb83-972db4958247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>8db1e874-7ff4-463b-9caa-6aad2e582aba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>c36ad09f-4019-4b3a-92d3-9a55ddc230ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tx_iframe_taxTypeExisitingFEINIFrame</value>
      <webElementGuid>bf116b60-584d-41ce-9589-9467bf8c31ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tx_iframe_taxTypeExisitingFEINIFrame</value>
      <webElementGuid>f5681dd2-c29c-41de-8b65-6d47c65157a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tx_iframe_taxTypeExisitingFEINIFrame&quot;)</value>
      <webElementGuid>adf4e35b-b565-4699-b497-68f617f9f59a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='tx_iframe_taxTypeExisitingFEINIFrame']</value>
      <webElementGuid>ccb63016-8dfc-4a44-ac45-8eaeef32af0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='taxTypeExisitingFEINIFrame']/iframe</value>
      <webElementGuid>201408d1-e0d4-40e8-9581-63f4a2614d51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[5]/fieldset/div/iframe</value>
      <webElementGuid>604b1834-8846-43e9-9ae9-03632506a2ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://test-htp.tokenex.com/iframe/v3?AuthenticationKey=DjbcS1xc4TOcSG721tqfIv7ROXYjMQqRIT1ZLXZ24NQ%3D&amp;Origin=https%3A%2F%2Fqa2.velocitypayment.com&amp;TokenExID=3817434419954472&amp;Timestamp=20230903184346&amp;Container=taxTypeExisitingFEINIFrame&amp;Mode=Data&amp;PCI=false&amp;TokenScheme=nTOKENfour1to1&amp;ExpiresInSeconds=1200' and @id = 'tx_iframe_taxTypeExisitingFEINIFrame' and @name = 'tx_iframe_taxTypeExisitingFEINIFrame']</value>
      <webElementGuid>d0fef71d-d97e-4890-8d93-d5bdc4e13762</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
