<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Please enter a valid FEIN with 9 digits_tx_iframe_reTaxTypeExisitingFEINIFrame</name>
   <tag></tag>
   <elementGuidId>829a0545-1476-4519-9f17-f26d7126fad2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tx_iframe_reTaxTypeExisitingFEINIFrame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='tx_iframe_reTaxTypeExisitingFEINIFrame']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'tx_iframe_reTaxTypeExisitingFEINIFrame' and @name = 'tx_iframe_reTaxTypeExisitingFEINIFrame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>be18ed7a-2101-4199-a3e1-8359c8e36f48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://test-htp.tokenex.com/iframe/v3?AuthenticationKey=DjbcS1xc4TOcSG721tqfIv7ROXYjMQqRIT1ZLXZ24NQ%3D&amp;Origin=https%3A%2F%2Fqa2.velocitypayment.com&amp;TokenExID=3817434419954472&amp;Timestamp=20230903184346&amp;Container=reTaxTypeExisitingFEINIFrame&amp;Mode=Data&amp;PCI=false&amp;TokenScheme=nTOKENfour1to1&amp;ExpiresInSeconds=1200</value>
      <webElementGuid>4950ebbe-1ca5-4daa-b271-e99b0c29e9cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f304806d-f34a-4abd-b8e6-a20c464b74e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>3cc37d95-ecf1-4e48-86cd-1be9e22b32d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>deb6c2fb-7ff6-43ad-804e-ff577ad7cc35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tx_iframe_reTaxTypeExisitingFEINIFrame</value>
      <webElementGuid>80d6a33b-720c-400d-a3f6-91e367fb4da7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tx_iframe_reTaxTypeExisitingFEINIFrame</value>
      <webElementGuid>2ca0affe-61dc-4415-afa6-6f37d0f0dc6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tx_iframe_reTaxTypeExisitingFEINIFrame&quot;)</value>
      <webElementGuid>00aa8e1a-1431-4683-9669-40d530e0e95d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='tx_iframe_reTaxTypeExisitingFEINIFrame']</value>
      <webElementGuid>33787aa3-71c7-477a-b10c-1b55cb3b9724</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='reTaxTypeExisitingFEINIFrame']/iframe</value>
      <webElementGuid>9edf97c6-5a00-41a5-844f-71d1d121ad60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[6]/fieldset/div/iframe</value>
      <webElementGuid>6fcb3240-731b-4f61-8543-a8d1648edd61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://test-htp.tokenex.com/iframe/v3?AuthenticationKey=DjbcS1xc4TOcSG721tqfIv7ROXYjMQqRIT1ZLXZ24NQ%3D&amp;Origin=https%3A%2F%2Fqa2.velocitypayment.com&amp;TokenExID=3817434419954472&amp;Timestamp=20230903184346&amp;Container=reTaxTypeExisitingFEINIFrame&amp;Mode=Data&amp;PCI=false&amp;TokenScheme=nTOKENfour1to1&amp;ExpiresInSeconds=1200' and @id = 'tx_iframe_reTaxTypeExisitingFEINIFrame' and @name = 'tx_iframe_reTaxTypeExisitingFEINIFrame']</value>
      <webElementGuid>8aa407fc-212a-4a5c-aea3-c142cd64f202</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
