<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_HideAll</name>
   <tag></tag>
   <elementGuidId>b6b6934c-0dbb-4783-b46a-cfbfde758991</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='showHideElements(billDetailSpanArray,divArray,disdivArray,checkboxArray,false);']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#billListForm > div > a:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Hide All&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>88ef6225-0c0e-4edf-83b4-797f82f0aca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>29dd9337-9f3c-4c5d-b24b-8716250d1f5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>showHideElements(billDetailSpanArray,divArray,disdivArray,checkboxArray,false);</value>
      <webElementGuid>4dd6518b-aeb4-4331-ae39-a5e43807e479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hide All</value>
      <webElementGuid>80d7108d-580f-4323-8769-b0e9c5a60735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billListForm&quot;)/div[1]/a[2]</value>
      <webElementGuid>6706be4c-4836-46eb-8fcb-bcd3bf287a77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='showHideElements(billDetailSpanArray,divArray,disdivArray,checkboxArray,false);']</value>
      <webElementGuid>c5131079-fb14-45bd-a337-530dbd924a38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='billListForm']/div/a[2]</value>
      <webElementGuid>93981a57-5a7d-44f9-a8a7-ae3bd2844d45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Hide All')]</value>
      <webElementGuid>29b90865-7923-4614-84c6-dc3b2d59c74b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Find Other Bills Label'])[1]/preceding::a[1]</value>
      <webElementGuid>61dfcae2-6a1f-4eb1-a9a6-47176f68ee9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check to Pay'])[1]/preceding::a[2]</value>
      <webElementGuid>ed242eb7-d543-4784-95ae-dd4b2d9a22a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hide All']/parent::*</value>
      <webElementGuid>69e4286b-1278-4e5c-8228-248caa64a7ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[4]</value>
      <webElementGuid>ee353c4e-2985-402d-bb1c-3dee4738f79c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>c8064de5-9fab-4513-b4d5-53d845502604</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Hide All' or . = 'Hide All')]</value>
      <webElementGuid>9b687f7a-958a-4099-b0f3-99e0bf9216c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
