<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_SchedulePaymentIcon</name>
   <tag></tag>
   <elementGuidId>229b0cb8-572d-4269-8b08-df8fe61d6d18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;schedule payment plan&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='time1']/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;schedule payment plan&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3a0db002-fffb-4ade-aa7b-13ae47490033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/vbills/_assets/img/time.gif</value>
      <webElementGuid>7101af53-8112-45be-8f4d-b99968bc556b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>schedule payment plan</value>
      <webElementGuid>a56b38ef-6dca-42da-bd51-d1868fd0a2cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>schedule payment plan</value>
      <webElementGuid>1a2a5a58-14ea-49e8-bc92-ad3c690f2be2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>1e55834b-cc8e-48e4-a9b2-15137064835a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>5f68906f-44a1-4b84-afd1-b6ec20362f8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>200acad1-60b4-490e-bb21-da88491a4479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;time1&quot;)/a[1]/img[1]</value>
      <webElementGuid>9b82c453-ee7d-4346-b934-04ee5634cc64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='time1']/a/img</value>
      <webElementGuid>141db7ff-7649-4978-ac40-542391256ea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='schedule payment plan']</value>
      <webElementGuid>0ad12171-cae9-410f-9ccf-eba48502562f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/div/a/img</value>
      <webElementGuid>e6fcbb88-c444-4f4f-975d-fad15a822d80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/vbills/_assets/img/time.gif' and @alt = 'schedule payment plan' and @title = 'schedule payment plan']</value>
      <webElementGuid>c31e7927-2496-4d9d-9c8e-611a43ad895d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
