<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_UDF4</name>
   <tag></tag>
   <elementGuidId>ea71ce5a-38ae-4daf-ad0d-b1fea16bcc3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @name = 'billDetailForms[0].billerDefinedField4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;billDetailForms[0].billerDefinedField4&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='billDetailForms[0].billerDefinedField4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[alt=&quot;variable_field_4_label_916&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1fe4ef33-0ea5-4f32-8ca9-d130732f4b2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>db944f72-e092-4eae-9ce5-62ce19c5aeb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billDetailForms[0].billerDefinedField4</value>
      <webElementGuid>b2c94bef-18d7-4a8f-8f5d-536a8e3e0cb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>a47d851f-67f5-4034-a1a6-7db5878c0e45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>da8f676c-a924-4a6e-b14e-8dd1e5a6243a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>udf4</value>
      <webElementGuid>4ea85c3c-177f-4448-b284-8c0999e1dcd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>customOnChangeUdf4(this, 916)</value>
      <webElementGuid>995d160e-0bdf-4150-b5da-911bf985acbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>variable_field_4_label_916</value>
      <webElementGuid>89b21a7c-2635-49bb-b495-c383f2349f2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;udf1&quot;)/table[1]/tbody[1]/tr[4]/td[2]/input[1]</value>
      <webElementGuid>7595494d-2572-4c02-ad80-af6aac5f5ddb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='billDetailForms[0].billerDefinedField4']</value>
      <webElementGuid>e42d89bc-443e-4fac-902d-7b1e03171dfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='udf1']/table/tbody/tr[4]/td[2]/input</value>
      <webElementGuid>e9c64e34-7a24-459f-8e4b-50af71d20e0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/input</value>
      <webElementGuid>7564966d-0518-4314-8c3c-a77b224114d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'billDetailForms[0].billerDefinedField4' and @alt = 'variable_field_4_label_916']</value>
      <webElementGuid>4ac35325-5daf-4061-9950-85b4eda68f7f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
