<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_udf3</name>
   <tag></tag>
   <elementGuidId>06c421b3-5fd2-4e28-aa9a-8fbcde25c2cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#udf1 > table > tbody > tr:nth-of-type(3) > td:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='udf1']/table/tbody/tr[3]/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;udf3&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>5d94402f-9151-457d-a71c-7d3f59f30bfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
	                	udf3
	                </value>
      <webElementGuid>fd25faee-a58c-48cb-8522-1598372f1bf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;udf1&quot;)/table[1]/tbody[1]/tr[3]/td[2]</value>
      <webElementGuid>58e8c278-535c-49bd-be09-b5c9cc9db019</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='udf1']/table/tbody/tr[3]/td[2]</value>
      <webElementGuid>096e1270-50eb-4edd-9ea7-abcd8503ad22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UDF3:'])[1]/following::td[1]</value>
      <webElementGuid>48a3051b-e6b3-4083-816b-9454d4615d66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::td[3]</value>
      <webElementGuid>2ec292ab-7c1e-4cdd-94b5-cf2680f395e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UDF4:'])[1]/preceding::td[1]</value>
      <webElementGuid>9148cc7b-619e-4dd8-8810-36a22fa5cdce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='udf3']/parent::*</value>
      <webElementGuid>178ba509-b888-4107-b485-3f0e2abf1f27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/table/tbody/tr[3]/td[2]</value>
      <webElementGuid>d2fd3423-407c-4b34-8545-753720bc89ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '
	                	udf3
	                ' or . = '
	                	udf3
	                ')]</value>
      <webElementGuid>72f58920-f279-44ce-9b2b-3c81b3491ffb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
