<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Exit</name>
   <tag></tag>
   <elementGuidId>2f6008ef-3f7c-47f3-94e1-0862ed70ce82</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e7d2df2c-ea39-44fa-9401-0341ca72bf9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7854c6e5-61cf-4a19-98eb-cc38974e5900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>exit</value>
      <webElementGuid>4210db0f-1bd2-4e1a-b853-6ad1f79c1723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Exit</value>
      <webElementGuid>9dea9bbf-e548-4ced-acc7-3bc82a1665d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>payor_opt</value>
      <webElementGuid>5292b71d-1626-4175-8d24-ab217fd21df0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>location.href='http://www.govolution.com/ ?remittance_id=dfsdf34sdfsdf&amp;security_id=ad7f100c7271e3d0c591ad4b3ac49389&amp;application_id=649';</value>
      <webElementGuid>1f597353-30dd-4435-9b53-72f6efd9c472</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5ba09150-3538-4bae-8529-f13e6127190a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;main_col&quot;]/form[1]/table[1]/tbody[1]/tr[35]/td[2]/div[1]/input[@class=&quot;payor_opt&quot;]</value>
      <webElementGuid>b698e801-1e9a-40bd-847f-bf0633844d9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='exit']</value>
      <webElementGuid>d575514c-27dc-4a16-9c68-a5684261442a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input[3]</value>
      <webElementGuid>a34e6e48-cb5f-4d42-87bc-ca107001db20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
