<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>datePicker_PayDate</name>
   <tag></tag>
   <elementGuidId>f53c48d6-57ad-4fd9-9f01-a5cb23cc279e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='disc_payDate1']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;click to launch calendar and pick a date to pay&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;click to launch calendar and pick a date to pay&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b4f546aa-00b3-40f3-b111-e5d4f095e44c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>b6f7c36f-f840-469d-95ed-fe82e46baef6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>0648490b-c8e1-41db-84fd-1bebbe0244fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>absmiddle</value>
      <webElementGuid>aaf464ff-8f00-4ce6-8d59-cb35b6d1fa8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c8a041e4-079a-474a-b695-d8ed5246ca94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>click to launch calendar and pick a date to pay</value>
      <webElementGuid>d6d692aa-98d5-46a8-83e6-1425331f52bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>click to launch calendar and pick a date to pay</value>
      <webElementGuid>d186ccb0-fb0a-4f21-b751-c84192273b19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/vbills/_assets/img/calendar_dis.gif</value>
      <webElementGuid>76300f21-8717-4ed0-b902-8bd72a9a19bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;disc_payDate1&quot;)/img[1]</value>
      <webElementGuid>a247d911-23bd-4938-845c-5f3c40f1fc06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='disc_payDate1']/img</value>
      <webElementGuid>7d8f2d7f-225f-4e0c-8c9b-b9dbf448f235</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='click to launch calendar and pick a date to pay']</value>
      <webElementGuid>a4d81730-cb2d-4f11-9d35-925d6c274bec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>571c8de7-7cdb-4082-8027-38ff6b1d974a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@title = 'click to launch calendar and pick a date to pay' and @alt = 'click to launch calendar and pick a date to pay' and @src = '/vbills/_assets/img/calendar_dis.gif']</value>
      <webElementGuid>ce5a901a-8e02-44e4-b1bd-3baef2183af1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
