<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Month</name>
   <tag></tag>
   <elementGuidId>db62bb19-04e3-4ac2-ae7f-6381d6e75473</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cardExpireMonth']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cardExpireMonth</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cardExpireMonth</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9cd0d757-3852-4c47-93d6-20591d84713c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>paymentMethodForm.cardExpireMonth</value>
      <webElementGuid>2d6e25fb-10c7-4619-a613-0c14f064a076</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cardExpireMonth</value>
      <webElementGuid>d65bd927-d0a3-4e68-a3b0-93d2dee5a27b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Month...
                                            01
                                            02
                                            03
                                            04
                                            05
                                            06
                                            07
                                            08
                                            09
                                            10
                                            11
                                            12</value>
      <webElementGuid>24f40e29-da0b-49fa-af37-a207f4022d34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cardExpireMonth&quot;)</value>
      <webElementGuid>ba60772f-d65e-45b4-91a7-e9cb93053791</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cardExpireMonth']</value>
      <webElementGuid>b0b09d9e-8a13-46dc-865b-3387497d4814</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area_creditCard']/table/tbody/tr[5]/td[2]/select</value>
      <webElementGuid>fd511565-e2f9-4a5f-87cc-f7ae75406d71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::select[1]</value>
      <webElementGuid>37227d14-8fa0-41e9-8c52-96d7e1b9ccfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expiration Date:'])[1]/following::select[1]</value>
      <webElementGuid>a1f821f2-bbfb-44a2-a9ee-4ec06627da39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bank Account Information'])[1]/preceding::select[2]</value>
      <webElementGuid>eec9a8be-cc00-4c4d-9eea-88398c0e4ad9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company Name:'])[1]/preceding::select[2]</value>
      <webElementGuid>8d1b02f8-48eb-4828-b524-c61c1945f17d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[2]/select</value>
      <webElementGuid>11e657d2-be84-4550-8cc6-18a40a133e88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'paymentMethodForm.cardExpireMonth' and @id = 'cardExpireMonth' and (text() = 'Month...
                                            01
                                            02
                                            03
                                            04
                                            05
                                            06
                                            07
                                            08
                                            09
                                            10
                                            11
                                            12' or . = 'Month...
                                            01
                                            02
                                            03
                                            04
                                            05
                                            06
                                            07
                                            08
                                            09
                                            10
                                            11
                                            12')]</value>
      <webElementGuid>bc0e89cb-e394-4f2c-8686-cfc963ebbea2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
