<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DividetheBalanceDue</name>
   <tag></tag>
   <elementGuidId>e78f83b7-8e80-4617-8556-3e5771be7540</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#numberOfPayments</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='numberOfPayments']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Divide the Balance Due into payments&quot;s] >> internal:attr=[alt=&quot;Number of Payments&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d27f0e0b-6e02-4ecd-a9c2-6b4060edbbcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2b02beae-1017-42dd-85f0-efbde6e1d33d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>numberOfPayments</value>
      <webElementGuid>e4d7471f-494b-4eb2-b674-045a705040b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>d8ca3d49-be72-434c-8dcb-e62b5574c19d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>f14e87ec-f2be-4ddd-b2d6-15b40adc9aca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e429bb23-4202-48b6-be35-fcb544e936d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>numberOfPaymentsChanged()</value>
      <webElementGuid>167af2bd-d615-4c6e-93ae-2a48124b939d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>numberOfPayments</value>
      <webElementGuid>4226743e-8f2c-433c-9727-0adea6681852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Number of Payments</value>
      <webElementGuid>ee7268d4-452b-43ac-995f-fe0058a1f2e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;numberOfPayments&quot;)</value>
      <webElementGuid>382f345f-0e68-4c07-9fd5-ad100b1ef5b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='numberOfPayments']</value>
      <webElementGuid>da59c516-e014-49d3-adaa-0e2cbb8dfc9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divDivideOfPayments']/table/tbody/tr/td[2]/input</value>
      <webElementGuid>49e194fc-1d7f-4fd1-871b-d08235225373</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>d6ce1f31-d9e4-4797-847b-efef26fbf67c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'numberOfPayments' and @id = 'numberOfPayments' and @alt = 'Number of Payments']</value>
      <webElementGuid>0184c852-0a22-4ec0-a7a6-4f3077fd8312</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
