<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_RepeatthisAmountuntiltheBalanceDue</name>
   <tag></tag>
   <elementGuidId>f7f95c8a-ed97-49cf-a591-9052456a7b78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#paymentAmount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='paymentAmount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Repeat this amount until the Balance Due is achieved: $&quot;s] >> internal:attr=[alt=&quot;Individual Amount&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7777f421-8dc0-4cda-b5d2-bfe5cb8e7d53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>32c844e2-b6a4-4a9c-8269-e28a0309bf20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>paymentAmount</value>
      <webElementGuid>e7ce7966-2a99-4060-8d50-0c18030e72b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>dc3d0937-438e-492b-8447-1c888e3f7464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>be849862-3bb3-4cf7-ae82-c07a3018727e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>10.00</value>
      <webElementGuid>d533b1c4-bf11-4b53-989e-08f26f556089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>paymentAmountChanged()</value>
      <webElementGuid>03c435c8-8467-4ae2-8ba4-04e92aef0883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>paymentAmount</value>
      <webElementGuid>51085d56-cb1a-43f7-9c28-ec7b53cb64ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Individual Amount</value>
      <webElementGuid>37ce1c8f-96d8-44e2-83f7-0111fa433488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paymentAmount&quot;)</value>
      <webElementGuid>cc00c6c1-c757-48ea-84f2-9b41a97d5dce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='paymentAmount']</value>
      <webElementGuid>4a20fb9f-eec2-4a13-8ce8-73f069fef9d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divDivideOfPayments']/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>fe498ab9-31ac-4b3b-af9e-e53e9c7e52f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>5ae6f4bd-0f36-4b53-beff-43233cecc022</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'paymentAmount' and @id = 'paymentAmount' and @alt = 'Individual Amount']</value>
      <webElementGuid>faa1df4c-c222-4da3-8811-14cd8a83314e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
