<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_UDF4</name>
   <tag></tag>
   <elementGuidId>b4c1b18f-1ea6-4064-b8af-060ea0969765</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;billDetailForm.billerDefinedField4&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='billDetailForm.billerDefinedField4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[alt=&quot;variable_field_4_label_917&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e5339bfb-401f-4767-8d44-1a8e61544c2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>67b53cc4-634a-4fb3-97cb-5fc0a08f3599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billDetailForm.billerDefinedField4</value>
      <webElementGuid>d37c69ff-3574-42a7-a0e1-1af3411ffc33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>09c00e5a-e14c-4089-b441-24f9d766a2ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>7f66a4f8-1c76-4a7a-ad59-d9e03b8408c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>udf4</value>
      <webElementGuid>992c42e9-8148-4959-933c-605f92d56e09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>customOnChangeUdf4(this, 917)</value>
      <webElementGuid>2938080a-c45d-4da9-86ba-e3138078cbca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>variable_field_4_label_917</value>
      <webElementGuid>277c0048-f023-4303-87fe-0c9918f1b354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;udf&quot;)/table[1]/tbody[1]/tr[4]/td[2]/input[1]</value>
      <webElementGuid>34384b40-8b85-411f-86fb-ae920111881e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='billDetailForm.billerDefinedField4']</value>
      <webElementGuid>fb7c86ba-5938-464e-9bf0-2a64c6bfbe1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='udf']/table/tbody/tr[4]/td[2]/input</value>
      <webElementGuid>92164c91-5a74-40bc-87b7-e9da4890af81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/input</value>
      <webElementGuid>dc407759-0a9f-4a05-92f9-12d7bb0a0b82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'billDetailForm.billerDefinedField4' and @alt = 'variable_field_4_label_917']</value>
      <webElementGuid>6d492fca-48ab-43e5-8b1c-64d7b09a4685</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
