<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_UDF1</name>
   <tag></tag>
   <elementGuidId>8a0ecd61-6450-439d-99ca-0fe92d4a8b5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='billDetailForm.billerDefinedField1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;billDetailForm.billerDefinedField1&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @name = 'billDetailForm.billerDefinedField1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[alt=&quot;variable_field_1_label_917&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bd8b9d68-3af2-4539-be9b-387fe2d8d464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a2b03023-966b-42ff-b459-6cbe3bb670fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billDetailForm.billerDefinedField1</value>
      <webElementGuid>6883d6fe-05fc-4229-8e9d-86719f9fdc0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>f1a53660-49a4-485e-8515-f9712ac5b1e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>418288a1-7eef-458a-abaa-2fa9064238fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>udf1</value>
      <webElementGuid>4f740713-6920-461d-93bf-f2de455967be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>customOnChangeUdf1(this, 917)</value>
      <webElementGuid>79c46798-cd2e-4279-a724-cbca4ae5c2c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>variable_field_1_label_917</value>
      <webElementGuid>60e917d2-b87c-418f-a6e5-ba3fb6a63f19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;udf&quot;)/table[1]/tbody[1]/tr[1]/td[2]/input[1]</value>
      <webElementGuid>88522185-d336-45ec-8afa-068ad2e0da83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='billDetailForm.billerDefinedField1']</value>
      <webElementGuid>07f10680-0b8c-42b4-bcf6-563721645df1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='udf']/table/tbody/tr/td[2]/input</value>
      <webElementGuid>ec041468-b005-437f-a018-cde4a8336dca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>5090228e-a1d8-465a-b38f-50cbb6b5f58b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'billDetailForm.billerDefinedField1' and @alt = 'variable_field_1_label_917']</value>
      <webElementGuid>7cbf00e3-3e65-426b-b400-f4189173124e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
