<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_InstallmentPlan</name>
   <tag></tag>
   <elementGuidId>c96c1ff8-8ee5-48d8-b978-aaa35135c5bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#installment_plan_radio</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='installment_plan_radio']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Installment Plan - Multiple payments fulfill a single bill.&quot;i] >> internal:attr=[alt=&quot;Number of Payments&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a872feaa-5764-4bce-93ce-c9d4a868a50f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>01850e88-e28b-45e7-a17d-3772e35eecd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>paymentPlanCategory</value>
      <webElementGuid>23f5a52f-6ffc-424b-86c8-334f6c6732b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e270b272-4e66-4297-8b25-a1c15b278c52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>showFrequencyAndDivide()</value>
      <webElementGuid>dd03e0f2-7677-44ca-b3a4-d1b65390b452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>installment_plan_radio</value>
      <webElementGuid>545c4fc3-5fe2-409a-bf70-2f3ce6f987f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Number of Payments</value>
      <webElementGuid>0de13a33-cce3-49b1-917d-25407a27687b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;installment_plan_radio&quot;)</value>
      <webElementGuid>bed8bd1d-645e-4791-9d3b-2d7db7df4258</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='installment_plan_radio']</value>
      <webElementGuid>1a5b1806-4edd-487d-ba5b-0467290224c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='scheduledPaymentForm']/table[4]/tbody/tr/td/input</value>
      <webElementGuid>4577c7e6-cf56-4e8b-afff-12123e39850e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[4]/tbody/tr/td/input</value>
      <webElementGuid>bafdb24c-8398-49b4-b225-f2bcf78e06db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'paymentPlanCategory' and @id = 'installment_plan_radio' and @alt = 'Number of Payments']</value>
      <webElementGuid>64b6b93e-3700-4bda-8232-1486b66f4298</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
