<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_AutomaticPayment</name>
   <tag></tag>
   <elementGuidId>e026858a-cb78-410f-a649-dff3c12fa27c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#automatic_payment_radio</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='automatic_payment_radio']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Automatic Payment - Bills are automatically paid 3 calendar days before the Due Date.&quot;i] >> internal:attr=[alt=&quot;Individual Amount&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4b622045-d0c9-43c6-ba8c-93b58e9e5ea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>88762432-cb40-4e9f-a5bd-5acccaa364a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>paymentPlanCategory</value>
      <webElementGuid>1b6580a9-35a4-42b4-b995-b11b1a660756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>e83bdfd9-2d2d-498f-8d5a-c8b65819b15e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>hideFrequencyAndDivide()</value>
      <webElementGuid>ce7c090c-a224-4429-9183-e303071965b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>automatic_payment_radio</value>
      <webElementGuid>84e45802-a0c1-4a4f-97d1-b3e9dfe7969f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Individual Amount</value>
      <webElementGuid>3e184212-a1fd-436e-955f-769fb8b956d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;automatic_payment_radio&quot;)</value>
      <webElementGuid>54ee88b2-c942-492f-b57c-854814c3aed6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='automatic_payment_radio']</value>
      <webElementGuid>4c016345-6d9f-4d75-8c0b-f69c65dc91f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='scheduledPaymentForm']/table[4]/tbody/tr[3]/td/input</value>
      <webElementGuid>80bb9952-0263-4eb3-b7f1-f60602a3a5f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[4]/tbody/tr[3]/td/input</value>
      <webElementGuid>a673a8cd-ac0f-42b9-abd3-a8495dae7a9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'paymentPlanCategory' and @id = 'automatic_payment_radio' and @alt = 'Individual Amount']</value>
      <webElementGuid>dff4ac37-9121-47e6-9bee-4df3c99292be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
