<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_RecurringAmount</name>
   <tag></tag>
   <elementGuidId>815da0e9-ea52-4da3-852f-622007d16c71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#recurring_Amount_radio</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='recurring_Amount_radio']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Recurring Fixed Amount Payment - The same amount is paid at a determined frequency.&quot;i] >> internal:attr=[alt=&quot;Number of Payments&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5c50e454-1605-4fa8-ae6a-33207ec2e23c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>f86d3f12-aae8-4de8-8caa-721e2910bf94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>paymentPlanCategory</value>
      <webElementGuid>28eb6bd1-b1fa-418a-9b3c-0a54008fec29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>36791667-bb31-4992-a287-607cf9f3ed4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>showFrequency()</value>
      <webElementGuid>8fa8d95d-599f-4b1f-8658-26eb47d464e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>recurring_Amount_radio</value>
      <webElementGuid>ad99ebd1-8251-4925-a35f-376297879686</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Number of Payments</value>
      <webElementGuid>0cf4e0c7-df32-4f44-8de3-30722ca8a205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;recurring_Amount_radio&quot;)</value>
      <webElementGuid>78e73060-820c-453f-9148-ac57d67fd764</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='recurring_Amount_radio']</value>
      <webElementGuid>88e47123-487e-4761-ac9e-fcc82c9fe461</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='scheduledPaymentForm']/table[4]/tbody/tr[2]/td/input</value>
      <webElementGuid>53b139a5-492f-4f61-a277-cc923eddaf1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[4]/tbody/tr[2]/td/input</value>
      <webElementGuid>694d1c4e-a326-4702-b1c2-41b1f22eab8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'paymentPlanCategory' and @id = 'recurring_Amount_radio' and @alt = 'Number of Payments']</value>
      <webElementGuid>1c2b8b5d-2180-4bfc-8c25-9e4ccff8f985</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
