import internal.GlobalVariable as GlobalVariable
import com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords as WebUI

WebUI.openBrowser('https://www.google.com/')
String baseUrl = "https://www.google.com/"
int pageLoadTimeoutSeconds = 30
def to = { String locator -> CustomKeywords.'customClasses.LegacyLocatorUtils.testObjectFromLegacyLocator'(locator) }
println("Verify that a Credit Card Payment can be modified")

def bbpURL = GlobalVariable.BBPURL
if (bbpURL?.startsWith('http://') || bbpURL?.startsWith('https://')) {
	WebUI.navigateToUrl(bbpURL)
} else {
	WebUI.navigateToUrl(baseUrl + bbpURL)
}


WebUI.setText(to("id=field1"), "111150")
WebUI.setText(to("id=field2"), "111151")
WebUI.click(to("name=Test"))
WebUI.delay(2)
WebUI.click(to("name=paysubmit"))
WebUI.waitForPageLoad(pageLoadTimeoutSeconds)
WebUI.click(to("name=paymentMethod"))
WebUI.click(to("css=input[type=\"submit\"]"))
WebUI.waitForPageLoad(pageLoadTimeoutSeconds)
//softAssertion.assertEquals("Required fields are highlighted with an asterisk.", selenium.getText("css=span.required"))
//softAssertion.assertEquals("Please enter the following information about your payment:", selenium.getText("css=span.vrelay-header"))

WebUI.verifyTextPresent(("Required fields are highlighted with an asterisk."), true)
WebUI.verifyTextPresent(("Please enter the following information about your payment:"), true)


WebUI.setText(to("name=amount"), ("12.00").toString())
WebUI.setText(to("name=userDefined2"), ("UDF2 Data1").toString())
WebUI.setText(to("name=userDefined3"), ("UDF3 Data1").toString())
WebUI.selectOptionByLabel(to("name=variableField4DropdownGroupItemID"), "Purple", false)
WebUI.selectOptionByLabel(to("name=variableField5DropdownGroupItemID"), "Orange", false)
WebUI.setText(to("name=userDefined6"), ("UDF6 Data1").toString())
WebUI.setText(to("name=userDefined7"), ("UDF7 Data1").toString())
WebUI.setText(to("name=userDefined8"), ("UDF8 Data1").toString())
WebUI.setText(to("name=billingName"), ("Hunter Helms").toString())
WebUI.setText(to("id=cardNumber"), "4111111111111111")
WebUI.setText(to("id=spc"), "123")
WebUI.selectOptionByLabel(to("name=cardExpMonth"), "04", false)
WebUI.selectOptionByLabel(to("name=cardExpYear"), "2028", false)
WebUI.setText(to("name=billingAddress"), ("2311 york road").toString())
WebUI.setText(to("name=billingAddress2"), ("Suite 600").toString())
WebUI.setText(to("id=billing-zip-input"), "21054")
WebUI.setText(to("name=emailAddress"), ("iahmed@govolution.com").toString())
WebUI.click(to("id=checkedAcceptCondition"))
WebUI.click(to("name=ccSubmit"))
WebUI.waitForPageLoad(pageLoadTimeoutSeconds)

WebUI.verifyTextPresent(("Please verify the following information:"), true)
WebUI.verifyTextPresent(("Is this information correct"), true)


//softAssertion.assertEquals("$12.00", selenium.getText("//tr[4]/td[3]"))
//softAssertion.assertEquals("UDF2 Data1", selenium.getText("//tr[6]/td[3]"))
//softAssertion.assertEquals("UDF3 Data1", selenium.getText("//tr[7]/td[3]"))
//softAssertion.assertEquals("Purple", selenium.getText("//tr[8]/td[3]"))
//softAssertion.assertEquals("Orange", selenium.getText("//tr[9]/td[3]"))
//softAssertion.assertEquals("UDF6 Data1", selenium.getText("//tr[10]/td[3]"))
//softAssertion.assertEquals("UDF7 Data1", selenium.getText("//tr[11]/td[3]"))
//softAssertion.assertEquals("UDF8 Data1", selenium.getText("//tr[12]/td[3]"))
//softAssertion.assertEquals("Hunter Helms", selenium.getText("//tr[15]/td[3]"))
//softAssertion.assertEquals("Visa", selenium.getText("//tr[16]/td[3]"))
//softAssertion.assertEquals(Pattern.matches('selenium.getText("//tr[17]/td[3]")', '^exact:[\\s\\S]*[\\s\\S]*[\\s\\S]*[\\s\\S]*[\\s\\S]*[\\s\\S]*[\\s\\S]*[\\s\\S]*[\\s\\S]*[\\s\\S]*[\\s\\S]*[\\s\\S]*1111$'), true)
//softAssertion.assertEquals("4/2025", selenium.getText("//tr[19]/td[3]"))
//softAssertion.assertEquals("2311 york road", selenium.getText("//tr[22]/td[3]"))
//softAssertion.assertEquals("Suite 600", selenium.getText("//tr[23]/td[3]"))
//softAssertion.assertEquals("United States", selenium.getText("//tr[24]/td[3]"))
//softAssertion.assertEquals("GAMBRILLS", selenium.getText("//tr[25]/td[3]"))
//softAssertion.assertEquals("Maryland", selenium.getText("//tr[26]/td[3]"))
//softAssertion.assertEquals("21054", selenium.getText("//tr[27]/td[3]"))
//softAssertion.assertEquals("iahmed@govolution.com", selenium.getText("//tr[29]/td[3]"))

WebUI.verifyTextPresent(("12.00"), true)
WebUI.verifyTextPresent(("UDF2 Data1"), true)
WebUI.verifyTextPresent(("UDF3 Data1"), true)
WebUI.verifyTextPresent(("Purple"), true)
WebUI.verifyTextPresent(("Orange"), true)
WebUI.verifyTextPresent(("UDF6 Data1"), true)
WebUI.verifyTextPresent(("UDF7 Data1"), true)
WebUI.verifyTextPresent(("UDF8 Data1"), true)
WebUI.verifyTextPresent(("Hunter Helms"), true)
WebUI.verifyTextPresent(("Visa"), true)
WebUI.verifyTextPresent(("1111"), true)
WebUI.verifyTextPresent(("4/2028"), true)
WebUI.verifyTextPresent(("2311 york road"), true)
WebUI.verifyTextPresent(("Suite 600"), true)
WebUI.verifyTextPresent(("United States"), true)
WebUI.verifyTextPresent(("GAMBRILLS"), true)
WebUI.verifyTextPresent(("Maryland"), true)
WebUI.verifyTextPresent(("21054"), true)
WebUI.verifyTextPresent(("iahmed@govolution.com"), true)



WebUI.click(to("xpath=(//input[@name='confirmNotifyAction'])[2]"))
WebUI.waitForPageLoad(pageLoadTimeoutSeconds)
WebUI.setText(to("name=amount"), ("20.00").toString())
WebUI.setText(to("name=userDefined2"), ("UDF2 Data1 Modified").toString())
WebUI.setText(to("name=userDefined3"), ("UDF3 Data1 Modified").toString())
WebUI.selectOptionByLabel(to("name=variableField4DropdownGroupItemID"), "Orange", false)
WebUI.selectOptionByLabel(to("name=variableField5DropdownGroupItemID"), "Purple", false)
WebUI.setText(to("name=userDefined6"), ("UDF6 Data1 Modified").toString())
WebUI.setText(to("name=userDefined7"), ("UDF7 Data1 Modified").toString())
WebUI.setText(to("name=userDefined8"), ("UDF8 Data1 Modified").toString())
WebUI.setText(to("name=billingName"), ("Jyoti James").toString())
WebUI.setText(to("id=cardNumber"), "5424000000000015")
WebUI.setText(to("id=spc"), "123")
WebUI.selectOptionByLabel(to("name=cardExpMonth"), "09", false)
WebUI.selectOptionByLabel(to("name=cardExpYear"), "2029", false)
WebUI.setText(to("name=billingAddress"), ("15 Main Street").toString())
WebUI.setText(to("name=billingAddress2"), ("Building 2").toString())
WebUI.setText(to("id=billing-zip-input"), "21114")
WebUI.setText(to("name=emailAddress"), ("imtiazster@gmail.com").toString())
WebUI.click(to("name=ccSubmit"))
WebUI.waitForPageLoad(pageLoadTimeoutSeconds)
//softAssertion.assertEquals("$20.00", selenium.getText("//tr[4]/td[3]"))
//softAssertion.assertEquals("UDF2 Data1 Modified", selenium.getText("//tr[6]/td[3]"))
//softAssertion.assertEquals("UDF3 Data1 Modified", selenium.getText("//tr[7]/td[3]"))
//softAssertion.assertEquals("Orange", selenium.getText("//tr[8]/td[3]"))
//softAssertion.assertEquals("Purple", selenium.getText("//tr[9]/td[3]"))
//softAssertion.assertEquals("UDF6 Data1 Modified", selenium.getText("//tr[10]/td[3]"))
//softAssertion.assertEquals("UDF7 Data1 Modified", selenium.getText("//tr[11]/td[3]"))
//softAssertion.assertEquals("UDF8 Data1 Modified", selenium.getText("//tr[12]/td[3]"))
//softAssertion.assertEquals("Jyoti James", selenium.getText("//tr[15]/td[3]"))
//softAssertion.assertEquals("MasterCard", selenium.getText("//tr[16]/td[3]"))
//softAssertion.assertEquals(Pattern.matches('selenium.getText("//tr[17]/td[3]")', '^exact:[\\s\\S]*[\\s\\S]*[\\s\\S]*[\\s\\S]*[\\s\\S]*[\\s\\S]*[\\s\\S]*[\\s\\S]*[\\s\\S]*[\\s\\S]*[\\s\\S]*[\\s\\S]*0015$'), true)
//softAssertion.assertEquals("9/2026", selenium.getText("//tr[19]/td[3]"))
//softAssertion.assertEquals("15 Main Street", selenium.getText("//tr[22]/td[3]"))
//softAssertion.assertEquals("Building 2", selenium.getText("//tr[23]/td[3]"))
//softAssertion.assertEquals("United States", selenium.getText("//tr[24]/td[3]"))
//softAssertion.assertEquals("CROFTON", selenium.getText("//tr[25]/td[3]"))
//softAssertion.assertEquals("Maryland", selenium.getText("//tr[26]/td[3]"))
//softAssertion.assertEquals("21114", selenium.getText("//tr[27]/td[3]"))
//softAssertion.assertEquals("imtiazster@gmail.com", selenium.getText("//tr[29]/td[3]"))


WebUI.verifyTextPresent(("20.00"), true)
WebUI.verifyTextPresent(("UDF2 Data1 Modified"), true)
WebUI.verifyTextPresent(("UDF3 Data1 Modified"), true)
WebUI.verifyTextPresent(("Orange"), true)
WebUI.verifyTextPresent(("Purple"), true)
WebUI.verifyTextPresent(("UDF6 Data1 Modified"), true)
WebUI.verifyTextPresent(("UDF7 Data1 Modified"), true)
WebUI.verifyTextPresent(("UDF8 Data1 Modified"), true)
WebUI.verifyTextPresent(("Jyoti James"), true)
WebUI.verifyTextPresent(("MasterCard"), true)
WebUI.verifyTextPresent(("0015"), true)
WebUI.verifyTextPresent(("9/2029"), true)
WebUI.verifyTextPresent(("15 Main Street"), true)
WebUI.verifyTextPresent(("Building 2"), true)
WebUI.verifyTextPresent(("United States"), true)
WebUI.verifyTextPresent(("CROFTON"), true)
WebUI.verifyTextPresent(("Maryland"), true)
WebUI.verifyTextPresent(("21114"), true)
WebUI.verifyTextPresent(("imtiazster@gmail.com"), true)



WebUI.click(to("name=confirmNotifyAction"))
WebUI.waitForPageLoad(pageLoadTimeoutSeconds)
WebUI.delay(15)
//softAssertion.assertEquals(Pattern.matches('selenium.getText("//tr[16]/td[2]")', "MasterCard.*"), true)
//softAssertion.assertEquals(Pattern.matches('selenium.getText("//tr[16]/td[2]")', "JYOTI JAMES.*"), true)
//softAssertion.assertEquals(Pattern.matches('selenium.getText("//tr[16]/td[2]")', "0015.*"), true)
//softAssertion.assertEquals(Pattern.matches('selenium.getText("//tr[17]/td[2]")', "15 Main Street.*"), true)
//softAssertion.assertEquals(Pattern.matches('selenium.getText("//tr[17]/td[2]")', "Building 2.*"), true)
//softAssertion.assertEquals(Pattern.matches('selenium.getText("//tr[17]/td[2]")', "United States.*"), true)
//softAssertion.assertEquals(Pattern.matches('selenium.getText("//tr[17]/td[2]")', "CROFTON.*"), true)
//softAssertion.assertEquals(Pattern.matches('selenium.getText("//tr[17]/td[2]")', "Maryland.*"), true)
//softAssertion.assertEquals(Pattern.matches('selenium.getText("//tr[17]/td[2]")', "21114.*"), true)

WebUI.verifyTextPresent(("MasterCard"), true)
WebUI.verifyTextPresent(("JYOTI JAMES"), true)
WebUI.verifyTextPresent(("0015"), true)
WebUI.verifyTextPresent(("15 Main Street"), true)
WebUI.verifyTextPresent(("Building 2"), true)
WebUI.verifyTextPresent(("United States"), true)
WebUI.verifyTextPresent(("CROFTON"), true)
WebUI.verifyTextPresent(("MD"), true)
WebUI.verifyTextPresent(("21114"), true)


