<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CVV</name>
   <tag></tag>
   <elementGuidId>7ad37cfa-b232-443c-9dea-8cd89e8f52a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CVV']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CVV</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a5ebc1ef-78b5-43cd-88d3-9d10f3e52229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CVV</value>
      <webElementGuid>870e3119-2772-4660-88f1-e415edbcba10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CVV</value>
      <webElementGuid>69b70b80-500a-44d3-8855-5112c7fb6fcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>CVV</value>
      <webElementGuid>15e9adab-2f3b-4555-9124-369c1a48ee6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>ffeb2fc0-a225-4ebe-b939-6a0f082f408f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>901aa39f-71a2-4e8f-aac0-db6dd7859b62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>4733828f-542a-495b-b042-a4e4ead36181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>floating__input dpp-input ng-pristine ng-valid ng-touched</value>
      <webElementGuid>055da1ee-c2e6-47e8-b4b6-bdac6f1d81aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>doNotAutoComplete</value>
      <webElementGuid>23ea6933-8bbe-457d-b3a5-b9fdc8142a60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e7d17991-db83-4184-bed8-798dddc26ec8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>236ff4f9-f9a5-426c-bbd7-c6d7282f585d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>370092ab-e2d2-4985-aca3-cf7f39b60fa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CVV&quot;)</value>
      <webElementGuid>5a25e57f-f94e-4486-94db-bc382130fefd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CVV']</value>
      <webElementGuid>4d252a44-361e-450b-8aab-007085c0a080</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapsePaymentInfoArea']/div[4]/div/div/div[3]/div/div/input</value>
      <webElementGuid>0d9cfd06-0f4e-4b68-9155-e2e2e902fa63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[4]/div/div/div[3]/div/div/input</value>
      <webElementGuid>ab5189cb-9103-4c7e-b8d6-66eeb3a86cdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'CVV' and @name = 'CVV' and @type = 'tel']</value>
      <webElementGuid>36c22ae9-4533-4201-af48-3007190dcbb3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
