<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>app_btn_right</name>
   <tag></tag>
   <elementGuidId>13708dad-5d5b-43a3-bc52-4416b49f5f5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'btnRight' and @onclick = concat(&quot;moveSelectedOptions(this.form[&quot; , &quot;'&quot; , &quot;availableApplicationIds&quot; , &quot;'&quot; , &quot;],this.form[&quot; , &quot;'&quot; , &quot;applicationIds&quot; , &quot;'&quot; , &quot;]);&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnRight</value>
      <webElementGuid>feb8ce32-98c8-474c-a2bb-fa19f8edd40d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>moveSelectedOptions(this.form['availableApplicationIds'],this.form['applicationIds']);</value>
      <webElementGuid>4a5f2fdd-c51c-4471-b663-56a4262d3551</webElementGuid>
   </webElementProperties>
</WebElementEntity>
