<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>check_failure_transaction</name>
   <tag></tag>
   <elementGuidId>ab9a46b5-8e3a-4c06-95b3-b7416e11f7ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'includeFailedTransactions' and @type = 'checkbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>includeFailedTransactions</value>
      <webElementGuid>4a446270-8d29-46d2-9243-37604ee5e404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>423de8d2-56bf-4a28-ac1f-6610f9cedbec</webElementGuid>
   </webElementProperties>
</WebElementEntity>
