<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__billLookupForm.lookupValue1</name>
   <tag></tag>
   <elementGuidId>feac0fe5-c6ac-47c0-833b-fe7185508f84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lookupValue1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lookupValue1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7b95e081-12cc-4649-8a61-eb7e853bb1a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>670f0bd2-972b-42f5-8301-66ff90fa7a93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billLookupForm.lookupValue1</value>
      <webElementGuid>f69fb2d1-c3aa-4507-9da9-f4df6b9d37fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>2bcee8c4-ecd7-498a-847f-8a957e7edee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>e2b8c444-4725-4941-a303-821d15a7e5aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lookupValue1</value>
      <webElementGuid>cfc1e277-e1e8-469e-9782-78121533b105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>485lookup1</value>
      <webElementGuid>2491237d-ef59-4685-ba10-d943d2859920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lookupValue1&quot;)</value>
      <webElementGuid>3eb607a0-60cc-44f2-9bdb-989c980af3bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lookupValue1']</value>
      <webElementGuid>72b0d635-0297-4d5e-ae18-b1adce097650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='lookupTr1']/td[2]/input</value>
      <webElementGuid>d1fc92be-5f72-41ed-91c7-529fb25fc432</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>1ef9bfa1-fbc6-4016-bedc-ece8bd578318</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'billLookupForm.lookupValue1' and @id = 'lookupValue1' and @alt = '485lookup1']</value>
      <webElementGuid>0b2c3add-0c53-4450-a009-8869c8684b19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
