<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__billLookupForm.lookupValue3</name>
   <tag></tag>
   <elementGuidId>a8c4cf26-e2d0-480f-afc1-941f047b4aa8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lookupValue3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lookupValue3</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @name = 'billLookupForm.lookupValue3' and @id = 'lookupValue3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3b6c97ea-2218-427f-b1b1-ee08769a3a40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ef4cbb2c-054d-47bf-85a6-9018d5723e31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billLookupForm.lookupValue3</value>
      <webElementGuid>bb673e1e-e605-4862-97c5-15a6d2b4dc50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>00e9a7f1-1ec6-40da-90f1-f63426dc4664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>b457e448-4341-4581-87e0-169ebc2abd55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lookupValue3</value>
      <webElementGuid>adfc9974-628d-459b-a147-3efc35a9c93c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>485lookup3</value>
      <webElementGuid>09bf328f-4bb7-4fc1-9d09-0feabd06378f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lookupValue3&quot;)</value>
      <webElementGuid>8872d7da-7721-44be-836c-80da034ffec3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lookupValue3']</value>
      <webElementGuid>3a146a31-0737-49a1-8d77-187f2b097bdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='lookupTr3']/td[2]/input</value>
      <webElementGuid>612ab0e5-9b5d-48ca-907b-4b836c30b088</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/table/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>e3ae5ffd-dac5-45ed-a4f9-9aa8d944676b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'billLookupForm.lookupValue3' and @id = 'lookupValue3' and @alt = '485lookup3']</value>
      <webElementGuid>b4a76797-33a8-4d48-9b47-ba664b26426a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
