<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__guestBillSubmitBtn</name>
   <tag></tag>
   <elementGuidId>e362f222-4c79-4e97-b40d-f58310538200</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='guestBillSubmitBtn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#guestBillSubmitBtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dbb42d33-d03e-4086-b3ef-f4513733df9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>guestBillSubmitBtn</value>
      <webElementGuid>f911070b-c8f7-494a-bc36-985ece603647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>guestBillSubmitBtn</value>
      <webElementGuid>3895f657-05a8-42cf-ba10-4902b41011fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a6e70a90-00c9-4c13-9a2a-294d65447946</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>guestPaySubmit()</value>
      <webElementGuid>0d3eb430-a8fb-43ae-8c6b-ba398d0f2eb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Pay as a Guest</value>
      <webElementGuid>6d3ce030-03c6-437c-9be4-31c50f7c708f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;guestBillSubmitBtn&quot;)</value>
      <webElementGuid>e0d04413-b891-4531-9d06-efa0ff2384c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='guestBillSubmitBtn']</value>
      <webElementGuid>e8ed76eb-df94-43c1-8210-46f0b9a46dd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='guestBillSubmitBtnDiv']/input[4]</value>
      <webElementGuid>85999afe-5715-4059-bf0a-583fabf553d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input[4]</value>
      <webElementGuid>84d4cb50-9186-4ce8-932e-a253aeb2cc14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'guestBillSubmitBtn' and @name = 'guestBillSubmitBtn' and @type = 'button']</value>
      <webElementGuid>a5164c7d-a206-43db-aab3-07f97678ce2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
