<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_savechanges</name>
   <tag></tag>
   <elementGuidId>89bc85bd-a4b7-483a-a67e-6f38f064e28f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#modifyDiv > input[name=&quot;changePaymentMethodButton&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and @value = 'Save Changes']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='changePaymentMethodButton'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Save Changes&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>560e0532-68a0-411e-85c7-ae2a55845aab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a1269f37-21d5-42f6-8634-c6b135d3e2b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>changePaymentMethodButton</value>
      <webElementGuid>95fe11c7-e0b7-44de-8a0c-9abd1835f510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save Changes</value>
      <webElementGuid>5f35d67c-bb71-4318-a15a-e98e0e28a547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>payor_opt</value>
      <webElementGuid>aab87dc1-b091-41d5-b3ce-a84ab7705cea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>changePaymentModifySubmit();</value>
      <webElementGuid>3588431d-20f5-4de5-a14a-93192b3894fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modifyDiv&quot;)/input[@class=&quot;payor_opt&quot;]</value>
      <webElementGuid>24744b59-eeff-4639-b03b-9a228f3c617d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='changePaymentMethodButton'])[3]</value>
      <webElementGuid>436ddba9-bd8e-4f64-b61e-74714b9feb9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modifyDiv']/input</value>
      <webElementGuid>e1488faa-0d27-4b6d-a617-393b76e41c44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div[3]/input</value>
      <webElementGuid>896c8be0-c051-43bc-a8d0-547e72c90277</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'changePaymentMethodButton']</value>
      <webElementGuid>07d39106-50b9-49b7-a3cf-5783ed89f699</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
