<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>startDate</name>
   <tag></tag>
   <elementGuidId>9e206cd7-b758-4cdd-a983-d38d56284064</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'startD' and @value = '02/13/2026']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>startD</value>
      <webElementGuid>77ed6a74-e1fe-4abb-863c-138e151d96f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>02/13/2026</value>
      <webElementGuid>bf42a279-5ac3-4e78-aad0-13424a8d098e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
