<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_billingAddress</name>
   <tag></tag>
   <elementGuidId>c385e740-2a11-4e35-b0c2-e53f5993f91b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#billingAddress</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='billingAddress']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c702fc14-8cd2-423a-87a7-47d1d392993e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c7f18130-5ebb-4035-9ca8-26201f6e4f12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>68fb1f68-6f7c-4033-812b-806f185e0891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billingAddress</value>
      <webElementGuid>54bf1a5b-48cf-4935-b069-5a018c51bd4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billingAddress</value>
      <webElementGuid>25793c3c-96e2-4891-bc58-ebfac842f148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Address Line 1</value>
      <webElementGuid>787e41eb-ed7d-44e3-8aa9-a0f274a92e8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>a7bb0ba1-41b9-4cd1-8933-6ed2e2625066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>3dd38cc2-49e3-417d-8748-a33197f486a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>123 Paradise Road</value>
      <webElementGuid>13011e5f-85b6-48db-b9a9-67db23d00ad1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>4c38c461-f9c8-4f6b-9c6c-8a389a776ec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billingAddress&quot;)</value>
      <webElementGuid>78beb1f1-fa4b-4180-b9f3-11a28e3f5bd3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='billingAddress']</value>
      <webElementGuid>a9eb8bee-c703-4a3e-b799-b3fca685d2e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nobr/input</value>
      <webElementGuid>38ba1ac2-2d57-497d-98e0-6a49982774a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'billingAddress' and @id = 'billingAddress' and @alt = 'Address Line 1']</value>
      <webElementGuid>dc4a534f-75eb-4291-b83c-562e4d969e17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
