<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Exit</name>
   <tag></tag>
   <elementGuidId>0dab941b-dbaa-48c1-8d86-bb88a5b5282f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#existButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='existButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e2d4e465-ec2d-4f1e-af4e-922e2ebd551a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d1e4a62d-5112-47b0-a6a6-21d15e6790f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default btn-block</value>
      <webElementGuid>60bb7e9a-e9bf-4c14-9db0-d62577c95bb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>existButton</value>
      <webElementGuid>bc6c4069-455a-4dd9-970c-cdba2c52cb64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>location.href='https://www.dallascounty.org/departments/tax/?remittance_id=dsfdsf43535gghdfg&amp;security_id=ff4f8a709c22d545af2718c7e3e25268&amp;application_id=836';</value>
      <webElementGuid>ae2e8d15-32dc-49fa-9d49-8dc97556f012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Exit</value>
      <webElementGuid>96999d0f-3471-4a3e-bc9b-d4054401cc97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ec058edf-f54c-4de6-a681-6243956ff6f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;existButton&quot;)</value>
      <webElementGuid>92d475a8-d023-4833-8413-f65fbae7f7e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='existButton']</value>
      <webElementGuid>6a789562-0750-476f-9d73-873cfdb45a89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>306e1324-aa2b-4b00-ab01-6b9247910560</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'existButton']</value>
      <webElementGuid>c4ed9baf-9946-43f3-bd84-38c7903ae104</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
