<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_userDefined7</name>
   <tag></tag>
   <elementGuidId>0b4f9d30-f69d-4bea-9fce-5df1a0624ab1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='variableField7DropdownGroupItemID']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;variableField7DropdownGroupItemID&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>15325b3e-f997-4e06-95bd-a19038b49206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>variableField7DropdownGroupItemID</value>
      <webElementGuid>b53397cc-dddf-4d08-a5f4-ff8de0d802fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>84acb5b9-34ee-43cd-9c71-c9ae63cb553c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>UDF7 Label tabindex=</value>
      <webElementGuid>d4b5a3ce-772e-4b70-8354-2e51fff92d11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select One--OrangePurple</value>
      <webElementGuid>adb767e2-2319-405c-ad08-c2710a30baed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;udfcontent&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;form-group&quot;]/select[@class=&quot;form-control&quot;]</value>
      <webElementGuid>95671338-1547-43c6-8815-cc3c3beecb62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='variableField7DropdownGroupItemID']</value>
      <webElementGuid>cf89fe1a-2054-44f1-a947-84678c077111</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='udfcontent']/div/div[6]/div/select</value>
      <webElementGuid>55df64c1-5178-4c9b-a5b5-eda59045611a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UDF7 Label'])[1]/following::select[1]</value>
      <webElementGuid>b0469fcc-97cc-47cd-b21b-43085dc78444</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UDF6 Label'])[1]/following::select[1]</value>
      <webElementGuid>23c52d8c-c6db-4374-8019-d4119d0cedcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[12]/preceding::select[1]</value>
      <webElementGuid>e70e5b74-4999-429c-ba11-f89c1a33aea4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/select</value>
      <webElementGuid>4fd7783d-ef25-4d67-befe-a6c81b9a141f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'variableField7DropdownGroupItemID' and @alt = 'UDF7 Label tabindex=' and (text() = '--Select One--OrangePurple' or . = '--Select One--OrangePurple')]</value>
      <webElementGuid>5647aae1-33fd-4484-9085-352950495193</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
