<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_edit</name>
   <tag></tag>
   <elementGuidId>698a953f-475e-4808-8057-10596d573cc3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='paymentMethod[kk]']/td[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(3) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;edit&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f0ec4c8d-38cb-46f9-a4c0-311bfe816653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:toURL('/vbills/imtiazcustomer/navigatePaymentMethod.go?action=navigate&amp;forgotType=null&amp;id=101555')</value>
      <webElementGuid>5c7935bf-2104-4bfe-8ed0-66b5d5af38a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>edit</value>
      <webElementGuid>91ad91f0-b54e-46ab-97cb-877683aefbea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paymentMethod[kk]&quot;)/td[3]/a[1]</value>
      <webElementGuid>58a4e54d-4c65-4bf3-9e87-cd59e79852e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='paymentMethod[kk]']/td[3]/a</value>
      <webElementGuid>221e14c8-fe58-4312-a171-afb77bddd0b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'edit')]</value>
      <webElementGuid>a2a8a991-b0b5-408c-9ad1-3d3ea4676029</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='edit']/parent::*</value>
      <webElementGuid>5e6424e4-4a4c-4f7e-b85a-74d69f2dfd35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:toURL('/vbills/imtiazcustomer/navigatePaymentMethod.go?action=navigate&amp;forgotType=null&amp;id=101555')&quot;)]</value>
      <webElementGuid>288008c1-5554-443f-a4e4-4a1ee02c0790</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a</value>
      <webElementGuid>6ba25a48-74f8-446e-bdff-3351916c0679</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;javascript:toURL(&quot; , &quot;'&quot; , &quot;/vbills/imtiazcustomer/navigatePaymentMethod.go?action=navigate&amp;forgotType=null&amp;id=101555&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'edit' or . = 'edit')]</value>
      <webElementGuid>dcfbf029-1f3a-4ea0-9a84-8779416ca1b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
