<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__cardNumber</name>
   <tag></tag>
   <elementGuidId>ed63aa0a-e87d-4e93-bc32-2cc277b53044</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cardAccountNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cardAccountNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[alt=&quot;Card Number&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a19849f1-71fa-410d-872f-236740bfd4e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4cf28751-5a66-4ffc-a438-109b9f3c2a9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cardAccountNumber</value>
      <webElementGuid>1a143050-b600-494c-b3e3-81c4de30c85a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>ac20a0f1-36b3-4c58-88d8-5f917d40b986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>ba2e2fbe-1968-4812-82e7-7a47109c1d06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cardAccountNumber</value>
      <webElementGuid>ce554ccb-befd-4399-9305-c9cf8a7ae415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Card Number</value>
      <webElementGuid>36e26930-b7ae-40fa-8584-e44750a143be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cardAccountNumber&quot;)</value>
      <webElementGuid>2b3798ad-4348-4f3e-bc8b-d7aaa1ddf68f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cardAccountNumber']</value>
      <webElementGuid>5b54b9bd-d0b9-4371-972b-aeb4f169d24c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area_creditCard']/table/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>f5b6db9a-30cc-4aab-bbec-678af8cfb004</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/input</value>
      <webElementGuid>b7d95d0c-f669-4e59-8d77-bfd8bfaf6f12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'cardAccountNumber' and @id = 'cardAccountNumber' and @alt = 'Card Number']</value>
      <webElementGuid>798c157c-4657-4097-bb34-fde4a8b1b685</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
