<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Country</name>
   <tag></tag>
   <elementGuidId>1374b4b0-792b-4990-9e69-1ef9f24c5ff6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='countryId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#countryId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#countryId</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>79b20c4d-57fa-4aea-8951-1a0440ea1406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billingAddressForm.countryId</value>
      <webElementGuid>7628d6e9-c25a-4c15-bed8-d63a6f58b34f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>linkageStateAndCountry(this.value)</value>
      <webElementGuid>7f2e7d3f-31c3-474e-a1d9-d494f70a83a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>countryId</value>
      <webElementGuid>9ca5c49e-3d45-421b-9500-473f223ee934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>United States</value>
      <webElementGuid>c72cf4ef-d114-432a-9be4-ab47434f58e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;countryId&quot;)</value>
      <webElementGuid>83f45b94-9fde-4073-80c1-ef5744852ef6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='countryId']</value>
      <webElementGuid>4cc779d7-b3c4-4d9b-805b-d3095c5a0e8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='addressForm']/table/tbody/tr[4]/td[2]/select</value>
      <webElementGuid>2780fa9a-d789-4198-ad5a-8faf9f41d25c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[11]/following::select[1]</value>
      <webElementGuid>e390c214-b5f4-45e6-abb0-c6144eb9e449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country:'])[1]/following::select[1]</value>
      <webElementGuid>d8987a51-8e64-44e6-b369-5f96d209730f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ZIP'])[1]/preceding::select[1]</value>
      <webElementGuid>d65f7752-3dd6-4740-95d3-e5ad1a63b485</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/table/tbody/tr[4]/td[2]/select</value>
      <webElementGuid>0e732c3f-75b3-42f6-93b0-4867650ad14d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'billingAddressForm.countryId' and @id = 'countryId' and (text() = 'United States' or . = 'United States')]</value>
      <webElementGuid>43518149-704d-437b-8bd1-e7d44a753697</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
