<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Year</name>
   <tag></tag>
   <elementGuidId>de791fc2-640d-4bc9-a346-53266477c8c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cardExpireYear']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cardExpireYear</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cardExpireYear</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a9eba919-2c84-4442-82f6-8e932f6d0613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cardExpireYear</value>
      <webElementGuid>7ed7c194-bba8-4064-adec-273b721eb813</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cardExpireYear</value>
      <webElementGuid>1bfac42f-cfa8-4eea-813a-063f241fe88e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Year...
                                    2025
2026
2027
2028
2029
2030
2031
2032
2033
2034
2035
2036
2037
2038
2039</value>
      <webElementGuid>c662d16d-883e-407a-a7f5-52b82d3fc403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cardExpireYear&quot;)</value>
      <webElementGuid>ea6d825f-7f3f-4081-9007-22206ffb706b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cardExpireYear']</value>
      <webElementGuid>97901ebf-4077-45fc-b114-f1560ac43abe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area_creditCard']/table/tbody/tr[4]/td[2]/select[2]</value>
      <webElementGuid>8822b2ce-d3e9-496e-8a8d-a5ac788e030a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::select[2]</value>
      <webElementGuid>edd3992a-d4ec-4c5b-9ba6-70fa5ee0ea86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expiration Date:'])[1]/following::select[2]</value>
      <webElementGuid>9850394b-34cd-409e-b9e6-9f516789b004</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bank Account Information'])[1]/preceding::select[1]</value>
      <webElementGuid>101f8adb-c930-4c37-a17a-8dcfdfe7ebd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company Name:'])[1]/preceding::select[1]</value>
      <webElementGuid>a34fe984-df40-4a77-b1af-83e9d19abd77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[2]</value>
      <webElementGuid>8b9663e4-2ca0-420a-8e15-8ada036b7eb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'cardExpireYear' and @id = 'cardExpireYear' and (text() = 'Year...
                                    2025
2026
2027
2028
2029
2030
2031
2032
2033
2034
2035
2036
2037
2038
2039' or . = 'Year...
                                    2025
2026
2027
2028
2029
2030
2031
2032
2033
2034
2035
2036
2037
2038
2039')]</value>
      <webElementGuid>27899b05-8c54-4774-b4bb-aac992eb4eef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
