<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>edit_payment</name>
   <tag></tag>
   <elementGuidId>f4b39a21-dfc8-4c1c-94ea-b415b4f9c49c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = concat(&quot;javascript:deferredPaymentAction(&quot; , &quot;'&quot; , &quot;edit&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;107714&quot; , &quot;'&quot; , &quot;);&quot;)]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='deferredPaymentHistory']/tbody/tr/td[6]/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;| Edit&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ea46c479-f5fd-4d20-a2f8-c71cc3392fd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:deferredPaymentAction('edit', '107714');</value>
      <webElementGuid>d2198066-34f2-4c0e-9e1d-cf816b0603bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>| Edit </value>
      <webElementGuid>569ee331-e4f6-4ab9-b12c-9f27627bc400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;deferredPaymentHistory&quot;)/tbody[1]/tr[@class=&quot;results-td-odd&quot;]/td[6]/a[2]</value>
      <webElementGuid>86326fc2-4279-4750-960d-bd4197e51140</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='deferredPaymentHistory']/tbody/tr/td[6]/a[2]</value>
      <webElementGuid>0198e79e-3cf4-425c-b8bb-f651496bef5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'| Edit')]</value>
      <webElementGuid>5c3be7b9-776e-4e83-a58f-150b06ea63b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[1]/following::a[1]</value>
      <webElementGuid>2f7c2208-17e3-4296-a43b-2f648000793e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PENDING'])[1]/following::a[2]</value>
      <webElementGuid>4e99874c-ca32-4f39-a4ee-d8e9d92b3b65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='| Cancel'])[1]/preceding::a[1]</value>
      <webElementGuid>38c7c356-98b0-4bf5-8168-7988e2044e50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='| Edit']/parent::*</value>
      <webElementGuid>6df5d8cf-39c7-444a-b98c-ce62f009ed3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:deferredPaymentAction('edit', '107714');&quot;)]</value>
      <webElementGuid>b6b77155-22ba-4a88-b0a9-dac56ad1a7ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>4130f910-453b-4fe1-bf98-3b03b792c72b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;javascript:deferredPaymentAction(&quot; , &quot;'&quot; , &quot;edit&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;107714&quot; , &quot;'&quot; , &quot;);&quot;) and (text() = '| Edit ' or . = '| Edit ')]</value>
      <webElementGuid>0f68e825-39db-49d8-9f79-071a490e699f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
