<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Standard</name>
   <tag></tag>
   <elementGuidId>ac1ed48f-1d1b-4de4-82c9-1d3e28447498</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.btn.btn-secondary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='ReportSubscriptionActionForm']/div/div/div/div/div/div[7]/div[2]/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Standard&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>b163837b-4e2c-4bfd-8c6f-d8f0330e915b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-secondary</value>
      <webElementGuid>dd77bcd3-e3ae-452c-87a5-af929e2e0ad9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>subjectType_Standard</value>
      <webElementGuid>3569a8a6-b8bb-4fd1-ad92-23020eacb8f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Standard</value>
      <webElementGuid>960a73d9-b2be-49f1-ab92-83be5b6bacc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ReportSubscriptionActionForm&quot;)/div[@class=&quot;tile-body&quot;]/div[@class=&quot;px-3&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-8&quot;]/div[@class=&quot;row m-0 mt-3&quot;]/div[@class=&quot;col-md-9  form-inline col-ms-12&quot;]/div[@class=&quot;radio-toolbar&quot;]/label[@class=&quot;btn btn-secondary&quot;]</value>
      <webElementGuid>89672940-7b74-46d1-b98b-59ff152b0cfd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='ReportSubscriptionActionForm']/div/div/div/div/div/div[7]/div[2]/div/label</value>
      <webElementGuid>d4c7fbde-0c81-47e1-a172-9586e5760a84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/following::label[1]</value>
      <webElementGuid>cd3162c7-b013-4827-a4e0-fdbb85ea1b80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Custom'])[1]/preceding::label[1]</value>
      <webElementGuid>1c1e6fb0-3e26-49a8-b593-412e9cc22931</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Standard']/parent::*</value>
      <webElementGuid>155b46dd-e823-4b50-8803-b28ab4ead3a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>059af496-357c-41bb-b8c8-d0d724f2d992</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Standard' or . = 'Standard')]</value>
      <webElementGuid>ce26ef09-9f43-42fe-aaa6-472006f6f074</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
