<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_namelist_Prod</name>
   <tag></tag>
   <elementGuidId>a3dff507-91c4-46e4-8cbe-cbbd1e4a6796</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//select[@id='lstBox1'])[3]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'availableEmailTos']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>select[name=&quot;availableEmailTos&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b6a57710-5fb6-40c6-83e7-1046fc1361a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>availableEmailTos</value>
      <webElementGuid>e7554184-7310-4349-9e46-51f6cdec68cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>multiple</name>
      <type>Main</type>
      <value>multiple</value>
      <webElementGuid>df5811f3-e09f-4137-9f9f-ad2a8d2ed2a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lstBox1</value>
      <webElementGuid>ed99b9f4-fcd8-4847-81a6-38cc7520dc98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>269aa789-4e66-49b4-bfd9-e1e3ed4891ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondblclick</name>
      <type>Main</type>
      <value>moveSelectedOptions(this.form['availableEmailTos'],this.form['emailTos']);</value>
      <webElementGuid>113f0df1-1c0e-476c-bf19-11203300bef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ALICE Wonderland(Aice)Apple IOS(Apple16)Ashu I(Aashu)Ashwity Indurkar(aindurkar)Aurora W(Runaway)AutoUser UserProd(AutoUserProd)Ayesha Kowkab(akowkab2)Case user(CASEuser)FairyQueen Mother(Queen)Jason Bergeron(jasonb)Lance Klusener(Lance60)ModFName ModLName(ToBeModUser)Moh Asif(Asif1)Rahul Dravid(Wall)Roger Federer(federer)Sesame Chawal(Seasame5321)Shane Warne(Warne1000)Susmitha Anganagari(Susmitha1)Viru Sehwag(Sehwag300)change password(changepassword)hack jack(hak20)haris ahmed(hahmed)hi wi(huy12)isat faction(isat)jake blak(jake80)pavneet kaur(pkaur)test dummy(test_dummy)zing 2(Zing)</value>
      <webElementGuid>8a7447ad-323d-4c70-81b0-88a6422cacd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ReportSubscriptionActionForm&quot;)/div[@class=&quot;tile-body&quot;]/div[@class=&quot;px-3&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-8&quot;]/div[@class=&quot;row m-0 mt-3&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;col-md-12  col-ms-12&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;tile w-100 p-0&quot;]/div[@class=&quot;tile-body p-3&quot;]/div[@class=&quot;subject-info-box-1&quot;]/select[@id=&quot;lstBox1&quot;]</value>
      <webElementGuid>42c6fb12-ab5a-4923-a89f-ec70e0ca81bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//select[@id='lstBox1'])[3]</value>
      <webElementGuid>16d76e38-7535-4184-bfef-2e14501651a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='ReportSubscriptionActionForm']/div/div/div/div/div/div[5]/div[2]/div/div/div/div[2]/div/select</value>
      <webElementGuid>1c797c0e-01de-45fe-a654-0ba16cb3c59e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Available :'])[3]/following::select[1]</value>
      <webElementGuid>08f9387e-1b16-41ed-901f-320989ce2c6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Email Address List'])[1]/following::select[1]</value>
      <webElementGuid>9fdb7edd-c5e4-48b5-a403-7426f0307da0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selected :'])[3]/preceding::select[1]</value>
      <webElementGuid>bb416959-5a97-4517-b2fe-eca551c9eddb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/div/div[2]/div/select</value>
      <webElementGuid>c76319a7-4552-48d9-b844-1b4b151a75f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'availableEmailTos' and @id = 'lstBox1' and (text() = 'ALICE Wonderland(Aice)Apple IOS(Apple16)Ashu I(Aashu)Ashwity Indurkar(aindurkar)Aurora W(Runaway)AutoUser UserProd(AutoUserProd)Ayesha Kowkab(akowkab2)Case user(CASEuser)FairyQueen Mother(Queen)Jason Bergeron(jasonb)Lance Klusener(Lance60)ModFName ModLName(ToBeModUser)Moh Asif(Asif1)Rahul Dravid(Wall)Roger Federer(federer)Sesame Chawal(Seasame5321)Shane Warne(Warne1000)Susmitha Anganagari(Susmitha1)Viru Sehwag(Sehwag300)change password(changepassword)hack jack(hak20)haris ahmed(hahmed)hi wi(huy12)isat faction(isat)jake blak(jake80)pavneet kaur(pkaur)test dummy(test_dummy)zing 2(Zing)' or . = 'ALICE Wonderland(Aice)Apple IOS(Apple16)Ashu I(Aashu)Ashwity Indurkar(aindurkar)Aurora W(Runaway)AutoUser UserProd(AutoUserProd)Ayesha Kowkab(akowkab2)Case user(CASEuser)FairyQueen Mother(Queen)Jason Bergeron(jasonb)Lance Klusener(Lance60)ModFName ModLName(ToBeModUser)Moh Asif(Asif1)Rahul Dravid(Wall)Roger Federer(federer)Sesame Chawal(Seasame5321)Shane Warne(Warne1000)Susmitha Anganagari(Susmitha1)Viru Sehwag(Sehwag300)change password(changepassword)hack jack(hak20)haris ahmed(hahmed)hi wi(huy12)isat faction(isat)jake blak(jake80)pavneet kaur(pkaur)test dummy(test_dummy)zing 2(Zing)')]</value>
      <webElementGuid>3308f2fb-38b8-4280-9e47-0eb81f638100</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
