<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Selected_emailTos</name>
   <tag></tag>
   <elementGuidId>b7706ca3-21aa-4bbe-adab-626fe3244303</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//select[@id='lstBox2'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>select[name=&quot;emailTos&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4d969834-ebd3-4c74-9c5a-8a70ad9af54a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>emailTos</value>
      <webElementGuid>61f8d6af-0044-48c3-a835-c6a68c033481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lstBox2</value>
      <webElementGuid>e5fc2202-2e40-486f-975e-3151dda7ee16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9d7b4ed1-640a-4a5d-8988-8c3c4466970f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>multiple</name>
      <type>Main</type>
      <value>multiple</value>
      <webElementGuid>898d4b80-e75f-4b2c-9a00-905c5254cd88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondblclick</name>
      <type>Main</type>
      <value>moveSelectedOptions(this.form['emailTos'],this.form['availableEmailTos']);</value>
      <webElementGuid>a2dfd379-2fbe-4d8b-81d8-d4312d2f68de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ReportSubscriptionActionForm&quot;)/div[@class=&quot;tile-body&quot;]/div[@class=&quot;px-3&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-8&quot;]/div[@class=&quot;row m-0 mt-3&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;col-md-12  col-ms-12&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;tile w-100 p-0&quot;]/div[@class=&quot;tile-body p-3&quot;]/div[@class=&quot;subject-info-box-2&quot;]/select[@id=&quot;lstBox2&quot;]</value>
      <webElementGuid>4f69b919-1ea7-4c99-ae06-81430e027718</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//select[@id='lstBox2'])[3]</value>
      <webElementGuid>9c7d36c5-29b1-4dc1-a279-b83443fe6c14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='ReportSubscriptionActionForm']/div/div/div/div/div/div[5]/div[2]/div/div/div/div[2]/div[3]/select</value>
      <webElementGuid>e5f2ee98-f457-4346-bc16-e6bd5b6f3b38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selected :'])[3]/following::select[1]</value>
      <webElementGuid>f2214898-7fcc-4640-af24-0cf55e66a052</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Available :'])[3]/following::select[2]</value>
      <webElementGuid>d8c5fadf-378a-4ae6-b2a9-3ed465932306</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/preceding::select[1]</value>
      <webElementGuid>1f7c7ad0-f316-46e8-8b6d-00c2b0f4ea42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/div/div[2]/div[3]/select</value>
      <webElementGuid>ccff54da-de29-45d7-a2b3-3d8f3e7d20d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'emailTos' and @id = 'lstBox2']</value>
      <webElementGuid>af41f28b-50ec-4fc5-a213-6e8f42a21526</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
