<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Active Payment Plan Report</name>
   <tag></tag>
   <elementGuidId>ccad21c7-bd1f-48d2-8373-02b86935227a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Operational_Reports18']/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Active Payment Plan Report' or . = 'Active Payment Plan Report')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.report-name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Active Payment Plan Report&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8e04b696-4d16-4222-a231-64b7edc063b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>5cf823c9-0d93-4df4-8baa-b1a3b6a62aad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>f5075d46-e0fd-4e01-87ed-92a6e5198826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/admin/testcustomer/bootstrap/vclerk/reports/activepyplan.do?&amp;reset=true&amp;actionType=operational</value>
      <webElementGuid>a8eb0ecd-4909-4048-91ef-302ba7e50c21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>report-name</value>
      <webElementGuid>2f0adbbb-d6e0-42ee-bda8-23c71035cc19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-original-title</name>
      <type>Main</type>
      <value>View details for all &quot;Pending&quot; and &quot;In Process&quot; payment plans, for a selected payment application.</value>
      <webElementGuid>2fb4ffcc-812e-403d-9852-1c46b75d32bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip208315</value>
      <webElementGuid>e88c7416-9c19-4fcd-a310-831506f67d5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Active Payment Plan Report</value>
      <webElementGuid>0adec6f6-a41c-4141-aebf-b5825f019559</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Operational_Reports18&quot;)/a[@class=&quot;report-name&quot;]</value>
      <webElementGuid>a59b0275-2a4d-448a-b220-7bbe240aa832</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Operational_Reports18']/a</value>
      <webElementGuid>c7e793a1-9ed2-4954-8b77-01d0b1fdd257</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Active Payment Plan Report')]</value>
      <webElementGuid>24a97393-3a9e-4f6a-bec9-732e2f4257ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operational Reports'])[2]/following::a[1]</value>
      <webElementGuid>f4490538-58ad-4a05-842f-171d20b1bf85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IVR Call Metrics'])[1]/following::a[1]</value>
      <webElementGuid>9951718e-82c6-46df-a581-38f4628e0894</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Auto Pay Enrollments Report'])[1]/preceding::a[1]</value>
      <webElementGuid>db00a6d1-0f3a-492b-82c8-c3b11c847ce6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bill Statistics Report'])[1]/preceding::a[2]</value>
      <webElementGuid>d92b7cff-d7ef-4e9c-918f-053f56d4867b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Active Payment Plan Report']/parent::*</value>
      <webElementGuid>91a0923c-d604-452f-8aab-7d1802ad6e0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/admin/testcustomer/bootstrap/vclerk/reports/activepyplan.do?&amp;reset=true&amp;actionType=operational')]</value>
      <webElementGuid>93f513d3-5880-42e5-ac7f-328d06aa9789</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a</value>
      <webElementGuid>3fd9671f-8187-41af-81a7-767fabf558b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/admin/testcustomer/bootstrap/vclerk/reports/activepyplan.do?&amp;reset=true&amp;actionType=operational' and (text() = 'Active Payment Plan Report' or . = 'Active Payment Plan Report')]</value>
      <webElementGuid>094b98e0-2abe-4a0f-9251-15166d1f836e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
