<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Enterprise Transaction Summary Report by Payment Channel</name>
   <tag></tag>
   <elementGuidId>a426ac47-facd-4d0f-800a-e0ce8ee876e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Operational_Reports20']/div/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Enterprise Transaction Summary Report by Payment Channel' or . = 'Enterprise Transaction Summary Report by Payment Channel')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Operational_Reports20 > div.px-3.py-2 > a.report-name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Enterprise Transaction Summary Report by Payment Channel&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>201c6359-664f-4347-b35e-9e771a15489c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>b2ea8198-aa2d-492a-8289-d26ed5aac279</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>dbf1b871-0035-4b53-b835-7858e2198e7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/admin/testcustomer/bootstrap/vclerk/reports/vtreasurerbychannel.do?&amp;reset=true&amp;actionType=operational</value>
      <webElementGuid>3266f5f4-d971-4c2d-8ad6-cda3c9b930d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>report-name</value>
      <webElementGuid>dd6d80ee-ea62-448d-806e-91d45d799f52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-original-title</name>
      <type>Main</type>
      <value>View enterprise-wide processing totals for a given day, week or month, itemized by payment channel.</value>
      <webElementGuid>3ad862b9-d6ac-4616-b4f5-0d45a8d4cdfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip82402</value>
      <webElementGuid>981f7724-b343-434e-9182-940312cc1189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Enterprise Transaction Summary Report by Payment Channel</value>
      <webElementGuid>4c457c82-0fba-41dc-84a6-0b8df34550f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Operational_Reports20&quot;)/div[@class=&quot;px-3 py-2&quot;]/a[@class=&quot;report-name&quot;]</value>
      <webElementGuid>c46e353a-f78e-484c-9b31-df6ee6cb1164</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Operational_Reports20']/div/a</value>
      <webElementGuid>5e7fdae6-7b96-441a-b307-324b208710ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Enterprise Transaction Summary Report by Payment Channel')]</value>
      <webElementGuid>065e5b41-09f7-4a99-b16b-36ee8b1a974c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download Report'])[1]/following::a[1]</value>
      <webElementGuid>ed421b19-7ab7-49ba-8bfe-8b41196dd9e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Profiles Report'])[1]/following::a[2]</value>
      <webElementGuid>e16ba39f-7c7f-4c1a-b65a-0b73bcdb0db8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enterprise Transaction Summary By Tender Type Report'])[1]/preceding::a[1]</value>
      <webElementGuid>1095ac98-0caa-44ee-afc4-c254b92b1232</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enterprise Transaction Summary Report'])[1]/preceding::a[2]</value>
      <webElementGuid>fe8e3b43-e867-43d8-9680-21a042adfc04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Enterprise Transaction Summary Report by Payment Channel']/parent::*</value>
      <webElementGuid>d9aadc79-f75c-48c3-b7aa-6d248c2fcac5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/admin/testcustomer/bootstrap/vclerk/reports/vtreasurerbychannel.do?&amp;reset=true&amp;actionType=operational')]</value>
      <webElementGuid>189588ac-e8f4-4888-8942-cb61804e7acf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/a</value>
      <webElementGuid>92f2c301-23fc-44c0-8a43-13e862d80aee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/admin/testcustomer/bootstrap/vclerk/reports/vtreasurerbychannel.do?&amp;reset=true&amp;actionType=operational' and (text() = 'Enterprise Transaction Summary Report by Payment Channel' or . = 'Enterprise Transaction Summary Report by Payment Channel')]</value>
      <webElementGuid>df86728a-a385-47b1-a11a-75d744c66282</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
