<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Enterprise Transaction Summary Report by Payment Channel</name>
   <tag></tag>
   <elementGuidId>a426ac47-facd-4d0f-800a-e0ce8ee876e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Operational_Reports20 > div.px-3.py-2 > a.report-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Operational_Reports20']/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Enterprise Transaction Summary Report by Payment Channel&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>518e352e-5aea-47f9-82d4-f1bd1e84274b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>88ca50f4-4353-4613-854a-112c11b04656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>5e3b78e1-4582-4f14-8370-e7a5f68079c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/admin/testcustomer/bootstrap/vclerk/reports/vtreasurerbychannel.do?&amp;reset=true&amp;actionType=operational</value>
      <webElementGuid>ce400d6f-82f0-4e08-89f5-4f964c13cdce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>report-name</value>
      <webElementGuid>38c24705-9080-4f9f-bc8c-63e1653d19c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-original-title</name>
      <type>Main</type>
      <value>View enterprise-wide processing totals for a given day, week or month, itemized by payment channel.</value>
      <webElementGuid>fc84f21d-539c-42ac-931c-01832650d5c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip82402</value>
      <webElementGuid>5ebe4352-b39a-4c7c-8dc2-f8675610428c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Enterprise Transaction Summary Report by Payment Channel</value>
      <webElementGuid>8292f07f-3217-4c0a-a174-2433eba72d32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Operational_Reports20&quot;)/div[@class=&quot;px-3 py-2&quot;]/a[@class=&quot;report-name&quot;]</value>
      <webElementGuid>a78825b9-988c-43a3-96da-26f9d5a4ab33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Operational_Reports20']/div/a</value>
      <webElementGuid>0a0807b1-5ca9-4ff1-a5d8-11a2b2ebc27a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Enterprise Transaction Summary Report by Payment Channel')]</value>
      <webElementGuid>84c95388-e8fc-40bb-b8f9-f2d92809fc02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download Report'])[1]/following::a[1]</value>
      <webElementGuid>05ecbbf4-75cb-4579-b22c-b78c4e396ec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Profiles Report'])[1]/following::a[2]</value>
      <webElementGuid>9ec9bd8a-b65d-4fd2-a474-e6b18fa24fc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enterprise Transaction Summary By Tender Type Report'])[1]/preceding::a[1]</value>
      <webElementGuid>3e21a4c3-f16e-43fc-8ea8-7c7aca50885d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enterprise Transaction Summary Report'])[1]/preceding::a[2]</value>
      <webElementGuid>1508101c-01bc-458b-bffc-c83280915ad6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Enterprise Transaction Summary Report by Payment Channel']/parent::*</value>
      <webElementGuid>dfbef6af-f69c-40a9-b693-cfdec7d14fdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/admin/testcustomer/bootstrap/vclerk/reports/vtreasurerbychannel.do?&amp;reset=true&amp;actionType=operational')]</value>
      <webElementGuid>93ec7f93-5b52-4802-add4-399a552132ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/a</value>
      <webElementGuid>00fb6af9-411c-4f2b-9ad8-6a42900d01bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/admin/testcustomer/bootstrap/vclerk/reports/vtreasurerbychannel.do?&amp;reset=true&amp;actionType=operational' and (text() = 'Enterprise Transaction Summary Report by Payment Channel' or . = 'Enterprise Transaction Summary Report by Payment Channel')]</value>
      <webElementGuid>31f9e715-533f-4cbd-9481-25e941314c85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
