<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Real Time Monitor Report</name>
   <tag></tag>
   <elementGuidId>86edae3e-576b-412c-9109-b78fc6265a23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Real_Time_Monitor > div.px-3.py-2 > a.report-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Real_Time_Monitor']/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Real Time Monitor Report&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e9adb119-b695-4897-86eb-7cc8b02f5291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>9071ebf6-4198-48fb-bb21-7f3a8f5a2010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>243f144c-ca30-4a21-80e6-9b06d9c4da48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/admin/testcustomer/bootstrap/vclerk/reports/realtimemonitor.do?&amp;reset=true&amp;actionType=operational</value>
      <webElementGuid>1a401f50-f064-4c20-ab0a-a6e87ff7cdbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>report-name</value>
      <webElementGuid>e0e5fef6-ffb7-4252-95cb-b25e24b9ff89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-original-title</name>
      <type>Main</type>
      <value>Real Time Monitor Displays 25 Most Recent Transactions</value>
      <webElementGuid>bdd04e74-c8b1-465d-93a1-320047873f40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip804749</value>
      <webElementGuid>dacd4466-a941-4f05-8006-062e0982a321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Real Time Monitor Report</value>
      <webElementGuid>16838c07-9f23-47ca-b85c-6e1fe68f6e8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Real_Time_Monitor&quot;)/div[@class=&quot;px-3 py-2&quot;]/a[@class=&quot;report-name&quot;]</value>
      <webElementGuid>fc5e373f-b16f-48a3-bf18-6e9755e956b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Real_Time_Monitor']/div/a</value>
      <webElementGuid>fbbfb066-9b26-4089-96e7-4d8b6b81a113</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Real Time Monitor Report')]</value>
      <webElementGuid>b0d4ee0a-350a-46b4-8acd-e8a97bfaec66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transaction Summary Report'])[1]/following::a[1]</value>
      <webElementGuid>606869e3-2c47-4858-a53c-2de0d534aa1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transaction Activity Report'])[1]/following::a[2]</value>
      <webElementGuid>bc2394da-fff4-4cd6-840e-4534aaaa8f32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Real Time Monitor Report']/parent::*</value>
      <webElementGuid>93faf79e-6ffe-4e98-b060-305842c6f978</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/admin/testcustomer/bootstrap/vclerk/reports/realtimemonitor.do?&amp;reset=true&amp;actionType=operational')]</value>
      <webElementGuid>57b1928a-e73e-4eda-8edc-650404003df0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[21]/div/a</value>
      <webElementGuid>bfe570e5-1dc0-4928-92f6-1bc6290adf5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/admin/testcustomer/bootstrap/vclerk/reports/realtimemonitor.do?&amp;reset=true&amp;actionType=operational' and (text() = 'Real Time Monitor Report' or . = 'Real Time Monitor Report')]</value>
      <webElementGuid>baa984a0-8598-49be-8546-6b444c620e43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
