<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Scheduled Payments Report</name>
   <tag></tag>
   <elementGuidId>2f3b4e79-6f51-4bb4-9351-ed705cf734ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Operational_Reports13 > div.px-3.py-2 > a.report-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Operational_Reports13']/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Scheduled Payments Report&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>325e37f0-3f77-4969-9098-8e4bccd7dc04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>00f7c197-1542-4c0e-b7af-689f32ef7d20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>d7d7c723-7b08-40dd-8aaf-f7d0d484bab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/admin/testcustomer/bootstrap/vclerk/reports/schedpymtsrpt.do?&amp;reset=true&amp;actionType=operational</value>
      <webElementGuid>293062f1-0948-4ed8-a8e1-9679acf6d57b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>report-name</value>
      <webElementGuid>5a2d0249-9130-467c-8673-46948c8b2868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-original-title</name>
      <type>Main</type>
      <value>View your anticipated cash flow information, by process date, for one-time, future-dated transactions and recurring payment plans.</value>
      <webElementGuid>bcf0896d-b42d-44dc-a739-4a080da29102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip10886</value>
      <webElementGuid>74c35ba1-0f59-4b86-9d7c-ac2c8dae3b97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Scheduled Payments Report</value>
      <webElementGuid>3b205d94-8486-4b87-ada6-3b3994f27382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Operational_Reports13&quot;)/div[@class=&quot;px-3 py-2&quot;]/a[@class=&quot;report-name&quot;]</value>
      <webElementGuid>4f410780-3439-4da4-aa11-5ef47cfe0f72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Operational_Reports13']/div/a</value>
      <webElementGuid>d53a8e81-e462-4a43-818a-e4e9cf36bd5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Scheduled Payments Report')]</value>
      <webElementGuid>e63365b2-4349-4609-8e6c-e1e8895d73a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QuickBooks Integration'])[1]/following::a[1]</value>
      <webElementGuid>40ff7ddf-0f4a-4876-8be4-8b680648ec86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Posting File Report'])[1]/following::a[2]</value>
      <webElementGuid>f1b5ac2b-dd90-4bcb-b9b5-bbc8f0ce39bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Settlement Batch Activity Report'])[1]/preceding::a[1]</value>
      <webElementGuid>b57db918-364c-4548-bfb0-99f80b84604f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transaction Activity Report'])[1]/preceding::a[2]</value>
      <webElementGuid>9e23b1cf-182d-4262-8d83-c730de9f9c53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Scheduled Payments Report']/parent::*</value>
      <webElementGuid>97f6a11c-7032-42f6-9a5e-68b8222bf333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/admin/testcustomer/bootstrap/vclerk/reports/schedpymtsrpt.do?&amp;reset=true&amp;actionType=operational')]</value>
      <webElementGuid>a5731e16-64bd-477f-ac14-7c98c4668970</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/div/a</value>
      <webElementGuid>d6436436-e8cd-48b8-a5fb-2a2e14f572bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/admin/testcustomer/bootstrap/vclerk/reports/schedpymtsrpt.do?&amp;reset=true&amp;actionType=operational' and (text() = 'Scheduled Payments Report' or . = 'Scheduled Payments Report')]</value>
      <webElementGuid>1fd8da80-a68e-49b6-8bbb-abec240c26db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
