<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_close</name>
   <tag></tag>
   <elementGuidId>f97b2ad8-d696-43c9-beb1-e35e5847b8e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Close' or . = 'Close') and @class = 'velocity-default']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>cce9fdb2-40ff-4bef-b69d-6d31dc75355c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>velocity-default</value>
      <webElementGuid>4c71487a-61d8-4887-a46f-16f43bd3bba8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
