<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Country</name>
   <tag></tag>
   <elementGuidId>8a667223-feff-4523-8436-92752a40a03a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#billing-country-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='billing-country-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#billing-country-input</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f1cb4854-e62c-4925-b653-9dc6af6183cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>496d1286-3d22-4860-8ffa-8f1e85b41b5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billingCountry</value>
      <webElementGuid>35c6a07a-c565-4ab0-9045-2d9d5f3f5b60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billing-country-input</value>
      <webElementGuid>5dee4900-354a-4a8d-8408-b4be07ad1f91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>e051c1ba-8fc0-4d38-9963-ce0744b6e1cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
		            		United States
		            	</value>
      <webElementGuid>1ad97def-16f6-4a8b-8b57-eb36d62f2fee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billing-country-input&quot;)</value>
      <webElementGuid>79c43551-e3ed-4e17-a377-3cf92e2cf9c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='billing-country-input']</value>
      <webElementGuid>78fba3af-3daf-4fec-af7a-d1aaba6b6845</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='velocityForm']/div/div[8]/div[4]/select</value>
      <webElementGuid>c032db8f-9fce-4567-9cce-a963ef2e35e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[19]/following::select[1]</value>
      <webElementGuid>c7ab328c-578b-4a1c-931b-aac288bad5e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[20]/preceding::select[1]</value>
      <webElementGuid>dd5ec381-cf68-48de-9268-65d895344539</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[4]/select</value>
      <webElementGuid>f42df9b2-1a7a-45b8-8409-43a7192dab42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'billingCountry' and @id = 'billing-country-input' and (text() = '
		            		United States
		            	' or . = '
		            		United States
		            	')]</value>
      <webElementGuid>00de1053-5d1a-466c-be85-cb35ef1bad4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
