<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_billingAddress</name>
   <tag></tag>
   <elementGuidId>bd94e84d-7a99-48cc-bb51-fe073f69b8a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#billingAddress</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='billingAddress']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d961c6cf-3d9d-414c-b8d3-e3bf77c93c53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>939f239a-fb93-4a4f-ae03-9b278cd2875e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>cfddcdf9-3bb3-43d5-8dc9-739405054731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billingAddress</value>
      <webElementGuid>ef1230be-2f4b-4c95-998d-32789fdcbf15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billingAddress</value>
      <webElementGuid>f9cd3dae-e6d9-4d55-9dd8-bdaa1bf877ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Address Line 1</value>
      <webElementGuid>3132b0d0-8732-4373-9938-294e58e1a711</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>37d345ba-5e9c-4cb6-a4b7-472b72202ebf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>becae32a-57e7-4efd-aefc-f134321324b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2508 Mandan Terrace</value>
      <webElementGuid>ae0ffe10-780e-4c11-b220-1ffd06e50e02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>3708f4ea-8538-4196-b30d-a59da735d3d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billingAddress&quot;)</value>
      <webElementGuid>e7c4ac91-3ffa-4062-8134-d55672d5ab0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='billingAddress']</value>
      <webElementGuid>a2871e66-d23c-49fd-9d90-cf7f624588cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='process']/div/div/div[5]/div/div/input</value>
      <webElementGuid>e459aea0-cf38-4c5b-97cd-fb8651e88727</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/input</value>
      <webElementGuid>1c671487-5969-41aa-9c30-90e5db2ef4ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'billingAddress' and @name = 'billingAddress' and @alt = 'Address Line 1']</value>
      <webElementGuid>0d1c86bb-307d-4fda-8585-e8d5594b0a49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
