<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Submit</name>
   <tag></tag>
   <elementGuidId>ec499c2a-5ba7-4173-b361-601825ceec1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;feeLookupForm&quot;]/div[4]/button[count(. | //*[@class = 'submit-btn']) = count(//*[@class = 'submit-btn'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>submit-btn</value>
      <webElementGuid>9fc9de45-7d14-4de4-9ace-b612e16334f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;feeLookupForm&quot;]/div[4]/button</value>
      <webElementGuid>71317f3a-2b1b-48c1-a016-443498996a40</webElementGuid>
   </webElementProperties>
</WebElementEntity>
