<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>UserDefinedField1Info</name>
   <tag></tag>
   <elementGuidId>d767d3d6-4ac2-4d67-93c4-98c180f23e7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;opalConfirm&quot;]/div/div[5]/div[2]/div/div[2]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;opalConfirm&quot;]/div/div[5]/div[2]/div/div[2]/div[2]</value>
      <webElementGuid>96bfc924-99d5-4c97-b1ba-ce9c8088324c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
