<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__billDetailForms0.payAmount</name>
   <tag></tag>
   <elementGuidId>599fd3e2-8427-47c3-b47c-3b1236aad0b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @name = 'billDetailForms[0].payAmount' and @id = 'payAmount1']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='payAmount1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#payAmount1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7c035e32-0ee0-4f17-980c-a7db98e4e76e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b3a75fcf-8b38-4e2c-a0ee-412782949073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billDetailForms[0].payAmount</value>
      <webElementGuid>3ad6569d-9e61-4a34-96c2-f11a140531ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>442c6f45-5bbd-4dee-8674-c4da70328af2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>3fa31349-207e-47a5-a403-b7770e8ec5f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0.00</value>
      <webElementGuid>d32a5b2b-f03e-46de-bb9a-197eb2be4fab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>resetCheckbox(this, 'payCheckbox1', 'false', 'amountDue1', 'false');</value>
      <webElementGuid>2368ba90-dc30-41ad-8ec8-25a4f7533a85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payAmount1</value>
      <webElementGuid>a13a4114-f478-44b2-bf47-55940630cab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Amount to Pay</value>
      <webElementGuid>b718333c-4b8a-4635-adfb-6bb3e1a25133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payAmount1&quot;)</value>
      <webElementGuid>0801af23-3720-4465-a85b-46a5173b42c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='payAmount1']</value>
      <webElementGuid>ca1abf28-11a8-44d8-a949-e8700490f5b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='tr1']/td[6]/input</value>
      <webElementGuid>e9dddbb5-0593-4e44-aff9-2399490f36cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/input</value>
      <webElementGuid>28f16d3c-7514-4bdc-97d3-590bc2d940f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'billDetailForms[0].payAmount' and @id = 'payAmount1' and @alt = 'Amount to Pay']</value>
      <webElementGuid>f46a83be-6200-41c7-8d50-3e1d8ff3e526</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
