<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Action</name>
   <tag></tag>
   <elementGuidId>d69fa90e-9818-43e0-aea7-5ba410ba7c2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#config_configForm_action_type</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='config_configForm_action_type']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#config_configForm_action_type</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>75b38f5f-e660-40a5-9c5e-1de8a69028cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>71cf520c-f077-47cb-a52b-358b7f414fc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>configForm.action_type</value>
      <webElementGuid>e11d7c68-a5e0-45c9-999d-e65a2c5b8df7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>3df6363b-7a63-49cf-9a74-8ff0d9e7f5f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Paynow</value>
      <webElementGuid>a230adbb-df63-452e-9e7d-576b1c296695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>config_configForm_action_type</value>
      <webElementGuid>1bfd62c9-6794-40a5-8cba-60b683bda56a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;config_configForm_action_type&quot;)</value>
      <webElementGuid>d4834a72-b43f-4feb-9cda-e31c130215f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='config_configForm_action_type']</value>
      <webElementGuid>b786d951-0a4e-4060-9617-4fb959251b5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[2]/input</value>
      <webElementGuid>af0124d1-92b1-46f5-91cb-e5d7ec50bd7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'configForm.action_type' and @id = 'config_configForm_action_type']</value>
      <webElementGuid>42279746-56ed-46fe-ad80-c5b648c71403</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
