<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Company</name>
   <tag></tag>
   <elementGuidId>f7bdbc65-6d64-478d-87a5-22fdb4703ca9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#config_configForm_billing_companyname</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='config_configForm_billing_companyname']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#config_configForm_billing_companyname</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>89209ee9-f8c1-454d-87e8-4fd16255797c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1f8204dc-97a5-4f81-a57e-dd662c172f8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>configForm.billing_companyname</value>
      <webElementGuid>03187b78-1a99-469d-b41a-aae1068f94bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>0adadf6a-9829-4e26-9ce2-d3bd7a2df55e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>config_configForm_billing_companyname</value>
      <webElementGuid>88b0ece3-b6ca-4ac2-b8a1-fe123c512258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;config_configForm_billing_companyname&quot;)</value>
      <webElementGuid>e3e98083-9c0b-433f-b8bc-f0d6d01e12cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='config_configForm_billing_companyname']</value>
      <webElementGuid>723f1943-ccd6-4841-9440-1bf87448f475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[18]/td[2]/input</value>
      <webElementGuid>27f53403-2710-44e8-99ac-3847c7f416b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'configForm.billing_companyname' and @id = 'config_configForm_billing_companyname']</value>
      <webElementGuid>24c4b49f-33b1-4856-8753-f8dc433e860b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
