<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Email</name>
   <tag></tag>
   <elementGuidId>736b6ee2-7651-41bd-9a58-b0f68cfa164d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#config_configForm_email_address</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='config_configForm_email_address']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#config_configForm_email_address</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5434e90f-ecc1-472c-88c6-32516418701a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>800943e2-9774-49cc-af83-74e9f2b2105e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>configForm.email_address</value>
      <webElementGuid>e64932a2-bb29-4448-9c2e-ed81b01cbc90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>167e9d20-4332-4796-95de-2be7beb0fec8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>agency@test.com</value>
      <webElementGuid>9270fcb7-67e8-4b57-94eb-5bb749f46715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>config_configForm_email_address</value>
      <webElementGuid>d0914c31-d0f8-47f9-8ab5-14dbb352bb46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;config_configForm_email_address&quot;)</value>
      <webElementGuid>868ec9f0-3d60-4d37-941a-170496572b1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='config_configForm_email_address']</value>
      <webElementGuid>0a3cbd6c-7f01-430f-8b84-c6de68223b52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[19]/td[2]/input</value>
      <webElementGuid>518d3824-5c80-43c5-8bed-f846b8da00f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'configForm.email_address' and @id = 'config_configForm_email_address']</value>
      <webElementGuid>1201d771-f469-4e95-a572-791bbf3d8c32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
