<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MV</name>
   <tag></tag>
   <elementGuidId>6d087bca-2b83-48b8-9277-4b9ccb2d75a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#config_configForm_message_version</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='config_configForm_message_version']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#config_configForm_message_version</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>16d2b218-15c8-4a84-be60-12d8d61f0157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>configForm.message_version</value>
      <webElementGuid>96586e94-b655-4281-9ef8-adf275ee71c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>config_configForm_message_version</value>
      <webElementGuid>25f3d81a-3a33-405b-86fc-26769e9d50dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>changeMessageVersion(this.value)</value>
      <webElementGuid>237dc30d-94da-40f8-8e31-28f2b92ef9e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
    2.1
    2.2
    2.3
    2.5
    2.7
    3.0
</value>
      <webElementGuid>203afa57-181b-4463-b341-65af4fa5d352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;config_configForm_message_version&quot;)</value>
      <webElementGuid>518b5619-dea6-4d74-bf17-58a62eb06774</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='config_configForm_message_version']</value>
      <webElementGuid>64282cba-8721-446a-8627-62a90a0704bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Message Version'])[1]/following::select[1]</value>
      <webElementGuid>6b2c297d-fa57-44c2-943a-3b18a84daee1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Input Editor'])[2]/following::select[1]</value>
      <webElementGuid>b170732a-a953-47f5-ab64-6714de7e48e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amount'])[1]/preceding::select[1]</value>
      <webElementGuid>bf0f3fe6-3ada-4db1-be90-d037c0cb3ae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Account Number'])[1]/preceding::select[1]</value>
      <webElementGuid>4f3f6096-dc21-4562-b641-d4f3afdcb2ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>f6dce256-60fe-4668-b7b7-0a0d68b28e4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'configForm.message_version' and @id = 'config_configForm_message_version' and (text() = '
    2.1
    2.2
    2.3
    2.5
    2.7
    3.0
' or . = '
    2.1
    2.2
    2.3
    2.5
    2.7
    3.0
')]</value>
      <webElementGuid>128e1d07-2f50-4422-8404-0b91a127ff9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
