<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Administrator</name>
   <tag></tag>
   <elementGuidId>03e2d097-48d7-440e-9f93-26fb4e4807a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@type='button'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Administrator&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b2939309-54e0-46e1-b215-aca36d9e0607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>30250cb2-7867-4764-b329-3640e2e442cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-show</value>
      <webElementGuid>150ffae7-caaa-437a-aaaa-a23384ea6a84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Administrator</value>
      <webElementGuid>aafbaae1-fa43-4dd9-9c94-64ae758bbe53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loadRoles&quot;)/tr[@class=&quot;odd&quot;]/td[1]/div[@class=&quot;btn-group dropright pl-2&quot;]/div[@class=&quot;dropdown-show&quot;]</value>
      <webElementGuid>16d2dd54-2a18-48fb-84eb-3fa48cfd0d64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@type='button'])[3]</value>
      <webElementGuid>693af6e4-9384-40ac-850d-1c084c9f1426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='loadRoles']/tr[3]/td/div/div</value>
      <webElementGuid>c1a35bf1-e1c6-4a1c-bfaf-5f1737742e36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='abc4'])[1]/following::div[3]</value>
      <webElementGuid>cc775285-9758-40b1-adc5-c2fe6e669208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='abc'])[1]/following::div[6]</value>
      <webElementGuid>d0d1c2ec-b61f-493e-9882-0e904f649dc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nikki Edmund'])[1]/preceding::div[1]</value>
      <webElementGuid>dac63800-24b1-4896-a938-4bf9296e4544</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deven Majkowski'])[1]/preceding::div[1]</value>
      <webElementGuid>67f8aab5-86b3-45a5-b795-1256ee6e6dd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Administrator']/parent::*</value>
      <webElementGuid>3711db17-ddf4-48a7-a3a6-78c13f99a700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/div/div</value>
      <webElementGuid>29145698-2219-4023-83be-d835f96875de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@type = 'button' and (text() = 'Administrator' or . = 'Administrator')]</value>
      <webElementGuid>a73a9e65-689d-4470-a4de-3025ebf2f870</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
