<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Active Payment Plan Report</name>
   <tag></tag>
   <elementGuidId>373042df-9ac7-4d41-8b49-934e7ca6d6b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Operational_Reports18']/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Active Payment Plan Report' or . = 'Active Payment Plan Report')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.report-name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Active Payment Plan Report&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>72876243-db6c-48ec-a169-dbaa376b0dc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>6e88108c-0d56-48ce-a74b-e743426f2937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>6fbe41c2-028b-4a18-8dff-04a0bdc2dac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/admin/testcustomer/bootstrap/vclerk/reports/activepyplan.do?&amp;reset=true&amp;actionType=all</value>
      <webElementGuid>cf7f6853-3230-4e8f-aa28-ad847457696f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>report-name</value>
      <webElementGuid>bfe2958f-e49b-49d4-89e3-5e771c560a1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-original-title</name>
      <type>Main</type>
      <value>View details for all &quot;Pending&quot; and &quot;In Process&quot; payment plans, for a selected payment application.</value>
      <webElementGuid>83307de3-1572-43a2-ba05-37223e910bfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip52954</value>
      <webElementGuid>effbd2b4-dae2-401e-a8e4-f2f971a240c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Active Payment Plan Report</value>
      <webElementGuid>987771a8-11a8-4467-91a2-329e3bddbd9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Operational_Reports18&quot;)/a[@class=&quot;report-name&quot;]</value>
      <webElementGuid>a1ec556e-ae08-437a-9cc6-97dd187fda0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Operational_Reports18']/a</value>
      <webElementGuid>b8fbf444-0263-4eea-a5c2-91d58f0c1e8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Active Payment Plan Report')]</value>
      <webElementGuid>6b8c7fd4-4576-4a67-b1af-7c059be48cd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Online Reporting'])[1]/following::a[1]</value>
      <webElementGuid>dc23ae9f-8f27-43db-9c7a-651ee4826c67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IVR Call Metrics'])[1]/following::a[1]</value>
      <webElementGuid>2b68c317-0a4a-40e9-8a51-4c71ea9bfcd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Auto Pay Enrollments Report'])[1]/preceding::a[1]</value>
      <webElementGuid>852ed26f-1f84-4cf7-a4bd-ab59588ad71d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bill Statistics Report'])[1]/preceding::a[2]</value>
      <webElementGuid>c02d8326-b93b-4b98-8f9f-7476fa51cd30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Active Payment Plan Report']/parent::*</value>
      <webElementGuid>c76fcdb2-ce29-44f1-b642-5c04ae8a01de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/admin/testcustomer/bootstrap/vclerk/reports/activepyplan.do?&amp;reset=true&amp;actionType=all')]</value>
      <webElementGuid>6f3383ae-8921-45aa-840c-cfb55dd8f1e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a</value>
      <webElementGuid>6440ae6a-0baa-4f29-ac13-d54383f28a04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/admin/testcustomer/bootstrap/vclerk/reports/activepyplan.do?&amp;reset=true&amp;actionType=all' and (text() = 'Active Payment Plan Report' or . = 'Active Payment Plan Report')]</value>
      <webElementGuid>c2e03ec0-0f95-497e-a838-f3d6111fd214</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
