<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Bill Statistics Report</name>
   <tag></tag>
   <elementGuidId>99d6648f-5814-40a7-b72f-6a92fad38f72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Operational_Reports2']/div/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Bill Statistics Report' or . = 'Bill Statistics Report')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Operational_Reports2 > div.px-3.py-2 > a.report-name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Bill Statistics Report&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>82607ca0-e0c3-49d9-9c6b-663f9349c8ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>ec4854f5-d304-4d4f-8297-8b18dbd10df5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>5ed28c3e-1fc6-4ba5-b894-2660e43caf47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/admin/testcustomer/bootstrap/vclerk/reports/billStatistics.do?&amp;reset=true&amp;actionType=all</value>
      <webElementGuid>df9afb3d-0f19-4b83-85cb-8a3cddb79d99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>report-name</value>
      <webElementGuid>7849461b-7966-4b9c-afae-9e323cec3bee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-original-title</name>
      <type>Main</type>
      <value>View customer profile creation and bill opt out statistics for your Enrolled v+Bills customers.</value>
      <webElementGuid>9398607f-9369-4cd3-8a25-c833fb7562c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip423134</value>
      <webElementGuid>6ca98292-2f7c-4f4a-9acf-c8a2d634b6c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bill Statistics Report</value>
      <webElementGuid>90fc34ab-f7fc-4c34-8a53-b716203aedfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Operational_Reports2&quot;)/div[@class=&quot;px-3 py-2&quot;]/a[@class=&quot;report-name&quot;]</value>
      <webElementGuid>cbc53dc9-bc93-49ec-bda5-662afdd4b724</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Operational_Reports2']/div/a</value>
      <webElementGuid>1243f852-3a82-4837-afc7-aa4e7ca67009</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Bill Statistics Report')]</value>
      <webElementGuid>dec2f55d-2a6a-4b8f-bcde-ff9fa98877cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Auto Pay Enrollments Report'])[1]/following::a[1]</value>
      <webElementGuid>f242defb-a152-4f6e-9354-d291bcc79cc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active Payment Plan Report'])[1]/following::a[2]</value>
      <webElementGuid>0e229b21-60bf-4d52-a729-f0045cb70902</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Profiles Report'])[1]/preceding::a[1]</value>
      <webElementGuid>975953ef-aad3-4a43-babb-74e55536b20c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download Report'])[1]/preceding::a[2]</value>
      <webElementGuid>9343113f-002f-4379-9f7c-f960269a776e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bill Statistics Report']/parent::*</value>
      <webElementGuid>8eb57f4e-45e0-45ad-8f9e-97be39aeab28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/admin/testcustomer/bootstrap/vclerk/reports/billStatistics.do?&amp;reset=true&amp;actionType=all')]</value>
      <webElementGuid>076c5dc4-8e92-4704-9c2f-8d64e15af46f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a</value>
      <webElementGuid>d248c3bf-2d31-4c24-8042-259ce965a038</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/admin/testcustomer/bootstrap/vclerk/reports/billStatistics.do?&amp;reset=true&amp;actionType=all' and (text() = 'Bill Statistics Report' or . = 'Bill Statistics Report')]</value>
      <webElementGuid>f008334d-a533-4abe-a89b-25ce2b309edc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
