<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Online Check Returns Report</name>
   <tag></tag>
   <elementGuidId>494dd967-52f8-4c93-86f8-3546998fcd57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Operational_Reports8']/div/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Online Check Returns Report' or . = 'Online Check Returns Report')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Operational_Reports8 > div.px-3.py-2 > a.report-name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Online Check Returns Report&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dc300b09-9c05-4bf6-89e6-182db7959321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>e50921f7-9010-401b-bbd3-29ec421f00a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>408c0068-0a6b-4fe5-9964-b6246afd3dba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/admin/testcustomer/bootstrap/vclerk/reports/achreturns.do?&amp;reset=true&amp;actionType=all</value>
      <webElementGuid>82d8eb32-4d89-4f56-8e17-7e337f7b566c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>report-name</value>
      <webElementGuid>c922e336-a244-4449-8a69-a2cf7c8ce562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-original-title</name>
      <type>Main</type>
      <value>View returned online check payments.</value>
      <webElementGuid>8427806b-965f-4761-bdaf-06c37d3f684c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip52011</value>
      <webElementGuid>056a54cf-a77c-4668-9f91-4bddbdba17fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Online Check Returns Report</value>
      <webElementGuid>2ef4a0a6-491e-4726-8ef3-1f14163c962f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Operational_Reports8&quot;)/div[@class=&quot;px-3 py-2&quot;]/a[@class=&quot;report-name&quot;]</value>
      <webElementGuid>46bb1300-e2b6-4643-bb33-7e3448e6eb4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Operational_Reports8']/div/a</value>
      <webElementGuid>fc0e501e-a14e-4a04-8a31-15c9019bc825</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Online Check Returns Report')]</value>
      <webElementGuid>0cb32f70-a1cc-488d-90f6-8608ea1cc197</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='File Upload Report'])[1]/following::a[1]</value>
      <webElementGuid>faf266ab-a499-4c40-a992-e3db977ce794</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exceptions Report'])[1]/following::a[2]</value>
      <webElementGuid>d1bc890a-846d-4ba1-88d5-d4b4c32b1d8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Parcels Report'])[1]/preceding::a[1]</value>
      <webElementGuid>4adc71e1-0e5d-4679-a9c7-e04b2191ebb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment Account Activity Report'])[1]/preceding::a[2]</value>
      <webElementGuid>55ada93f-bcd3-4b33-81e7-1c4e21b67652</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Online Check Returns Report']/parent::*</value>
      <webElementGuid>48b6e17f-5561-49f8-bfdb-1f0b3d822be1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/admin/testcustomer/bootstrap/vclerk/reports/achreturns.do?&amp;reset=true&amp;actionType=all')]</value>
      <webElementGuid>0e8d8346-9b48-4473-974a-fafc496eefab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/a</value>
      <webElementGuid>f2701260-71be-4216-a987-66f9491b731c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/admin/testcustomer/bootstrap/vclerk/reports/achreturns.do?&amp;reset=true&amp;actionType=all' and (text() = 'Online Check Returns Report' or . = 'Online Check Returns Report')]</value>
      <webElementGuid>a9694694-c18b-4fe2-8601-f7284270cf3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
