<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Payment Account Activity Report</name>
   <tag></tag>
   <elementGuidId>bbe4ec6c-04d6-4b93-a9eb-11a3c99137ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Operational_Reports9 > div.px-3.py-2 > a.report-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Operational_Reports9']/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Payment Account Activity Report&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3b2f6cd0-19af-4b50-be1d-2406722a728d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>a8e5edfc-e970-4d2e-90e8-f3123d23d437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>ac3d99aa-0e20-404a-9881-653fd619eab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/admin/testcustomer/bootstrap/vclerk/reports/pymtacct.do?&amp;reset=true&amp;actionType=all</value>
      <webElementGuid>be12d699-70e2-40cd-bc05-9750401a7530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>report-name</value>
      <webElementGuid>627830b5-72a4-44d2-ad63-aabc1368af3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-original-title</name>
      <type>Main</type>
      <value>View and examine the activity for a given payment account (e.g. bill number or account number) to determine if payment has been received or to compare against your accounts receivables system.</value>
      <webElementGuid>93bc47e5-7a4d-4702-9d0e-ce8daf875a93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip496910</value>
      <webElementGuid>2c003140-f855-4445-b26e-cd6d57b4afe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Payment Account Activity Report</value>
      <webElementGuid>4e555b84-ebcc-4845-a8a1-aafc84a69392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Operational_Reports9&quot;)/div[@class=&quot;px-3 py-2&quot;]/a[@class=&quot;report-name&quot;]</value>
      <webElementGuid>6ca86b9f-8521-4c45-9d62-c134fce017a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Operational_Reports9']/div/a</value>
      <webElementGuid>086e224f-3dd9-4028-8fbe-712fef2358c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Payment Account Activity Report')]</value>
      <webElementGuid>15c19edb-0ee2-4e39-b23d-1e366d3d9938</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Parcels Report'])[1]/following::a[1]</value>
      <webElementGuid>f90d14ec-1175-4541-882b-96781373a7c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Online Check Returns Report'])[1]/following::a[2]</value>
      <webElementGuid>4fb0fa97-945a-499e-9ec3-b35c5a51cbc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment Tender Activity Report'])[1]/preceding::a[1]</value>
      <webElementGuid>be7ebaaa-381e-4be6-80a0-41f4c749bc4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Posting File Report'])[1]/preceding::a[2]</value>
      <webElementGuid>a4fe660f-b5f7-4608-bc93-0903eac633c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Payment Account Activity Report']/parent::*</value>
      <webElementGuid>5bfed37f-abe5-408a-8851-f362c93d9160</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/admin/testcustomer/bootstrap/vclerk/reports/pymtacct.do?&amp;reset=true&amp;actionType=all')]</value>
      <webElementGuid>097d1177-f1f8-4660-819b-4c3e44535703</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/a</value>
      <webElementGuid>36676496-061e-4d41-9f8d-6ead485df57f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/admin/testcustomer/bootstrap/vclerk/reports/pymtacct.do?&amp;reset=true&amp;actionType=all' and (text() = 'Payment Account Activity Report' or . = 'Payment Account Activity Report')]</value>
      <webElementGuid>e879ba81-d9b9-4d21-adff-55f1798540bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
