<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_PeriodEnding_MFFT</name>
   <tag></tag>
   <elementGuidId>064745cb-ff21-4741-860a-5899992f8826</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'salesUseMonth' and @name = 'salesUseMonth']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='salesUseMonth']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#salesUseMonth</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9922fe48-ec4c-4071-a7f1-7c1840011217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>onMonthYearChange()</value>
      <webElementGuid>0cf41238-3b54-4d9c-a67d-e4bbb92bda1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>5f66322b-c3ec-49b3-b5ca-40a778562da2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>salesUseMonth</value>
      <webElementGuid>817c5bf9-ce71-46bd-968a-2a361d88f55c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>salesUseMonth</value>
      <webElementGuid>c3611f89-6340-429e-b0f6-fd9fd9c721e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Floating label select example</value>
      <webElementGuid>4e67bfbd-3ac8-4d35-81c7-09578da74469</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
										    Month
											January
											February
											March
											April
											May
											June
											July
											August
											September
											October
											November
											December
										  </value>
      <webElementGuid>8b9872a0-435a-4338-89e9-0830cd542663</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;salesUseMonth&quot;)</value>
      <webElementGuid>b290a6dd-587f-448e-8c83-678be71376e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='salesUseMonth']</value>
      <webElementGuid>1ced0c2d-6ea5-4416-a183-179da7d07b03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='taxForm']/div[3]/div[3]/div/select</value>
      <webElementGuid>82239061-35c1-4031-964f-113d5d14f789</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select a filing year'])[1]/following::select[1]</value>
      <webElementGuid>c77b1305-9b59-40d0-bf3f-ef9db225de0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filing Year:'])[1]/following::select[1]</value>
      <webElementGuid>7154ad70-d94c-4072-a5ac-21b6c911aa19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Period Ending:'])[1]/preceding::select[1]</value>
      <webElementGuid>7c50b0a7-7618-47d4-9849-b23a89caa8d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select reporting period'])[1]/preceding::select[1]</value>
      <webElementGuid>a2c45375-3fa9-4c13-b466-e547de48b3e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/select</value>
      <webElementGuid>c1e5a0e7-156a-444b-b42f-f4336f83b977</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
