<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_close</name>
   <tag></tag>
   <elementGuidId>de66adb1-3016-4f68-b6bb-b60b664723bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnClose</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnClose']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Close&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6dd053b3-c07c-4166-9ed4-08717edeef1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnClose</value>
      <webElementGuid>b4208bec-8a86-4786-b93e-67e7664bf0b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>98e7831d-56bb-46c9-99f0-e6ae33171ea8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>db112179-0072-4b80-9b24-0368c0d36cb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>custom_close()</value>
      <webElementGuid>512ec9bc-0229-4f07-b7a6-fcfa91059c68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnClose&quot;)</value>
      <webElementGuid>423e9d95-e006-4d79-94d3-6879efa78613</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnClose']</value>
      <webElementGuid>b9f12cb4-d1a4-44b3-a00b-f4c65ef86eb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='closeTable']/input</value>
      <webElementGuid>8aa152e7-5e49-484f-bcea-abc241606c26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>90ed3e3f-aaad-4384-b150-ddbb4086ca98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'btnClose' and @type = 'button']</value>
      <webElementGuid>74e0bbc0-ff7c-4463-8946-f20056427af0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
