<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dd_SelectPaymentApplication</name>
   <tag></tag>
   <elementGuidId>71a76d84-153b-45ad-9916-90c909c0a6fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'paymentApplicationId' and @id = 'paymentApplicationId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>paymentApplicationId</value>
      <webElementGuid>025975d6-ae44-4674-8a14-38a20ca6fcad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>paymentApplicationId</value>
      <webElementGuid>0c8d4fe1-8412-4057-921f-2fd7996ad1f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>faea161d-7845-4b05-b9ee-c4185849f029</webElementGuid>
   </webElementProperties>
</WebElementEntity>
