<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_User Transaction Summary By Tender Type Report</name>
   <tag></tag>
   <elementGuidId>97555af2-fd7a-4e88-a862-eeedc1426f32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#User_Reports4 > div.px-3.py-2 > a.report-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='User_Reports4']/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;User Transaction Summary By Tender Type Report&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c3bb6b86-68b9-44d4-b111-49bea2c48d23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>63a0aee6-e038-4739-bc8d-7eab8898ffe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>4f9debce-1a9b-4899-91ba-e128dd4ce41a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/admin/testcustomer/bootstrap/vclerk/reports/userreports.do?report=usertransactionsummerbytendertype&amp;actionType=user</value>
      <webElementGuid>02a1d4d9-2023-4615-b99a-f9535d419231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>report-name</value>
      <webElementGuid>6a32a347-c7a8-42c3-a3da-17dacf5d583b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-original-title</name>
      <type>Main</type>
      <value>View processing totals for one or more users over a given time period, itemized by payment tender.</value>
      <webElementGuid>83c9520f-3b1d-4a84-a755-6c8e98c561b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip533063</value>
      <webElementGuid>79aa0364-ca16-4482-937a-99520251a6c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>User Transaction Summary By Tender Type Report</value>
      <webElementGuid>4bf90917-ec2c-4960-99b6-5c6c46a6ed75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;User_Reports4&quot;)/div[@class=&quot;px-3 py-2&quot;]/a[@class=&quot;report-name&quot;]</value>
      <webElementGuid>7783a78d-c5f1-4b2c-a2b1-464018b46304</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='User_Reports4']/div/a</value>
      <webElementGuid>442de8df-1c3d-489e-ac81-bf63262ef418</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'User Transaction Summary By Tender Type Report')]</value>
      <webElementGuid>6cb6dd94-12fb-4b7c-8c37-843ff044e084</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Transaction Summary By Application Report'])[1]/following::a[1]</value>
      <webElementGuid>be4f5b54-0809-4dc3-84c7-2ae36ee7dc49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Transaction Detail Report'])[1]/following::a[2]</value>
      <webElementGuid>78baf39c-d3c6-46ea-bbee-5053f2e4fec8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='User Transaction Summary By Tender Type Report']/parent::*</value>
      <webElementGuid>76416a58-5dcb-4a75-9059-353a90fc4450</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/admin/testcustomer/bootstrap/vclerk/reports/userreports.do?report=usertransactionsummerbytendertype&amp;actionType=user')]</value>
      <webElementGuid>eaae58ed-ae9e-4052-b9ed-e2f13601678b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/a</value>
      <webElementGuid>e30abcaa-e03a-4c7d-9813-f3635f0e322c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/admin/testcustomer/bootstrap/vclerk/reports/userreports.do?report=usertransactionsummerbytendertype&amp;actionType=user' and (text() = 'User Transaction Summary By Tender Type Report' or . = 'User Transaction Summary By Tender Type Report')]</value>
      <webElementGuid>2bcd11b4-7c50-4cf6-99b4-36481cc49836</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
