<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Keyboard Entry_Prod</name>
   <tag></tag>
   <elementGuidId>98d709a9-820b-4c17-bb1c-3a4dd29d514c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='collapseOne']/div/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;collapseOne&quot;)/div[@class=&quot;card-body ml-4&quot;]/a[@class=&quot;ml-2&quot;][count(. | //*[(text() = 'Keyboard Entry' or . = 'Keyboard Entry')]) = count(//*[(text() = 'Keyboard Entry' or . = 'Keyboard Entry')])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.ml-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Keyboard Entry&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8620df38-c3da-49d8-ad58-4975c059fe8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ml-2</value>
      <webElementGuid>a0b94a3c-4cb8-4252-afc4-56dc60a63222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/admin/testcustomer/bootstrap/vpos/4585/transactions/AuthCapForm/</value>
      <webElementGuid>cc2de517-817f-4f6d-a511-1a3977f5e522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Keyboard Entry</value>
      <webElementGuid>3ac964f8-66c6-4559-a610-aa0f94f058a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapseOne&quot;)/div[@class=&quot;card-body ml-4&quot;]/a[@class=&quot;ml-2&quot;]</value>
      <webElementGuid>e49ac535-442d-4beb-874c-e696aa03959b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapseOne']/div/a</value>
      <webElementGuid>8475d519-6566-400b-a234-4eb07d590d5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Keyboard Entry')]</value>
      <webElementGuid>bc874b81-3e56-4428-9b5a-096bd63f50d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit Card'])[1]/following::a[1]</value>
      <webElementGuid>841e275d-095c-49a3-85c5-237ad0547a0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PIN Pad Entry'])[1]/preceding::a[1]</value>
      <webElementGuid>c40d3db2-e4b0-4b77-8736-83040ae7441f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Swipe'])[1]/preceding::a[2]</value>
      <webElementGuid>df032a75-ef87-4dc8-bea1-1b1519e2c07b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Keyboard Entry']/parent::*</value>
      <webElementGuid>f10a6d31-1796-4ad2-9e2c-75138fdfb86d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/admin/testcustomer/bootstrap/vpos/4585/transactions/AuthCapForm/')]</value>
      <webElementGuid>8508a752-b78c-4ae8-b328-0bc17a90013d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>e07a6969-360c-4af6-80e5-8afc2a0be9a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/admin/testcustomer/bootstrap/vpos/4585/transactions/AuthCapForm/' and (text() = 'Keyboard Entry' or . = 'Keyboard Entry')]</value>
      <webElementGuid>c4de436a-7d56-4b4d-981d-87e8af3291d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
