<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CCCreditOrVoid-App411</name>
   <tag></tag>
   <elementGuidId>43b6b8ab-afaa-4d6a-8518-b8bc543ef1d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.post-content > div.border-0.card.bg_light > div.bg-white.border-0.card-header > h2.mb-0 > a > button.btn.btn-link.btn-block.p-0.text-left</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[9]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and @href = '/admin/imtiaz/bootstrap/vpos/411/transactions/CCCreditOrVoidSearch/']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c1bf0cee-a164-4a75-a0df-77d12256c3d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-link btn-block p-0 text-left</value>
      <webElementGuid>a1fd9211-f45c-4776-a4a4-f184fa666911</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>04c0ee74-04ff-44dd-b89c-c9c2a8e67669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>78cde8e9-beaa-4d7e-82d1-6bdee4b3bbd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Credit or  Void </value>
      <webElementGuid>95e5fbc0-e378-4ca4-8afd-1cc1a985546e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;option1&quot;)/div[@class=&quot;d-flex&quot;]/div[@class=&quot;w-100 flex-shrink-1&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6  pr-4 pl-1&quot;]/div[@class=&quot;timeline-post&quot;]/div[@class=&quot;post-content&quot;]/div[@class=&quot;border-0 card bg_light&quot;]/div[@class=&quot;bg-white border-0 card-header&quot;]/h2[@class=&quot;mb-0&quot;]/a[1]/button[@class=&quot;btn btn-link btn-block p-0 text-left&quot;]</value>
      <webElementGuid>b777386b-b787-40d9-b911-0621750561e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/admin/imtiaz/bootstrap/vpos/411/transactions/CCCreditOrVoidSearch/</value>
      <webElementGuid>e1bfd2ab-b218-445d-ba2a-9e7dd6181140</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[9]</value>
      <webElementGuid>48045c93-3537-45d0-a562-31d520dea3cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='option1']/div/div/div/div[2]/div/div[2]/div[2]/div/h2/a/button</value>
      <webElementGuid>12e3a0c9-4f1f-470c-89f1-ffadc3850046</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='On-line Check'])[1]/following::button[2]</value>
      <webElementGuid>ff5ed933-68e3-49fd-a51d-5558a1118e65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Find Profile'])[2]/preceding::button[1]</value>
      <webElementGuid>31c0b15d-4b7f-4fc3-bac9-40e008c474df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Criteria :'])[1]/preceding::button[1]</value>
      <webElementGuid>d39039e3-3a4f-4676-9186-37b1b3047886</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/h2/a/button</value>
      <webElementGuid>89032d85-0038-45ef-966b-659c25fe467b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
