<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sale_Keyboard_Generic</name>
   <tag></tag>
   <elementGuidId>822ebd94-0507-41e4-9378-4ae1c4e092e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.ml-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='collapseOne']/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>becdc8db-0ff2-4042-9fed-e57fe4d18e08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ml-2</value>
      <webElementGuid>f5cb3f1e-5ac5-41bf-8efa-bef9b987eeb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/admin/imtiaz/bootstrap/vpos/818/transactions/AuthCapForm/</value>
      <webElementGuid>c5300462-69e7-4890-8bde-3ecc7fbdb770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Keyboard Entry</value>
      <webElementGuid>4674c1da-3086-4e08-a6ed-c01dba1a4728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapseOne&quot;)/div[@class=&quot;card-body ml-4&quot;]/a[@class=&quot;ml-2&quot;]</value>
      <webElementGuid>e818aa50-d5cb-4442-9f87-60fa9a29c350</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapseOne']/div/a</value>
      <webElementGuid>2a38078e-d39b-4877-9399-4011a32ee23c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Keyboard Entry')]</value>
      <webElementGuid>01363246-dfe3-42e0-a729-b1f824bf1a26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit Card'])[1]/following::a[1]</value>
      <webElementGuid>5d697a04-f798-4374-b46a-eb6345c61384</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keyboard Entry'])[2]/preceding::a[1]</value>
      <webElementGuid>23d172d4-dfea-4ee2-a967-1b2a2bba2fe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Keyboard Entry']/parent::*</value>
      <webElementGuid>a945991f-0288-40d0-b40d-a247a490eccd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/admin/imtiaz/bootstrap/vpos/818/transactions/AuthCapForm/')]</value>
      <webElementGuid>b05f04a0-d994-44d9-abec-e0195ae3935f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>bbf7b92e-b446-4d4b-8ac5-c11dd2abb672</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/admin/imtiaz/bootstrap/vpos/818/transactions/AuthCapForm/' and (text() = 'Keyboard Entry' or . = 'Keyboard Entry')]</value>
      <webElementGuid>c9652e2a-1aa8-4680-9775-ce95fcf64a9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
