<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_UDF4</name>
   <tag></tag>
   <elementGuidId>fe374eee-a644-4b01-be80-dc57eba04c88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;billDetailForms[0].billerDefinedField4&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='billDetailForms[0].billerDefinedField4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[alt=&quot;variable_field_4_label_916&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0352495d-1a3e-4aca-b96c-6522843dfc90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>392494b0-0ab4-4ff5-88be-cb1cfefb79f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billDetailForms[0].billerDefinedField4</value>
      <webElementGuid>e87562da-a8ff-41e7-b85c-3105ef8f03c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>6a4a60d7-9cce-410a-a829-95c6c92d0d78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>4df5b25f-4f38-4905-9bd5-7fe28bb8dba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>udf4</value>
      <webElementGuid>20f58318-1374-479a-b355-2d1406ba3c31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>customOnChangeUdf4(this, 916)</value>
      <webElementGuid>b1681e6c-ba08-4907-8cdd-3a332a7a516c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>01d2243c-4588-42af-8619-5abf1d2c6262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>variable_field_4_label_916</value>
      <webElementGuid>4de5a85b-a074-4cd6-a0c7-0bf7af40bc21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;udf1&quot;)/table[1]/tbody[1]/tr[4]/td[2]/input[1]</value>
      <webElementGuid>961bf103-3a88-4712-be71-9b5bc8af52ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='billDetailForms[0].billerDefinedField4']</value>
      <webElementGuid>f13e0d90-b0e0-425c-a4b8-a40af95c47e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='udf1']/table/tbody/tr[4]/td[2]/input</value>
      <webElementGuid>1cc75796-dceb-4128-9943-23667cd37f0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/input</value>
      <webElementGuid>96324444-a573-490a-98f3-b22cbd167f60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'billDetailForms[0].billerDefinedField4' and @alt = 'variable_field_4_label_916']</value>
      <webElementGuid>0ebe0bfe-ff04-430a-b85c-3537dc4992ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
