<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_United States</name>
   <tag></tag>
   <elementGuidId>71ea163c-d206-4ac9-b52d-3c6d9f8a3ad8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#countryId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='countryId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#countryId</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d227d979-0ba9-4fc9-9680-20ea66b5bbb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>paymentMethodForm.billingAddressForm.countryId</value>
      <webElementGuid>bb90588f-1d8e-4a95-8ad5-1c263cf746b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>linkageStateAndCountry(this.value)</value>
      <webElementGuid>2ed091f5-6743-45be-bdae-71aa39f61494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>countryId</value>
      <webElementGuid>5e2729f8-efa4-4f3e-a4a9-ef484148bf9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>United States</value>
      <webElementGuid>6675b701-73bc-408d-ac1e-434b195af70e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;countryId&quot;)</value>
      <webElementGuid>514abbc4-6d51-495f-8aa8-2591c7f8ea48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='countryId']</value>
      <webElementGuid>de728bf6-b715-4472-82fd-3c317d290fe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tblBillingAddress']/tbody/tr[4]/td[2]/select</value>
      <webElementGuid>6ba7e046-d67f-45ee-9832-dfc8576bf635</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[13]/following::select[1]</value>
      <webElementGuid>504298fe-a34b-4b42-a838-fc750d53ce21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country:'])[1]/following::select[1]</value>
      <webElementGuid>910f7240-0a9e-4e6d-9b36-d02a635dca7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ZIP'])[1]/preceding::select[1]</value>
      <webElementGuid>8467a947-6a81-461e-88e9-6460357037bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/select</value>
      <webElementGuid>7a0bf28a-6900-4fa4-b1ce-b56262f0a23a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'paymentMethodForm.billingAddressForm.countryId' and @id = 'countryId' and (text() = 'United States' or . = 'United States')]</value>
      <webElementGuid>38c36ab9-6d7f-412b-b8b0-e6cb8bf75041</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
