<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Year</name>
   <tag></tag>
   <elementGuidId>d0ad8233-3802-4076-9fa6-0120ecdcd14a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cardExpireYear</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cardExpireYear']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cardExpireYear</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9c0c78f8-b65a-445c-84ae-d47d8552a6e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>paymentMethodForm.cardExpireYear</value>
      <webElementGuid>15d350d9-38eb-4ad5-8fee-fa444de8cdb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cardExpireYear</value>
      <webElementGuid>858bdfd2-af96-4ce9-b484-c2513125cce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Year...
                                            2025
2026
2027
2028
2029
2030
2031
2032
2033
2034
2035
2036
2037
2038
2039</value>
      <webElementGuid>a0b25354-5b42-40e2-9a45-a998908bf3a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cardExpireYear&quot;)</value>
      <webElementGuid>0b60f0b1-e63b-49ea-9a35-aab9ce004894</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cardExpireYear']</value>
      <webElementGuid>93f1c19d-df90-40fb-aa65-4ce711e58af8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='area_creditCard']/table/tbody/tr[5]/td[2]/select[2]</value>
      <webElementGuid>1fa9a594-08d5-41de-9847-a518c309f3db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/following::select[2]</value>
      <webElementGuid>5261483d-c097-46c3-8b3e-cec93b794e52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expiration Date:'])[1]/following::select[2]</value>
      <webElementGuid>1d082f0d-5881-41a0-8be3-fd61fe5efc96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bank Account Information'])[1]/preceding::select[1]</value>
      <webElementGuid>8c276d80-b95c-4715-84b9-9e2a69026050</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company Name:'])[1]/preceding::select[1]</value>
      <webElementGuid>f8ae731b-3feb-495c-b3e6-4e9e8452b138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[2]</value>
      <webElementGuid>93fcbfb6-4247-42c6-a5a1-7291dbe6afd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'paymentMethodForm.cardExpireYear' and @id = 'cardExpireYear' and (text() = 'Year...
                                            2025
2026
2027
2028
2029
2030
2031
2032
2033
2034
2035
2036
2037
2038
2039' or . = 'Year...
                                            2025
2026
2027
2028
2029
2030
2031
2032
2033
2034
2035
2036
2037
2038
2039')]</value>
      <webElementGuid>48957c21-ed12-4315-90f8-ad9d8f3cedcd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
