<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_udf3</name>
   <tag></tag>
   <elementGuidId>1f76ed89-13e4-4ec3-9548-2367712d8dc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#udf1 > table > tbody > tr:nth-of-type(3) > td:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='udf1']/table/tbody/tr[3]/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;udf3&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>1af2a474-89dd-48b1-854f-510381a7cab8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
	                	udf3
	                </value>
      <webElementGuid>862e6b8e-450e-4dd2-bf75-6c72a217f28a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;udf1&quot;)/table[1]/tbody[1]/tr[3]/td[2]</value>
      <webElementGuid>ede366ec-bcd6-4221-baee-7c48297c37ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='udf1']/table/tbody/tr[3]/td[2]</value>
      <webElementGuid>7c3ac2c0-f3ce-4971-a278-c117f1a1777f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UDF3:'])[1]/following::td[1]</value>
      <webElementGuid>b296c80a-546b-41ab-a051-e172edb3f4b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::td[3]</value>
      <webElementGuid>32dc8914-3e56-4dea-a5c0-c2af23294f81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UDF4:'])[1]/preceding::td[1]</value>
      <webElementGuid>981c210e-ec98-411f-aa6e-a10f314c5d2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='udf3']/parent::*</value>
      <webElementGuid>7cd5b58a-4e3c-4e3b-8611-911d024f8777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/table/tbody/tr[3]/td[2]</value>
      <webElementGuid>3a9cbf5b-b298-45cf-8a98-f2ce78dc51a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '
	                	udf3
	                ' or . = '
	                	udf3
	                ')]</value>
      <webElementGuid>402724eb-ecf2-40e8-9a15-d786bc905d74</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
