<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ConfirmButton</name>
   <tag></tag>
   <elementGuidId>5464156d-91e3-4f15-954a-d6f18871afc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'confirmNotifyAction' and @value = 'Confirm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>confirmNotifyAction</value>
      <webElementGuid>06432276-004e-4704-b1e5-33ee0b63e691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Confirm</value>
      <webElementGuid>70d848ad-7b74-4593-9149-1d17930b0072</webElementGuid>
   </webElementProperties>
</WebElementEntity>
