<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Risk ManagementAudit Reports</name>
   <tag></tag>
   <elementGuidId>31bd3afe-c884-4402-ad36-56fad32a595b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Audit_Reports</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='Audit_Reports']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@title = 'Risk Management/Audit Reports' and @id = 'Audit_Reports' and (text() = 'Risk Management/Audit Reports' or . = 'Risk Management/Audit Reports')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>491501f2-2732-4c9d-b9b2-4b0ccdd65029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>treeview-item </value>
      <webElementGuid>f9d64372-224d-4066-b8ae-17e07fd684ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/admin/imtiaz/bootstrap/vclerk/index.do?actionType=audit</value>
      <webElementGuid>4428ae57-0df6-477e-bbb0-e45ce9969f46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Risk Management/Audit Reports</value>
      <webElementGuid>9849f1a5-2766-481c-8de1-bcdbcd9b596b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Audit_Reports</value>
      <webElementGuid>577e2ac1-5d69-4e93-8e54-1ce618b1ce74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Risk Management/Audit Reports</value>
      <webElementGuid>92e8f1ff-c6a3-4aa1-9fbb-7a832a6a600e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Audit_Reports&quot;)</value>
      <webElementGuid>94f83d70-7d46-43ae-9e1b-ede06d68308a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='Audit_Reports']</value>
      <webElementGuid>d4251553-c11a-4d4c-850d-fe157fc30db1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Risk Management/Audit Reports')]</value>
      <webElementGuid>1c8ea404-b2a9-4d4e-a292-8ae33595559d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operational Reports'])[1]/following::a[1]</value>
      <webElementGuid>fb8536a8-d220-468d-821c-c81320898cc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reporting'])[1]/following::a[2]</value>
      <webElementGuid>b33a4707-f50e-413f-ad12-0db0209f98f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Reports'])[1]/preceding::a[1]</value>
      <webElementGuid>813c5e2f-442a-4cef-9023-6d6987a06d84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Reports'])[1]/preceding::a[2]</value>
      <webElementGuid>5396560c-110a-4a9d-800c-62981b0cf2cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Risk Management/Audit Reports']/parent::*</value>
      <webElementGuid>b1304490-69f3-463a-9f67-4c8c65b9cc21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/admin/imtiaz/bootstrap/vclerk/index.do?actionType=audit')]</value>
      <webElementGuid>7f3fc958-e65c-4ad3-abe7-d232d7821bee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/ul/li[2]/a</value>
      <webElementGuid>c46cf6a4-3915-407a-9778-cc2ca4c5b6a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
