<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_LeftNavEmailTextToPay</name>
   <tag></tag>
   <elementGuidId>9caf982a-eff5-4afa-a050-6398ac5eb32b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/aside/ul/li[7]/a/span[count(. | //*[@class = 'app-menu__label']) = count(//*[@class = 'app-menu__label'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Email &amp;amp; Text to Pay Management</value>
      <webElementGuid>ea7fc6ea-3763-43e7-9af6-5d3bc3c8376b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>app-menu__label</value>
      <webElementGuid>97b46f74-ac43-4566-8d01-c257b5521069</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/aside/ul/li[7]/a/span</value>
      <webElementGuid>0f01944c-2c5b-4fc5-a0e4-cdd9d48bc055</webElementGuid>
   </webElementProperties>
</WebElementEntity>
