<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_LeftNavEmailTextToPay</name>
   <tag></tag>
   <elementGuidId>9caf982a-eff5-4afa-a050-6398ac5eb32b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Email &amp;amp; Text to Pay Management' or . = 'Email &amp;amp; Text to Pay Management')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Email &amp;amp; Text to Pay Management</value>
      <webElementGuid>6513e3f4-86d2-471d-ad83-122391cc017b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>app-menu__label</value>
      <webElementGuid>89fec319-90ad-4705-9e08-6bba20327b0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/aside/ul/li[7]/a/span</value>
      <webElementGuid>373f45d3-c625-43cf-a355-8d3541af2bb6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
