<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Amount_1303</name>
   <tag></tag>
   <elementGuidId>13e2edd7-6c51-4115-990a-4356d480cea8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @id = 'modifyAmount_90552168880000089']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9d770413-e613-4ef5-8bd6-de3ba1f550d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>modifyAmount_90552168880000089</value>
      <webElementGuid>6ce969d3-b15e-4d41-bfad-787f65e60028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>13.03</value>
      <webElementGuid>3f83a6e3-a9a3-4916-a1c7-0e6095901e79</webElementGuid>
   </webElementProperties>
</WebElementEntity>
