<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Amount_1651</name>
   <tag></tag>
   <elementGuidId>58062060-a3b4-4aef-9223-189c50a5ce96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @id = 'modifyAmount_90552168880000088']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>97dd2fb7-c881-4277-babe-efc800bb43b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>modifyAmount_90552168880000088</value>
      <webElementGuid>3203c8ef-284a-4e02-beb8-311129f861c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>16.51</value>
      <webElementGuid>11a163cb-714d-4367-aba7-82fc12cf64c8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
