<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Exit</name>
   <tag></tag>
   <elementGuidId>7dba0a3d-a3f3-4f15-8262-7d6bcbcc1ae0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#existButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='existButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>245121db-f9f6-4dda-b5d7-b6f19bd86377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bc7f6b2f-3baa-4f44-a4e9-7161c928d272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default btn-block</value>
      <webElementGuid>1527c9cd-812b-418d-8c6e-cd53526370a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>existButton</value>
      <webElementGuid>69605073-e9a9-4a49-a62a-5ddd08997ebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>location.href='https://www.dallascounty.org/departments/tax/?remittance_id=dfdsf5456gfdvxc&amp;security_id=1c593cfd513df7c6d269051783c183d3&amp;application_id=836';</value>
      <webElementGuid>67a713e1-4536-4d67-83c3-0f7f3d28f72a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Exit</value>
      <webElementGuid>58b6fb0d-ad73-4cd3-b047-9152bfa8c341</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>626d5f38-1c3a-470f-99bb-b7887e9287d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;existButton&quot;)</value>
      <webElementGuid>6576e006-b356-4509-8591-c021faee0fc1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='existButton']</value>
      <webElementGuid>6947e2d4-39b3-4579-9a1e-237477f88e00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='process']/table/tbody/tr[2]/td[2]/div[2]/div[3]/input</value>
      <webElementGuid>efb9bdbf-74e9-4bb2-999f-dc4fbc63fad8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>15885dcc-6b85-4ae8-831a-37a994900c5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'existButton']</value>
      <webElementGuid>a8506eac-e87e-4b6b-a40d-4996cf5fca20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
