<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dd_State</name>
   <tag></tag>
   <elementGuidId>9f245a2d-2a2c-4a26-9d68-f62e86231df0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'stateId' and @id = 'state']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>stateId</value>
      <webElementGuid>fd85de63-60bd-4dbd-b28f-5664970c71da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>stateId</value>
      <webElementGuid>388c47ec-76f5-41f9-b1c5-16fb73f4c530</webElementGuid>
   </webElementProperties>
</WebElementEntity>
