<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TermConditionCheckbox</name>
   <tag></tag>
   <elementGuidId>ee9f42be-a485-4736-925a-db922edd79ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'checkedAcceptCondition' and @id = 'checkedAcceptCondition' and @type = 'checkbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>checkedAcceptCondition</value>
      <webElementGuid>0c55787c-b021-4bab-bf95-59b6deb8f0dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkedAcceptCondition</value>
      <webElementGuid>5c4a8962-4327-403e-8fc9-b62c732f9c73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f2ef408e-2133-4f85-8785-78fae9d15e20</webElementGuid>
   </webElementProperties>
</WebElementEntity>
