<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_UDF5</name>
   <tag></tag>
   <elementGuidId>8466e299-9525-4578-8be5-dd8f33a5bf88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'userDefined5' and @id = 'userDefined5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>userDefined5</value>
      <webElementGuid>946445e4-c335-42fd-945f-043c415a1e7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>userDefined5</value>
      <webElementGuid>5f2643c0-88d1-449d-9693-cc322d583313</webElementGuid>
   </webElementProperties>
</WebElementEntity>
