<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_UDF8</name>
   <tag></tag>
   <elementGuidId>2e1c0614-294c-4501-b76a-303f7c139523</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'userDefined8' and @id = 'userDefined8']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>userDefined8</value>
      <webElementGuid>b6ebe422-5f4b-441a-bf82-9110ff8404a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>userDefined8</value>
      <webElementGuid>ec4ad179-8ee5-46b1-b72f-f97a04834cc4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
