<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_UDF9</name>
   <tag></tag>
   <elementGuidId>6f53d9fb-43bd-4c46-ae05-407246d3e710</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'userDefined9' and @id = 'userDefined9']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>userDefined9</value>
      <webElementGuid>171e5130-e99a-4034-837d-b7b2b89b4042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>userDefined9</value>
      <webElementGuid>885f9a13-b769-4c5a-9f55-4da3067a515e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
