<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ModifyButton</name>
   <tag></tag>
   <elementGuidId>83d42434-d910-49c2-bfe3-49954ca05920</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'confirmNotifyAction' and @value = 'Modify']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>confirmNotifyAction</value>
      <webElementGuid>087d1493-6c73-4840-b86a-e59ec85bdf57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Modify</value>
      <webElementGuid>563375ce-d44d-41d1-a1c8-57bd05099ed7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
